version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gomod
    directory: /credentials
    commit-message:
      prefix: "deps(credentials)"
    schedule:
      interval: daily
