#
# common UpCloud golangci-lint configuration
#

linters:
  #
  # we use a custom set of linters, so disable all and enable one-by-one
  #
  disable-all: true
  #
  # run golangci-lint linters or see https://golangci-lint.run/usage/linters/ for a list of all linters
  #
  # please keep these sorted alphabetically
  #
  enable:
    - asciicheck
    - bodyclose
    ## - cyclop # DISABLE
    - deadcode
    ## - depguard # DISABLE
    - dogsled
    - dupl
    ## - durationcheck # DISABLE
    - errcheck
    - errname
    - errorlint
    - exhaustive
    ## - exhaustivestruct # DISABLE
    - exportloopref
    - forbidigo
    - forcetypeassert
    # - funlen # OPTIONAL
    ## - gci # DISABLE
    # - gochecknoglobals # OPTIONAL
    # - gochecknoinits # OPTIONAL
    ## - gocognit # DISABLE
    - goconst
    - gocritic
    ## - gocyclo # DISABLE
    - godot
    # - godox # OPTIONAL
    ## - goerr113 # DISABLE
    ## - gofmt # DISABLE
    - gofumpt
    ## - goheader # DISABLE
    ## - goimports # DISABLE
    ### - golint # deprecated
    ## - gomnd # DISABLE
    # - gomoddirectives # OPTIONAL
    ## - gomodguard # DISABLE
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    ### - interfacer # deprecated
    ## - lll # DISABLE
    - makezero
    ### - maligned # deprecated
    - misspell
    - nakedret
    # - nestif # OPTIONAL
    - nilerr
    ## - nlreturn # DISABLE
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    ## - promlinter # DISABLE
    - revive
    - rowserrcheck
    ### - scopelint # deprecated
    - sqlclosecheck
    - staticcheck
    - structcheck
    ## - stylecheck # DISABLE
    ## - tagliatelle # DISABLE
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    ## - unparam # DSIABLE
    - unused
    - varcheck
    - wastedassign
    - whitespace
    # - wrapcheck # OPTIONAL
    ## - wsl # DISABLE

output:
  # make issues output unique by line, default is true
  uniq-by-line: false

issues:
  exclude:
    # disable warning about acronym capitalization, eg Id should 'ID'. Our convention is still in flux and this would break backwards compatibility.
    - "var-naming: .*should be.*"
    # disable warning about underscore in package names. capitalization, eg Id should 'ID'. Our convention is still in flux and this would break backwards compatibility.
    - "var-naming: don't use an underscore in package name"
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

linters-settings:
  gocritic:
    disabled-checks:
      # this is disabled due to commentFormatting not really understanding machine-readable comments and forcing an extra space for (some of) them
      - commentFormatting
  importas:
    no-unaliased: true
    alias:
      # enforce using `pkgerrors` alias for importing `github.com/pkg/errors`
      - pkg: github.com/pkg/errors
        alias: pkgerrors