# Golang CI pipeline configuration
linters:
  disable-all: true

  # Run golangci-lint linters to see the list of all linters
  # Please keep them sorted alphabetically
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - dogsled
    - errcheck
    - goconst
    - gofumpt
    - goimports
    # - golint # TODO: upgrade to revive and re-enable, needs breaking change due to wanting IpAddress -> IPAddress
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - rowserrcheck
    - staticcheck
    # - stylecheck # TODO: re-enable, needs breaking change due to wanting IpAddress -> IPAddress
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace

issues:
  uniq-by-line: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - bodyclose

linters-settings:
  goconst:
    min-len: 5
  predeclared:
    ignore: "new"
