// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AccountTokensProblem400Status.
const (
	AccountTokensProblem400StatusN400 AccountTokensProblem400Status = 400
)

// Valid indicates whether the value is a known member of the AccountTokensProblem400Status enum.
func (e AccountTokensProblem400Status) Valid() bool {
	switch e {
	case AccountTokensProblem400StatusN400:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem400Type.
const (
	AccountTokensProblem400TypeHttpsdevelopersUpcloudCom13errorsERRORBADREQUEST AccountTokensProblem400Type = "https://developers.upcloud.com/1.3/errors#ERROR_BAD_REQUEST"
)

// Valid indicates whether the value is a known member of the AccountTokensProblem400Type enum.
func (e AccountTokensProblem400Type) Valid() bool {
	switch e {
	case AccountTokensProblem400TypeHttpsdevelopersUpcloudCom13errorsERRORBADREQUEST:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem401Status.
const (
	AccountTokensProblem401StatusN401 AccountTokensProblem401Status = 401
)

// Valid indicates whether the value is a known member of the AccountTokensProblem401Status enum.
func (e AccountTokensProblem401Status) Valid() bool {
	switch e {
	case AccountTokensProblem401StatusN401:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem401Type.
const (
	AccountTokensProblem401TypeHttpsdevelopersUpcloudCom13errorsERRORUNAUTHORIZED AccountTokensProblem401Type = "https://developers.upcloud.com/1.3/errors#ERROR_UNAUTHORIZED"
)

// Valid indicates whether the value is a known member of the AccountTokensProblem401Type enum.
func (e AccountTokensProblem401Type) Valid() bool {
	switch e {
	case AccountTokensProblem401TypeHttpsdevelopersUpcloudCom13errorsERRORUNAUTHORIZED:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem403Status.
const (
	AccountTokensProblem403StatusN403 AccountTokensProblem403Status = 403
)

// Valid indicates whether the value is a known member of the AccountTokensProblem403Status enum.
func (e AccountTokensProblem403Status) Valid() bool {
	switch e {
	case AccountTokensProblem403StatusN403:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem403Type.
const (
	AccountTokensProblem403TypeHttpsdevelopersUpcloudCom13errorsERRORFORBIDDEN AccountTokensProblem403Type = "https://developers.upcloud.com/1.3/errors#ERROR_FORBIDDEN"
)

// Valid indicates whether the value is a known member of the AccountTokensProblem403Type enum.
func (e AccountTokensProblem403Type) Valid() bool {
	switch e {
	case AccountTokensProblem403TypeHttpsdevelopersUpcloudCom13errorsERRORFORBIDDEN:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem404Status.
const (
	AccountTokensProblem404StatusN404 AccountTokensProblem404Status = 404
)

// Valid indicates whether the value is a known member of the AccountTokensProblem404Status enum.
func (e AccountTokensProblem404Status) Valid() bool {
	switch e {
	case AccountTokensProblem404StatusN404:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem404Type.
const (
	AccountTokensProblem404TypeHttpsdevelopersUpcloudCom13errorsERRORNOTFOUND AccountTokensProblem404Type = "https://developers.upcloud.com/1.3/errors#ERROR_NOT_FOUND"
)

// Valid indicates whether the value is a known member of the AccountTokensProblem404Type enum.
func (e AccountTokensProblem404Type) Valid() bool {
	switch e {
	case AccountTokensProblem404TypeHttpsdevelopersUpcloudCom13errorsERRORNOTFOUND:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem409Status.
const (
	AccountTokensProblem409StatusN400 AccountTokensProblem409Status = 400
)

// Valid indicates whether the value is a known member of the AccountTokensProblem409Status enum.
func (e AccountTokensProblem409Status) Valid() bool {
	switch e {
	case AccountTokensProblem409StatusN400:
		return true
	default:
		return false
	}
}

// Defines values for AccountTokensProblem409Type.
const (
	AccountTokensProblem409TypeHttpsdevelopersUpcloudCom13errorsERRORSERVICEUNAVAILABLE AccountTokensProblem409Type = "https://developers.upcloud.com/1.3/errors#ERROR_SERVICE_UNAVAILABLE"
)

// Valid indicates whether the value is a known member of the AccountTokensProblem409Type enum.
func (e AccountTokensProblem409Type) Valid() bool {
	switch e {
	case AccountTokensProblem409TypeHttpsdevelopersUpcloudCom13errorsERRORSERVICEUNAVAILABLE:
		return true
	default:
		return false
	}
}

// AccountTokensCreateTokenRequest Examples: {"allowed_ip_ranges":["0.0.0.0/0","::/0"],"can_create_tokens":true,"expires_at":"2025-11-30T08:03:15.944Z","gui":false,"name":"token"}, {"allowed_ip_ranges":["0.0.0.0/0","::/0"],"can_create_tokens":true,"expires_in":"1h30min","gui":false,"name":"token"}
type AccountTokensCreateTokenRequest struct {
	// AllowedIpRanges List of IP ranges that are allowed to authenticate with the token. Empty list denies access from everywhere. If unset, the default list will be the IP filters of the account. If no IP filters are defined for the account either, the default will be ["0.0.0.0/0", "::/0"], i.e. allow from any address.
	//
	// Examples: ["0.0.0.0/0","::/0"]
	AllowedIpRanges *[]AccountTokensIpRange `json:"allowed_ip_ranges,omitempty"`

	// CanCreateTokens Whether the token can create other tokens.
	CanCreateTokens *bool `json:"can_create_tokens,omitempty"`

	// ExpiresAt The requested expiry time of the token, in RFC3339 format (2025-10-12T07:20:50.52Z). Needs to be in the future and maximum of 1 year in the future.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// ExpiresIn The requested duration until expiry of the token, e.g. '1h30min'. Needs to be a positive duration and maximum of 1 year. Can be used instead of `expires_at`. Supported units are 'h' for hours, 'm' for minutes and 's' for seconds.
	//
	// Examples: 8760h, 720h, 24h, 1h30m, 15m
	ExpiresIn *string `json:"expires_in,omitempty"`

	// Gui Token is for internal GUI use. Can not be used externally.
	Gui *bool `json:"gui,omitempty"`

	// Name The name of the token. Does not need to be unique.
	//
	// Examples: my first token
	Name  string `json:"name"`
	union json.RawMessage
}

// AccountTokensCreateTokenRequest0 defines model for AccountTokensCreateTokenRequest.0.
type AccountTokensCreateTokenRequest0 struct {
	ExpiresIn interface{} `json:"expires_in,omitempty"`
}

// AccountTokensCreateTokenRequest1 defines model for AccountTokensCreateTokenRequest.1.
type AccountTokensCreateTokenRequest1 struct {
	ExpiresAt interface{} `json:"expires_at,omitempty"`
}

// AccountTokensGetTokenResponse A token.
type AccountTokensGetTokenResponse struct {
	// AllowedIpRanges List of IP ranges that are allowed to authenticate with the token. Empty list denies access from everywhere. If unset, the default list will be the IP filters of the account. If no IP filters are defined for the account either, the default will be ["0.0.0.0/0", "::/0"], i.e. allow from any address.
	AllowedIpRanges *[]AccountTokensIpRange `json:"allowed_ip_ranges,omitempty"`

	// CanCreateTokens Whether the token can create other tokens.
	CanCreateTokens *bool `json:"can_create_tokens,omitempty"`

	// CreatedAt Token creation time.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// ExpiresAt The requested expiry time of the token, in RFC3339 format (2025-10-12T07:20:50.52Z). Needs to be in the future and maximum of 1 year in the future.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Gui Token is for internal GUI use. Can not be used externally.
	Gui *bool `json:"gui,omitempty"`

	// Id UUID of the token
	//
	// Examples: e7b3f8a0-4c2d-11ec-bf63-0242ac130002, e7b3f8a0-4c2d-11ec-bf63-0242ac130003, e7b3f8a0-4c2d-11ec-bf63-0242ac130004
	Id *AccountTokensUuidOfTheToken `json:"id,omitempty"`

	// LastUsedAt The last time the token was used.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`

	// Name The name of the token. Does not need to be unique.
	//
	// Examples: my first token
	Name *string `json:"name,omitempty"`
}

// AccountTokensIpRange IP range from where to accept the token
//
// Examples: 1.2.3.4, 2001:db8::1, 0.0.0.0/0, ::/0, 0.0.0.0-0.0.0.255, 2001:db8::1-2001:db8::ff
type AccountTokensIpRange = string

// AccountTokensListTokensResponse Paged list of tokens.
type AccountTokensListTokensResponse = []AccountTokensToken

// AccountTokensProblem JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Internal server error.","invalid_params":[{"name":"expires_at","reason":"Token expiration time must be in the future."}],"status":500,"title":"Internal server error.","type":"https://developers.upcloud.com/1.3/errors#INTERNAL_SERVER_ERROR"}
type AccountTokensProblem struct {
	// CorrelationId A unique identifier for the request. This identifier is generated by the server and can be used to track the request in the server logs. It is useful for debugging and support purposes.
	//
	// Examples: 01JQV2ETY2K6HHE1KZFY9E1CYC
	CorrelationId *string `json:"correlation_id,omitempty"`

	// Detail A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Invalid parameters.
	Detail *string `json:"detail,omitempty"`

	// InvalidParams Examples: [{"name":"expires_at","reason":"Token expiration time must be in the future."}]
	InvalidParams *[]struct {
		Name   string `json:"name"`
		Reason string `json:"reason"`
	} `json:"invalid_params,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status int32 `json:"status"`

	// Title A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Internal server error.
	Title string `json:"title"`

	// Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
	//
	// Examples: https://developers.upcloud.com/1.3/errors#INTERNAL_SERVER_ERROR
	Type string `json:"type"`
}

// AccountTokensProblem400 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Invalid parameters.","invalid_params":[{"name":"expires_at","reason":"Token expiration time must be in the future."}],"status":400,"title":"Bad request.","type":"https://developers.upcloud.com/1.3/errors#ERROR_BAD_REQUEST"}
type AccountTokensProblem400 struct {
	// CorrelationId A unique identifier for the request. This identifier is generated by the server and can be used to track the request in the server logs. It is useful for debugging and support purposes.
	//
	// Examples: 01JQV2ETY2K6HHE1KZFY9E1CYC
	CorrelationId *string `json:"correlation_id,omitempty"`

	// Detail A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Invalid parameters.
	Detail *string `json:"detail,omitempty"`

	// InvalidParams Examples: [{"name":"expires_at","reason":"Token expiration time must be in the future."}]
	InvalidParams *[]struct {
		Name   string `json:"name"`
		Reason string `json:"reason"`
	} `json:"invalid_params,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status AccountTokensProblem400Status `json:"status"`

	// Title A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Bad request.
	Title string `json:"title"`

	// Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
	Type AccountTokensProblem400Type `json:"type"`
}

// AccountTokensProblem400Status The HTTP status code generated by the origin server for this occurrence of the problem.
type AccountTokensProblem400Status int32

// AccountTokensProblem400Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
type AccountTokensProblem400Type string

// AccountTokensProblem401 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Access denied.","status":401,"title":"Unauthorized.","type":"https://developers.upcloud.com/1.3/errors#ERROR_UNAUTHORIZED"}
type AccountTokensProblem401 struct {
	// CorrelationId A unique identifier for the request. This identifier is generated by the server and can be used to track the request in the server logs. It is useful for debugging and support purposes.
	//
	// Examples: 01JQV2ETY2K6HHE1KZFY9E1CYC
	CorrelationId *string `json:"correlation_id,omitempty"`

	// Detail A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Invalid parameters.
	Detail *string `json:"detail,omitempty"`

	// InvalidParams Examples: [{"name":"expires_at","reason":"Token expiration time must be in the future."}]
	InvalidParams *[]struct {
		Name   string `json:"name"`
		Reason string `json:"reason"`
	} `json:"invalid_params,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status AccountTokensProblem401Status `json:"status"`

	// Title A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Unauthorized.
	Title string `json:"title"`

	// Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
	Type AccountTokensProblem401Type `json:"type"`
}

// AccountTokensProblem401Status The HTTP status code generated by the origin server for this occurrence of the problem.
type AccountTokensProblem401Status int32

// AccountTokensProblem401Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
type AccountTokensProblem401Type string

// AccountTokensProblem403 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Invalid parameters.","status":403,"title":"Bad request.","type":"https://developers.upcloud.com/1.3/errors#ERROR_FORBIDDEN"}
type AccountTokensProblem403 struct {
	// CorrelationId A unique identifier for the request. This identifier is generated by the server and can be used to track the request in the server logs. It is useful for debugging and support purposes.
	//
	// Examples: 01JQV2ETY2K6HHE1KZFY9E1CYC
	CorrelationId *string `json:"correlation_id,omitempty"`

	// Detail A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Invalid parameters.
	Detail *string `json:"detail,omitempty"`

	// InvalidParams Examples: [{"name":"expires_at","reason":"Token expiration time must be in the future."}]
	InvalidParams *[]struct {
		Name   string `json:"name"`
		Reason string `json:"reason"`
	} `json:"invalid_params,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status AccountTokensProblem403Status `json:"status"`

	// Title A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Bad request.
	Title string `json:"title"`

	// Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
	Type AccountTokensProblem403Type `json:"type"`
}

// AccountTokensProblem403Status The HTTP status code generated by the origin server for this occurrence of the problem.
type AccountTokensProblem403Status int32

// AccountTokensProblem403Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
type AccountTokensProblem403Type string

// AccountTokensProblem404 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"User not found.","status":404,"title":"Not found.","type":"https://developers.upcloud.com/1.3/errors#ERROR_NOT_FOUND"}
type AccountTokensProblem404 struct {
	// CorrelationId A unique identifier for the request. This identifier is generated by the server and can be used to track the request in the server logs. It is useful for debugging and support purposes.
	//
	// Examples: 01JQV2ETY2K6HHE1KZFY9E1CYC
	CorrelationId *string `json:"correlation_id,omitempty"`

	// Detail A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Invalid parameters.
	Detail *string `json:"detail,omitempty"`

	// InvalidParams Examples: [{"name":"expires_at","reason":"Token expiration time must be in the future."}]
	InvalidParams *[]struct {
		Name   string `json:"name"`
		Reason string `json:"reason"`
	} `json:"invalid_params,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status AccountTokensProblem404Status `json:"status"`

	// Title A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Not found.
	Title string `json:"title"`

	// Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
	Type AccountTokensProblem404Type `json:"type"`
}

// AccountTokensProblem404Status The HTTP status code generated by the origin server for this occurrence of the problem.
type AccountTokensProblem404Status int32

// AccountTokensProblem404Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
type AccountTokensProblem404Type string

// AccountTokensProblem409 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Try again later.","status":409,"title":"Service unavailable.","type":"https://developers.upcloud.com/1.3/errors#ERROR_SERVICE_UNAVAILABLE"}
type AccountTokensProblem409 struct {
	// CorrelationId A unique identifier for the request. This identifier is generated by the server and can be used to track the request in the server logs. It is useful for debugging and support purposes.
	//
	// Examples: 01JQV2ETY2K6HHE1KZFY9E1CYC
	CorrelationId *string `json:"correlation_id,omitempty"`

	// Detail A human readable explanation specific to this occurrence of the problem that is helpful to locate the problem and give advice on how to proceed. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Invalid parameters.
	Detail *string `json:"detail,omitempty"`

	// InvalidParams Examples: [{"name":"expires_at","reason":"Token expiration time must be in the future."}]
	InvalidParams *[]struct {
		Name   string `json:"name"`
		Reason string `json:"reason"`
	} `json:"invalid_params,omitempty"`

	// Status The HTTP status code generated by the origin server for this occurrence of the problem.
	Status AccountTokensProblem409Status `json:"status"`

	// Title A short summary of the problem type. Written in English and readable for engineers, usually not suited for non technical stakeholders and not localized.
	//
	// Examples: Service unavailable.
	Title string `json:"title"`

	// Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
	Type AccountTokensProblem409Type `json:"type"`
}

// AccountTokensProblem409Status The HTTP status code generated by the origin server for this occurrence of the problem.
type AccountTokensProblem409Status int32

// AccountTokensProblem409Type A URI reference that uniquely identifies the problem type only in the context of the provided API. It is neither recommended to be dereferenceable and point to a human-readable documentation nor globally unique for the problem type.
type AccountTokensProblem409Type string

// AccountTokensToken A token.
type AccountTokensToken struct {
	// AllowedIpRanges List of IP ranges that are allowed to authenticate with the token. Empty list denies access from everywhere. If unset, the default list will be the IP filters of the account. If no IP filters are defined for the account either, the default will be ["0.0.0.0/0", "::/0"], i.e. allow from any address.
	AllowedIpRanges *[]AccountTokensIpRange `json:"allowed_ip_ranges,omitempty"`

	// CanCreateTokens Whether the token can create other tokens.
	CanCreateTokens *bool `json:"can_create_tokens,omitempty"`

	// CreatedAt Token creation time.
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// ExpiresAt The requested expiry time of the token, in RFC3339 format (2025-10-12T07:20:50.52Z). Needs to be in the future and maximum of 1 year in the future.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`

	// Gui Token is for internal GUI use. Can not be used externally.
	Gui *bool `json:"gui,omitempty"`

	// Id UUID of the token
	//
	// Examples: e7b3f8a0-4c2d-11ec-bf63-0242ac130002, e7b3f8a0-4c2d-11ec-bf63-0242ac130003, e7b3f8a0-4c2d-11ec-bf63-0242ac130004
	Id *AccountTokensUuidOfTheToken `json:"id,omitempty"`

	// LastUsedAt The last time the token was used.
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`

	// Name The name of the token. Does not need to be unique.
	//
	// Examples: my first token
	Name *string `json:"name,omitempty"`
}

// AccountTokensUuidOfTheToken UUID of the token
//
// Examples: e7b3f8a0-4c2d-11ec-bf63-0242ac130002, e7b3f8a0-4c2d-11ec-bf63-0242ac130003, e7b3f8a0-4c2d-11ec-bf63-0242ac130004
type AccountTokensUuidOfTheToken = openapi_types.UUID

// AccountTokensGetTokenTokenUuid defines model for accountTokensGetTokenTokenUuid.
type AccountTokensGetTokenTokenUuid = openapi_types.UUID

// AccountTokensListTokensGui defines model for accountTokensListTokensGui.
type AccountTokensListTokensGui = bool

// AccountTokensListTokensLimit defines model for accountTokensListTokensLimit.
type AccountTokensListTokensLimit = int32

// AccountTokensListTokensOffset defines model for accountTokensListTokensOffset.
type AccountTokensListTokensOffset = int32

// AccountTokensListTokensSort defines model for accountTokensListTokensSort.
type AccountTokensListTokensSort = string

// AccountTokensRevokeTokenTokenUuid defines model for accountTokensRevokeTokenTokenUuid.
type AccountTokensRevokeTokenTokenUuid = openapi_types.UUID

// AccountTokensCreateToken201 A token.
type AccountTokensCreateToken201 = AccountTokensToken

// AccountTokensCreateToken400 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Invalid parameters.","invalid_params":[{"name":"expires_at","reason":"Token expiration time must be in the future."}],"status":400,"title":"Bad request.","type":"https://developers.upcloud.com/1.3/errors#ERROR_BAD_REQUEST"}
type AccountTokensCreateToken400 = AccountTokensProblem400

// AccountTokensCreateToken401 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Access denied.","status":401,"title":"Unauthorized.","type":"https://developers.upcloud.com/1.3/errors#ERROR_UNAUTHORIZED"}
type AccountTokensCreateToken401 = AccountTokensProblem401

// AccountTokensCreateToken403 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Invalid parameters.","status":403,"title":"Bad request.","type":"https://developers.upcloud.com/1.3/errors#ERROR_FORBIDDEN"}
type AccountTokensCreateToken403 = AccountTokensProblem403

// AccountTokensCreateToken409 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Try again later.","status":409,"title":"Service unavailable.","type":"https://developers.upcloud.com/1.3/errors#ERROR_SERVICE_UNAVAILABLE"}
type AccountTokensCreateToken409 = AccountTokensProblem409

// AccountTokensCreateTokenDefault JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Internal server error.","invalid_params":[{"name":"expires_at","reason":"Token expiration time must be in the future."}],"status":500,"title":"Internal server error.","type":"https://developers.upcloud.com/1.3/errors#INTERNAL_SERVER_ERROR"}
type AccountTokensCreateTokenDefault = AccountTokensProblem

// AccountTokensGetToken200 A token.
type AccountTokensGetToken200 = AccountTokensGetTokenResponse

// AccountTokensGetToken401 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Access denied.","status":401,"title":"Unauthorized.","type":"https://developers.upcloud.com/1.3/errors#ERROR_UNAUTHORIZED"}
type AccountTokensGetToken401 = AccountTokensProblem401

// AccountTokensGetToken404 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"User not found.","status":404,"title":"Not found.","type":"https://developers.upcloud.com/1.3/errors#ERROR_NOT_FOUND"}
type AccountTokensGetToken404 = AccountTokensProblem404

// AccountTokensGetTokenDefault JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Internal server error.","invalid_params":[{"name":"expires_at","reason":"Token expiration time must be in the future."}],"status":500,"title":"Internal server error.","type":"https://developers.upcloud.com/1.3/errors#INTERNAL_SERVER_ERROR"}
type AccountTokensGetTokenDefault = AccountTokensProblem

// AccountTokensListTokens200 Paged list of tokens.
type AccountTokensListTokens200 = AccountTokensListTokensResponse

// AccountTokensListTokens401 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Access denied.","status":401,"title":"Unauthorized.","type":"https://developers.upcloud.com/1.3/errors#ERROR_UNAUTHORIZED"}
type AccountTokensListTokens401 = AccountTokensProblem401

// AccountTokensListTokensDefault JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Internal server error.","invalid_params":[{"name":"expires_at","reason":"Token expiration time must be in the future."}],"status":500,"title":"Internal server error.","type":"https://developers.upcloud.com/1.3/errors#INTERNAL_SERVER_ERROR"}
type AccountTokensListTokensDefault = AccountTokensProblem

// AccountTokensRevokeToken401 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Access denied.","status":401,"title":"Unauthorized.","type":"https://developers.upcloud.com/1.3/errors#ERROR_UNAUTHORIZED"}
type AccountTokensRevokeToken401 = AccountTokensProblem401

// AccountTokensRevokeToken404 JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"User not found.","status":404,"title":"Not found.","type":"https://developers.upcloud.com/1.3/errors#ERROR_NOT_FOUND"}
type AccountTokensRevokeToken404 = AccountTokensProblem404

// AccountTokensRevokeTokenDefault JSON Problem Details for HTTP APIs
//
// Examples: {"correlation_id":"01JQV2ETY2K6HHE1KZFY9E1CYC","detail":"Internal server error.","invalid_params":[{"name":"expires_at","reason":"Token expiration time must be in the future."}],"status":500,"title":"Internal server error.","type":"https://developers.upcloud.com/1.3/errors#INTERNAL_SERVER_ERROR"}
type AccountTokensRevokeTokenDefault = AccountTokensProblem

// AccountTokensCreateToken Examples: {"allowed_ip_ranges":["0.0.0.0/0","::/0"],"can_create_tokens":true,"expires_at":"2025-11-30T08:03:15.944Z","gui":false,"name":"token"}, {"allowed_ip_ranges":["0.0.0.0/0","::/0"],"can_create_tokens":true,"expires_in":"1h30min","gui":false,"name":"token"}
type AccountTokensCreateToken = AccountTokensCreateTokenRequest

// ListTokensParams defines parameters for ListTokens.
type ListTokensParams struct {
	// Limit How many tokens to return at per page
	Limit *AccountTokensListTokensLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Offset to start listing the tokens from
	Offset *AccountTokensListTokensOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// Gui Filter tokens based on GUI flag (true or false). Default is no value, i.e. no filtering and all tokens are returned.
	Gui *AccountTokensListTokensGui `form:"gui,omitempty" json:"gui,omitempty"`

	// Sort Comma-separated list of fields to sort by. Prefix with '+' for ascending or '-' for descending order. Supported fields: created_at, expires_at, last_used_at, name. Example: sort=+name,-created_at. If no prefix is given, descending is assumed. Follows OpenAPI collectionFormat 'csv'.
	Sort *AccountTokensListTokensSort `form:"sort,omitempty" json:"sort,omitempty"`
}

// CreateTokenJSONRequestBody defines body for CreateToken for application/json ContentType.
type CreateTokenJSONRequestBody = AccountTokensCreateTokenRequest

// AsAccountTokensCreateTokenRequest0 returns the union data inside the AccountTokensCreateTokenRequest as a AccountTokensCreateTokenRequest0
func (t AccountTokensCreateTokenRequest) AsAccountTokensCreateTokenRequest0() (AccountTokensCreateTokenRequest0, error) {
	var body AccountTokensCreateTokenRequest0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAccountTokensCreateTokenRequest0 overwrites any union data inside the AccountTokensCreateTokenRequest as the provided AccountTokensCreateTokenRequest0
func (t *AccountTokensCreateTokenRequest) FromAccountTokensCreateTokenRequest0(v AccountTokensCreateTokenRequest0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAccountTokensCreateTokenRequest0 performs a merge with any union data inside the AccountTokensCreateTokenRequest, using the provided AccountTokensCreateTokenRequest0
func (t *AccountTokensCreateTokenRequest) MergeAccountTokensCreateTokenRequest0(v AccountTokensCreateTokenRequest0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAccountTokensCreateTokenRequest1 returns the union data inside the AccountTokensCreateTokenRequest as a AccountTokensCreateTokenRequest1
func (t AccountTokensCreateTokenRequest) AsAccountTokensCreateTokenRequest1() (AccountTokensCreateTokenRequest1, error) {
	var body AccountTokensCreateTokenRequest1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAccountTokensCreateTokenRequest1 overwrites any union data inside the AccountTokensCreateTokenRequest as the provided AccountTokensCreateTokenRequest1
func (t *AccountTokensCreateTokenRequest) FromAccountTokensCreateTokenRequest1(v AccountTokensCreateTokenRequest1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAccountTokensCreateTokenRequest1 performs a merge with any union data inside the AccountTokensCreateTokenRequest, using the provided AccountTokensCreateTokenRequest1
func (t *AccountTokensCreateTokenRequest) MergeAccountTokensCreateTokenRequest1(v AccountTokensCreateTokenRequest1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t AccountTokensCreateTokenRequest) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.AllowedIpRanges != nil {
		object["allowed_ip_ranges"], err = json.Marshal(t.AllowedIpRanges)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'allowed_ip_ranges': %w", err)
		}
	}

	if t.CanCreateTokens != nil {
		object["can_create_tokens"], err = json.Marshal(t.CanCreateTokens)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'can_create_tokens': %w", err)
		}
	}

	if t.ExpiresAt != nil {
		object["expires_at"], err = json.Marshal(t.ExpiresAt)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expires_at': %w", err)
		}
	}

	if t.ExpiresIn != nil {
		object["expires_in"], err = json.Marshal(t.ExpiresIn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expires_in': %w", err)
		}
	}

	if t.Gui != nil {
		object["gui"], err = json.Marshal(t.Gui)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'gui': %w", err)
		}
	}

	object["name"], err = json.Marshal(t.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	b, err = json.Marshal(object)
	return b, err
}

func (t *AccountTokensCreateTokenRequest) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["allowed_ip_ranges"]; found {
		err = json.Unmarshal(raw, &t.AllowedIpRanges)
		if err != nil {
			return fmt.Errorf("error reading 'allowed_ip_ranges': %w", err)
		}
	}

	if raw, found := object["can_create_tokens"]; found {
		err = json.Unmarshal(raw, &t.CanCreateTokens)
		if err != nil {
			return fmt.Errorf("error reading 'can_create_tokens': %w", err)
		}
	}

	if raw, found := object["expires_at"]; found {
		err = json.Unmarshal(raw, &t.ExpiresAt)
		if err != nil {
			return fmt.Errorf("error reading 'expires_at': %w", err)
		}
	}

	if raw, found := object["expires_in"]; found {
		err = json.Unmarshal(raw, &t.ExpiresIn)
		if err != nil {
			return fmt.Errorf("error reading 'expires_in': %w", err)
		}
	}

	if raw, found := object["gui"]; found {
		err = json.Unmarshal(raw, &t.Gui)
		if err != nil {
			return fmt.Errorf("error reading 'gui': %w", err)
		}
	}

	if raw, found := object["name"]; found {
		err = json.Unmarshal(raw, &t.Name)
		if err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
	}

	return err
}
