// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// The interface specification for the client above.
type AccountClientInterface interface {
	// AccountDetails request
	AccountDetails(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateMSLMASigningLink request
	CreateMSLMASigningLink(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) AccountDetails(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAccountDetailsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateMSLMASigningLink(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateMSLMASigningLinkRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAccountDetailsRequest generates requests for AccountDetails
func NewAccountDetailsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/account")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateMSLMASigningLinkRequest generates requests for CreateMSLMASigningLink
func NewCreateMSLMASigningLinkRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/account/ms_lma")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type AccountClientWithResponsesInterface interface {
	// AccountDetailsWithResponse request
	AccountDetailsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AccountDetailsResp, error)

	// CreateMSLMASigningLinkWithResponse request
	CreateMSLMASigningLinkWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CreateMSLMASigningLinkResp, error)
}

type AccountDetailsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *AccountDetails200
	JSONDefault  *AccountDetailsDefault
}

// Status returns HTTPResponse.Status
func (r AccountDetailsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AccountDetailsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateMSLMASigningLinkResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *AccountCreateMSLMASigningLink201
	JSONDefault  *AccountCreateMSLMASigningLinkDefault
}

// Status returns HTTPResponse.Status
func (r CreateMSLMASigningLinkResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateMSLMASigningLinkResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// AccountDetailsWithResponse request returning *AccountDetailsResp
func (c *ClientWithResponses) AccountDetailsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*AccountDetailsResp, error) {
	rsp, err := c.AccountDetails(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAccountDetailsResp(rsp)
}

// CreateMSLMASigningLinkWithResponse request returning *CreateMSLMASigningLinkResp
func (c *ClientWithResponses) CreateMSLMASigningLinkWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*CreateMSLMASigningLinkResp, error) {
	rsp, err := c.CreateMSLMASigningLink(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateMSLMASigningLinkResp(rsp)
}

// ParseAccountDetailsResp parses an HTTP response from a AccountDetailsWithResponse call
func ParseAccountDetailsResp(rsp *http.Response) (*AccountDetailsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AccountDetailsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AccountDetails200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest AccountDetailsDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateMSLMASigningLinkResp parses an HTTP response from a CreateMSLMASigningLinkWithResponse call
func ParseCreateMSLMASigningLinkResp(rsp *http.Response) (*CreateMSLMASigningLinkResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateMSLMASigningLinkResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest AccountCreateMSLMASigningLink201
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest AccountCreateMSLMASigningLinkDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
