// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// The interface specification for the client above.
type AuditLogsClientInterface interface {

	// ListAuditLogs List audit logs
	//
	// Returns a list of audit log rows according to the query parameters. Note that this endpoint is paginated by default and the list is limited in results.
	//
	// Pagination
	// Upcloud-Total-Count header is included in the response to indicate the total number of audit logs available with the current query parameters (excluding limit and offset). The total count can be used for a number of pagination strategies. limit and offset query parameters can be used to finally paginate the results.
	//
	// Corresponds with GET /1.3/audit-logs (the `ListAuditLogs` operationId).
	ListAuditLogs(ctx context.Context, params *ListAuditLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ExportAuditLogs Export audit logs
	//
	// Export all audit logs for the authenticated account as CSV or JSON (up to 180 day limit). Note: Use the format parameter to specify output format; only JSON schema is documented here.
	//
	// Corresponds with GET /1.3/audit-logs/export (the `ExportAuditLogs` operationId).
	ExportAuditLogs(ctx context.Context, params *ExportAuditLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetFilterOptions Get filter options
	//
	// Returns lists of available resource types, actions, and origins for filtering.
	//
	// Corresponds with GET /1.3/audit-logs/filter-options (the `GetFilterOptions` operationId).
	GetFilterOptions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetAuditLog Get event details
	//
	// Returns details of a single audit log event by its cloud event ID.
	//
	// Corresponds with GET /1.3/audit-logs/{cloudEventID} (the `GetAuditLog` operationId).
	GetAuditLog(ctx context.Context, cloudEventID AuditLogsGetAuditLogCloudEventID, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListAuditLogs List audit logs
//
// Returns a list of audit log rows according to the query parameters. Note that this endpoint is paginated by default and the list is limited in results.
//
// Pagination
// Upcloud-Total-Count header is included in the response to indicate the total number of audit logs available with the current query parameters (excluding limit and offset). The total count can be used for a number of pagination strategies. limit and offset query parameters can be used to finally paginate the results.
//
// Corresponds with GET /1.3/audit-logs (the `ListAuditLogs` operationId).
func (c *Client) ListAuditLogs(ctx context.Context, params *ListAuditLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAuditLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ExportAuditLogs Export audit logs
//
// Export all audit logs for the authenticated account as CSV or JSON (up to 180 day limit). Note: Use the format parameter to specify output format; only JSON schema is documented here.
//
// Corresponds with GET /1.3/audit-logs/export (the `ExportAuditLogs` operationId).
func (c *Client) ExportAuditLogs(ctx context.Context, params *ExportAuditLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExportAuditLogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetFilterOptions Get filter options
//
// Returns lists of available resource types, actions, and origins for filtering.
//
// Corresponds with GET /1.3/audit-logs/filter-options (the `GetFilterOptions` operationId).
func (c *Client) GetFilterOptions(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFilterOptionsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetAuditLog Get event details
//
// Returns details of a single audit log event by its cloud event ID.
//
// Corresponds with GET /1.3/audit-logs/{cloudEventID} (the `GetAuditLog` operationId).
func (c *Client) GetAuditLog(ctx context.Context, cloudEventID AuditLogsGetAuditLogCloudEventID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetAuditLogRequest(c.Server, cloudEventID)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAuditLogsRequest constructs an http.Request for the ListAuditLogs method
func NewListAuditLogsRequest(server string, params *ListAuditLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/audit-logs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Q != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "q", *params.Q, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Offset != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "offset", *params.Offset, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int32"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Actions != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "actions", *params.Actions, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Origins != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "origins", *params.Origins, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.ResourceTypes != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "resource_types", *params.ResourceTypes, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "array", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.CreatedAfter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "created_after", *params.CreatedAfter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.CreatedBefore != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "created_before", *params.CreatedBefore, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewExportAuditLogsRequest constructs an http.Request for the ExportAuditLogs method
func NewExportAuditLogsRequest(server string, params *ExportAuditLogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/audit-logs/export")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Format != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "format", *params.Format, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetFilterOptionsRequest constructs an http.Request for the GetFilterOptions method
func NewGetFilterOptionsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/audit-logs/filter-options")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetAuditLogRequest constructs an http.Request for the GetAuditLog method
func NewGetAuditLogRequest(server string, cloudEventID AuditLogsGetAuditLogCloudEventID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "cloudEventID", cloudEventID, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/audit-logs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type AuditLogsClientWithResponsesInterface interface {

	// ListAuditLogsWithResponse List audit logs
	//
	// Returns a list of audit log rows according to the query parameters. Note that this endpoint is paginated by default and the list is limited in results.
	//
	// Pagination
	// Upcloud-Total-Count header is included in the response to indicate the total number of audit logs available with the current query parameters (excluding limit and offset). The total count can be used for a number of pagination strategies. limit and offset query parameters can be used to finally paginate the results.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /1.3/audit-logs (the `ListAuditLogs` operationId).
	ListAuditLogsWithResponse(ctx context.Context, params *ListAuditLogsParams, reqEditors ...RequestEditorFn) (*ListAuditLogsResp, error)

	// ExportAuditLogsWithResponse Export audit logs
	//
	// Export all audit logs for the authenticated account as CSV or JSON (up to 180 day limit). Note: Use the format parameter to specify output format; only JSON schema is documented here.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /1.3/audit-logs/export (the `ExportAuditLogs` operationId).
	ExportAuditLogsWithResponse(ctx context.Context, params *ExportAuditLogsParams, reqEditors ...RequestEditorFn) (*ExportAuditLogsResp, error)

	// GetFilterOptionsWithResponse Get filter options
	//
	// Returns lists of available resource types, actions, and origins for filtering.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /1.3/audit-logs/filter-options (the `GetFilterOptions` operationId).
	GetFilterOptionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetFilterOptionsResp, error)

	// GetAuditLogWithResponse Get event details
	//
	// Returns details of a single audit log event by its cloud event ID.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /1.3/audit-logs/{cloudEventID} (the `GetAuditLog` operationId).
	GetAuditLogWithResponse(ctx context.Context, cloudEventID AuditLogsGetAuditLogCloudEventID, reqEditors ...RequestEditorFn) (*GetAuditLogResp, error)
}

// ListAuditLogsResp200Headers the declared response headers of an HTTP 200 response for ListAuditLogs
type ListAuditLogsResp200Headers struct {
	UpCloudTotalCount *int64
}

type ListAuditLogsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListAuditLogs200
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ListAuditLogsDefault
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *ListAuditLogsResp200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListAuditLogsResp) GetJSON200() *ListAuditLogs200 {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r ListAuditLogsResp) GetApplicationproblemJSONDefault() *ListAuditLogsDefault {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r ListAuditLogsResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListAuditLogsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListAuditLogsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListAuditLogsResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ExportAuditLogsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ExportAuditLogs200
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *ExportAuditLogsDefault
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ExportAuditLogsResp) GetJSON200() *ExportAuditLogs200 {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r ExportAuditLogsResp) GetApplicationproblemJSONDefault() *ExportAuditLogsDefault {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r ExportAuditLogsResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ExportAuditLogsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExportAuditLogsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExportAuditLogsResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetFilterOptionsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AuditLogsGetFilterOptions200
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *AuditLogsGetFilterOptionsDefault
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetFilterOptionsResp) GetJSON200() *AuditLogsGetFilterOptions200 {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetFilterOptionsResp) GetApplicationproblemJSONDefault() *AuditLogsGetFilterOptionsDefault {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetFilterOptionsResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetFilterOptionsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFilterOptionsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetFilterOptionsResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetAuditLogResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AuditLogsGetAuditLog200
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *AuditLogsGetAuditLogDefault
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetAuditLogResp) GetJSON200() *AuditLogsGetAuditLog200 {
	return r.JSON200
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetAuditLogResp) GetApplicationproblemJSONDefault() *AuditLogsGetAuditLogDefault {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetAuditLogResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetAuditLogResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetAuditLogResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetAuditLogResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListAuditLogsWithResponse List audit logs
//
// Returns a list of audit log rows according to the query parameters. Note that this endpoint is paginated by default and the list is limited in results.
//
// Pagination
// Upcloud-Total-Count header is included in the response to indicate the total number of audit logs available with the current query parameters (excluding limit and offset). The total count can be used for a number of pagination strategies. limit and offset query parameters can be used to finally paginate the results.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /1.3/audit-logs (the `ListAuditLogs` operationId).
func (c *ClientWithResponses) ListAuditLogsWithResponse(ctx context.Context, params *ListAuditLogsParams, reqEditors ...RequestEditorFn) (*ListAuditLogsResp, error) {
	rsp, err := c.ListAuditLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListAuditLogsResp(rsp)
}

// ExportAuditLogsWithResponse Export audit logs
//
// Export all audit logs for the authenticated account as CSV or JSON (up to 180 day limit). Note: Use the format parameter to specify output format; only JSON schema is documented here.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /1.3/audit-logs/export (the `ExportAuditLogs` operationId).
func (c *ClientWithResponses) ExportAuditLogsWithResponse(ctx context.Context, params *ExportAuditLogsParams, reqEditors ...RequestEditorFn) (*ExportAuditLogsResp, error) {
	rsp, err := c.ExportAuditLogs(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExportAuditLogsResp(rsp)
}

// GetFilterOptionsWithResponse Get filter options
//
// Returns lists of available resource types, actions, and origins for filtering.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /1.3/audit-logs/filter-options (the `GetFilterOptions` operationId).
func (c *ClientWithResponses) GetFilterOptionsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetFilterOptionsResp, error) {
	rsp, err := c.GetFilterOptions(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFilterOptionsResp(rsp)
}

// GetAuditLogWithResponse Get event details
//
// Returns details of a single audit log event by its cloud event ID.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /1.3/audit-logs/{cloudEventID} (the `GetAuditLog` operationId).
func (c *ClientWithResponses) GetAuditLogWithResponse(ctx context.Context, cloudEventID AuditLogsGetAuditLogCloudEventID, reqEditors ...RequestEditorFn) (*GetAuditLogResp, error) {
	rsp, err := c.GetAuditLog(ctx, cloudEventID, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetAuditLogResp(rsp)
}

// ParseListAuditLogsResp parses an HTTP response from a ListAuditLogsWithResponse call
func ParseListAuditLogsResp(rsp *http.Response) (*ListAuditLogsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListAuditLogsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListAuditLogs200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ListAuditLogsDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers ListAuditLogsResp200Headers
		if values := rsp.Header.Values("UpCloud-Total-Count"); len(values) > 0 {
			var value int64
			if err := runtime.BindStyledParameterWithOptions("simple", "UpCloud-Total-Count", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: "int64"}); err != nil {
				return nil, err
			}
			headers.UpCloudTotalCount = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseExportAuditLogsResp parses an HTTP response from a ExportAuditLogsWithResponse call
func ParseExportAuditLogsResp(rsp *http.Response) (*ExportAuditLogsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExportAuditLogsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ExportAuditLogs200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ExportAuditLogsDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetFilterOptionsResp parses an HTTP response from a GetFilterOptionsWithResponse call
func ParseGetFilterOptionsResp(rsp *http.Response) (*GetFilterOptionsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFilterOptionsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuditLogsGetFilterOptions200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest AuditLogsGetFilterOptionsDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetAuditLogResp parses an HTTP response from a GetAuditLogWithResponse call
func ParseGetAuditLogResp(rsp *http.Response) (*GetAuditLogResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetAuditLogResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AuditLogsGetAuditLog200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest AuditLogsGetAuditLogDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
