// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	"time"
)

// CurrencyCode ISO 4217 code
type CurrencyCode = string

// CurrencyCurrencies defines model for currencyCurrencies.
type CurrencyCurrencies struct {
	Currencies struct {
		Currency []struct {
			// Code ISO 4217 code
			Code    CurrencyCode `json:"code"`
			Rate    float64      `json:"rate"`
			Updated time.Time    `json:"updated"`
		} `json:"currency"`
	} `json:"currencies"`
}

// CurrencyError A general error response indicating that the request could not be fulfilled due to a technical issue.
type CurrencyError struct {
	Error struct {
		// ErrorCode Examples: GENERAL_FAILURE
		ErrorCode string `json:"error_code"`

		// ErrorMessage Examples: Your request could not be fulfilled due to a technical issue.
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// CurrencyListCurrencies200 defines model for currencyListCurrencies200.
type CurrencyListCurrencies200 = CurrencyCurrencies

// CurrencyListCurrenciesDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CurrencyListCurrenciesDefault = CurrencyError
