// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventsEventType.
const (
	ServerCreate    EventsEventType = "server_create"
	ServerError     EventsEventType = "server_error"
	ServerModify    EventsEventType = "server_modify"
	ServerShutdown  EventsEventType = "server_shutdown"
	ServerStart     EventsEventType = "server_start"
	ServerStartInit EventsEventType = "server_start_init"
	ServerStop      EventsEventType = "server_stop"
)

// Valid indicates whether the value is a known member of the EventsEventType enum.
func (e EventsEventType) Valid() bool {
	switch e {
	case ServerCreate:
		return true
	case ServerError:
		return true
	case ServerModify:
		return true
	case ServerShutdown:
		return true
	case ServerStart:
		return true
	case ServerStartInit:
		return true
	case ServerStop:
		return true
	default:
		return false
	}
}

// DatabaseDependencyResponse a dependency definition
type DatabaseDependencyResponse struct {
	// Required List of required properties when this dependency is present
	Required *[]string `json:"required,omitempty"`
}

// DatabasePropertySchemaResponse Schema definition for a single property
type DatabasePropertySchemaResponse struct {
	// Id Schema identifier
	Id *string `json:"$id,omitempty"`

	// Schema JSON Schema URI
	Schema *string `json:"$schema,omitempty"`

	// AdditionalProperties Whether additional properties are allowed
	AdditionalProperties *bool `json:"additionalProperties,omitempty"`

	// CreateOnly Whether the property can only be set during creation
	CreateOnly *bool `json:"createOnly,omitempty"`

	// Default Any valid JSON value is allowed here
	Default *map[string]interface{} `json:"default,omitempty"`

	// Dependencies Property dependency collection
	Dependencies *map[string]DatabaseDependencyResponse `json:"dependencies,omitempty"`

	// Description Description of the property
	Description *string `json:"description,omitempty"`

	// Enum Enumeration of allowed values
	Enum *[]interface{} `json:"enum,omitempty"`

	// Example Any valid JSON value is allowed here
	Example *map[string]interface{} `json:"example,omitempty"`

	// Items Schema definition for a single property
	Items *DatabasePropertySchemaResponse `json:"items,omitempty"`

	// MaxItems Maximum number of items for arrays
	MaxItems *int32 `json:"maxItems,omitempty"`

	// MaxLength Maximum length for the property schema
	MaxLength *int32 `json:"maxLength,omitempty"`

	// Maximum Maximum values for numeric properties
	Maximum *[]map[string]interface{} `json:"maximum,omitempty"`

	// MinLength Minimum length for the property schema
	MinLength *int32 `json:"minLength,omitempty"`

	// Minimum Minimum values for numeric properties
	Minimum *[]map[string]interface{} `json:"minimum,omitempty"`

	// Pattern Allowed patterns for the property
	Pattern *string `json:"pattern,omitempty"`

	// Properties Properties for object type
	Properties *map[string]DatabasePropertySchemaResponse `json:"properties,omitempty"`

	// Required List of required properties
	Required *[]string `json:"required,omitempty"`

	// Title Human-readable title for the property
	Title *string `json:"title,omitempty"`

	// Type Data type of the property
	Type *string `json:"type,omitempty"`

	// UserError User-friendly error message
	UserError *string `json:"user_error,omitempty"`
}

// Events Server event type
type Events struct {
	Events *struct {
		// Event List of events associated with servers
		Event []struct {
			Email     *openapi_types.Email `json:"email,omitempty"`
			FirstName *string              `json:"first_name,omitempty"`
			LastName  *string              `json:"last_name,omitempty"`

			// Server Universally unique identifier
			Server EventsUuid `json:"server"`

			// Time Timestamp of when the event occurred
			Time time.Time `json:"time"`

			// Type Server event type
			Type EventsEventType `json:"type"`
		} `json:"event"`
	} `json:"events,omitempty"`
}

// EventsError A general error response indicating that the request could not be fulfilled due to a technical issue.
type EventsError struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// EventsEventType Server event type
type EventsEventType string

// EventsUuid Universally unique identifier
type EventsUuid = openapi_types.UUID

// KubernetesName Name
type KubernetesName = string

// KubernetesNodeName Node name
type KubernetesNodeName = string

// KubernetesUuid UUID
type KubernetesUuid = openapi_types.UUID

// KubernetesNameParameter Name
type KubernetesNameParameter = KubernetesName

// KubernetesNodeNameParameter Node name
type KubernetesNodeNameParameter = KubernetesNodeName

// KubernetesUuidParameter UUID
type KubernetesUuidParameter = KubernetesUuid

// ListEventsCount defines model for listEventsCount.
type ListEventsCount = int

// ListEventsOffset defines model for listEventsOffset.
type ListEventsOffset = int

// ListEventsServerUuid defines model for listEventsServerUuid.
type ListEventsServerUuid = openapi_types.UUID

// ListEvents200 Server event type
type ListEvents200 = Events

// ListEventsDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ListEventsDefault = EventsError
