// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for IpAddressBooleanYesno.
const (
	IpAddressBooleanYesnoNo  IpAddressBooleanYesno = "no"
	IpAddressBooleanYesnoYes IpAddressBooleanYesno = "yes"
)

// Valid indicates whether the value is a known member of the IpAddressBooleanYesno enum.
func (e IpAddressBooleanYesno) Valid() bool {
	switch e {
	case IpAddressBooleanYesnoNo:
		return true
	case IpAddressBooleanYesnoYes:
		return true
	default:
		return false
	}
}

// Defines values for IpAddressIpFamily.
const (
	IpAddressIpFamilyIPv4 IpAddressIpFamily = "IPv4"
	IpAddressIpFamilyIPv6 IpAddressIpFamily = "IPv6"
)

// Valid indicates whether the value is a known member of the IpAddressIpFamily enum.
func (e IpAddressIpFamily) Valid() bool {
	switch e {
	case IpAddressIpFamilyIPv4:
		return true
	case IpAddressIpFamilyIPv6:
		return true
	default:
		return false
	}
}

// Defines values for IpAddressIpReleasePolicy.
const (
	IpAddressIpReleasePolicyKeep    IpAddressIpReleasePolicy = "keep"
	IpAddressIpReleasePolicyRelease IpAddressIpReleasePolicy = "release"
)

// Valid indicates whether the value is a known member of the IpAddressIpReleasePolicy enum.
func (e IpAddressIpReleasePolicy) Valid() bool {
	switch e {
	case IpAddressIpReleasePolicyKeep:
		return true
	case IpAddressIpReleasePolicyRelease:
		return true
	default:
		return false
	}
}

// Defines values for IpAddressNetworkType.
const (
	IpAddressNetworkTypePrivate IpAddressNetworkType = "private"
	IpAddressNetworkTypePublic  IpAddressNetworkType = "public"
	IpAddressNetworkTypeUtility IpAddressNetworkType = "utility"
)

// Valid indicates whether the value is a known member of the IpAddressNetworkType enum.
func (e IpAddressNetworkType) Valid() bool {
	switch e {
	case IpAddressNetworkTypePrivate:
		return true
	case IpAddressNetworkTypePublic:
		return true
	case IpAddressNetworkTypeUtility:
		return true
	default:
		return false
	}
}

// AddIpAddressRequest Schema for adding an IP address to a server
type AddIpAddressRequest struct {
	IpAddress struct {
		Access string `json:"access"`

		// Family IP address family
		Family IpAddressIpFamily `json:"family"`

		// Floating Boolean value represented as yes/no
		Floating *IpAddressBooleanYesno `json:"floating,omitempty"`

		// Mac MAC address
		Mac    *IpAddressMacAddress `json:"mac,omitempty"`
		Prefix *string              `json:"prefix,omitempty"`

		// ReleasePolicy Action taken when the resource using the address is deleted: release deletes the address, while keep preserves it as a detached floating IP address
		ReleasePolicy *IpAddressIpReleasePolicy `json:"release_policy,omitempty"`

		// Server Universally unique identifier
		Server *IpAddressUuid `json:"server,omitempty"`
		VlanId *string        `json:"vlan_id,omitempty"`

		// Zone Zone identifier
		//
		// Examples: fi-hel1, de-fra1, us-nyc1
		Zone *IpAddressZone `json:"zone,omitempty"`
	} `json:"ip_address"`
}

// BulkPatchIpAddressesRequestV13 Request schema for bulk patching IP addresses
type BulkPatchIpAddressesRequestV13 struct {
	IpAddresses []struct {
		// Address IP address
		Address IpAddress `json:"address"`

		// DelegatedToAccountId Unique numeric identifier of an account.
		DelegatedToAccountId IpAddressAccountId `json:"delegated_to_account_id"`

		// MainAccountId Unique numeric identifier of an account.
		MainAccountId IpAddressAccountId `json:"main_account_id"`

		// ReleasePolicy Action taken when the resource using the address is deleted: release deletes the address, while keep preserves it as a detached floating IP address
		ReleasePolicy IpAddressIpReleasePolicy `json:"release_policy"`
	} `json:"ip_addresses"`
}

// IpAddress IP address
type IpAddress struct {
	union json.RawMessage
}

// IpAddress0 IPv4 address
type IpAddress0 = string

// IpAddress1 IPv6 address
type IpAddress1 = string

// IpAddressAccountId Unique numeric identifier of an account.
type IpAddressAccountId = int64

// IpAddressBooleanYesno Boolean value represented as yes/no
type IpAddressBooleanYesno string

// IpAddressDelegatedToAccountId Attached to a resource that is delegated to another account. Null means not delegated.
type IpAddressDelegatedToAccountId = int64

// IpAddressDetails Details of an IP address
type IpAddressDetails struct {
	// Access Network access type
	Access IpAddressNetworkType `json:"access"`

	// AccountId Unique numeric identifier of an account.
	AccountId *IpAddressAccountId `json:"account_id,omitempty"`

	// Address IP address
	Address IpAddress `json:"address"`

	// DelegatedToAccountId Attached to a resource that is delegated to another account. Null means not delegated.
	DelegatedToAccountId *IpAddressDelegatedToAccountId `json:"delegated_to_account_id,omitempty"`

	// Family IP address family
	Family *IpAddressIpFamily `json:"family,omitempty"`

	// Floating Boolean value represented as yes/no
	Floating *IpAddressBooleanYesno `json:"floating,omitempty"`

	// Mac MAC address
	Mac *IpAddressMacAddress `json:"mac,omitempty"`

	// PartOfPlan Boolean value represented as yes/no
	PartOfPlan *IpAddressBooleanYesno `json:"part_of_plan,omitempty"`
	PtrRecord  *string                `json:"ptr_record,omitempty"`

	// ReleasePolicy Action taken when the resource using the address is deleted: release deletes the address, while keep preserves it as a detached floating IP address
	ReleasePolicy *IpAddressIpReleasePolicy `json:"release_policy,omitempty"`

	// Server Universally unique identifier
	Server *IpAddressUuid `json:"server,omitempty"`

	// Zone Zone identifier
	//
	// Examples: fi-hel1, de-fra1, us-nyc1
	Zone *IpAddressZone `json:"zone,omitempty"`
}

// IpAddressError A general error response indicating that the request could not be fulfilled due to a technical issue.
type IpAddressError struct {
	Error struct {
		// ErrorCode Examples: GENERAL_FAILURE
		ErrorCode string `json:"error_code"`

		// ErrorMessage Examples: Your request could not be fulfilled due to a technical issue.
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// IpAddressIpFamily IP address family
type IpAddressIpFamily string

// IpAddressIpReleasePolicy Action taken when the resource using the address is deleted: release deletes the address, while keep preserves it as a detached floating IP address
type IpAddressIpReleasePolicy string

// IpAddressMacAddress MAC address
type IpAddressMacAddress = string

// IpAddressNetworkType Network access type
type IpAddressNetworkType string

// IpAddressPtrRecord defines model for ipAddressPtrRecord.
type IpAddressPtrRecord = string

// IpAddressRequest Request schema for IP address operations
type IpAddressRequest struct {
	// IpAddresses List of IP addresses to operate on
	IpAddresses []IpAddressDetails `json:"ip_addresses"`
}

// IpAddressResponse Request schema for IP address operations
type IpAddressResponse struct {
	// IpAddress Details of an IP address
	IpAddress IpAddressDetails `json:"ip_address"`
}

// IpAddressUuid Universally unique identifier
type IpAddressUuid = openapi_types.UUID

// IpAddressZone Zone identifier
//
// Examples: fi-hel1, de-fra1, us-nyc1
type IpAddressZone = string

// IpAddressesResponse Request schema for IP address operations
type IpAddressesResponse struct {
	IpAddresses struct {
		// IpAddress List of IP addresses
		IpAddress []IpAddressDetails `json:"ip_address"`
	} `json:"ip_addresses"`
}

// ModifyIpAddressRequestV10 Request schema for modifying an IP address
type ModifyIpAddressRequestV10 struct {
	IpAddress struct {
		// Floating Boolean value represented as yes/no
		Floating  *IpAddressBooleanYesno `json:"floating,omitempty"`
		PtrRecord string                 `json:"ptr_record"`
		VlanId    *string                `json:"vlan_id,omitempty"`
	} `json:"ip_address"`
}

// PatchIpAddressRequestV13 Request schema for modifying an IP address
type PatchIpAddressRequestV13 struct {
	IpAddress struct {
		// Mac MAC address
		Mac       *IpAddressMacAddress `json:"mac,omitempty"`
		PtrRecord *IpAddressPtrRecord  `json:"ptr_record,omitempty"`

		// ReleasePolicy Action taken when the resource using the address is deleted: release deletes the address, while keep preserves it as a detached floating IP address
		ReleasePolicy *IpAddressIpReleasePolicy `json:"release_policy,omitempty"`
	} `json:"ip_address"`
}

// DeleteIPAddressAddress IP address
type DeleteIPAddressAddress = IpAddress

// GetIPAddressDetailsAddress defines model for getIPAddressDetailsAddress.
type GetIPAddressDetailsAddress = string

// ModifyIPAddressAddress IP address
type ModifyIPAddressAddress = IpAddress

// PatchModifyIPAddressAddress defines model for patchModifyIPAddressAddress.
type PatchModifyIPAddressAddress = string

// AddIPAddress201 Request schema for IP address operations
type AddIPAddress201 = IpAddressRequest

// AddIPAddressDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type AddIPAddressDefault = IpAddressError

// BulkModifyIPAddressesDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type BulkModifyIPAddressesDefault = IpAddressError

// DeleteIPAddressDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteIPAddressDefault = IpAddressError

// GetIPAddressDetails200 Request schema for IP address operations
type GetIPAddressDetails200 = IpAddressResponse

// GetIPAddressDetailsDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetIPAddressDetailsDefault = IpAddressError

// ListIPAddresses200 Request schema for IP address operations
type ListIPAddresses200 = IpAddressesResponse

// ListIPAddressesDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ListIPAddressesDefault = IpAddressError

// ModifyIPAddress202 Request schema for IP address operations
type ModifyIPAddress202 = IpAddressRequest

// ModifyIPAddressDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyIPAddressDefault = IpAddressError

// PatchModifyIPAddress202 Request schema for IP address operations
type PatchModifyIPAddress202 = IpAddressRequest

// PatchModifyIPAddressDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type PatchModifyIPAddressDefault = IpAddressError

// AddIPAddress Schema for adding an IP address to a server
type AddIPAddress = AddIpAddressRequest

// BulkModifyIPAddresses Request schema for bulk patching IP addresses
type BulkModifyIPAddresses = BulkPatchIpAddressesRequestV13

// ModifyIPAddress Request schema for modifying an IP address
type ModifyIPAddress = ModifyIpAddressRequestV10

// PatchModifyIPAddress Request schema for modifying an IP address
type PatchModifyIPAddress = PatchIpAddressRequestV13

// AddIPAddressJSONRequestBody defines body for AddIPAddress for application/json ContentType.
type AddIPAddressJSONRequestBody = AddIpAddressRequest

// BulkModifyIPAddressesJSONRequestBody defines body for BulkModifyIPAddresses for application/json ContentType.
type BulkModifyIPAddressesJSONRequestBody = BulkPatchIpAddressesRequestV13

// PatchModifyIPAddressJSONRequestBody defines body for PatchModifyIPAddress for application/json ContentType.
type PatchModifyIPAddressJSONRequestBody = PatchIpAddressRequestV13

// ModifyIPAddressJSONRequestBody defines body for ModifyIPAddress for application/json ContentType.
type ModifyIPAddressJSONRequestBody = ModifyIpAddressRequestV10

// AsIpAddress0 returns the union data inside the IpAddress as a IpAddress0
func (t IpAddress) AsIpAddress0() (IpAddress0, error) {
	var body IpAddress0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIpAddress0 overwrites any union data inside the IpAddress as the provided IpAddress0
func (t *IpAddress) FromIpAddress0(v IpAddress0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIpAddress0 performs a merge with any union data inside the IpAddress, using the provided IpAddress0
func (t *IpAddress) MergeIpAddress0(v IpAddress0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIpAddress1 returns the union data inside the IpAddress as a IpAddress1
func (t IpAddress) AsIpAddress1() (IpAddress1, error) {
	var body IpAddress1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIpAddress1 overwrites any union data inside the IpAddress as the provided IpAddress1
func (t *IpAddress) FromIpAddress1(v IpAddress1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIpAddress1 performs a merge with any union data inside the IpAddress, using the provided IpAddress1
func (t *IpAddress) MergeIpAddress1(v IpAddress1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t IpAddress) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *IpAddress) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
