// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for KubernetesAuthenticationIssuerConfigAudienceMatchPolicy.
const (
	KubernetesAuthenticationIssuerConfigAudienceMatchPolicyEmpty    KubernetesAuthenticationIssuerConfigAudienceMatchPolicy = ""
	KubernetesAuthenticationIssuerConfigAudienceMatchPolicyMatchAny KubernetesAuthenticationIssuerConfigAudienceMatchPolicy = "MatchAny"
)

// Valid indicates whether the value is a known member of the KubernetesAuthenticationIssuerConfigAudienceMatchPolicy enum.
func (e KubernetesAuthenticationIssuerConfigAudienceMatchPolicy) Valid() bool {
	switch e {
	case KubernetesAuthenticationIssuerConfigAudienceMatchPolicyEmpty:
		return true
	case KubernetesAuthenticationIssuerConfigAudienceMatchPolicyMatchAny:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesClusterPlan.
const (
	KubernetesClusterPlanDevMd           KubernetesClusterPlan = "dev-md"
	KubernetesClusterPlanDevelopment     KubernetesClusterPlan = "development"
	KubernetesClusterPlanProdMd          KubernetesClusterPlan = "prod-md"
	KubernetesClusterPlanProdMdHa        KubernetesClusterPlan = "prod-md-ha"
	KubernetesClusterPlanProductionSmall KubernetesClusterPlan = "production-small"
)

// Valid indicates whether the value is a known member of the KubernetesClusterPlan enum.
func (e KubernetesClusterPlan) Valid() bool {
	switch e {
	case KubernetesClusterPlanDevMd:
		return true
	case KubernetesClusterPlanDevelopment:
		return true
	case KubernetesClusterPlanProdMd:
		return true
	case KubernetesClusterPlanProdMdHa:
		return true
	case KubernetesClusterPlanProductionSmall:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesClusterState.
const (
	KubernetesClusterStateFailed         KubernetesClusterState = "failed"
	KubernetesClusterStatePending        KubernetesClusterState = "pending"
	KubernetesClusterStateRunning        KubernetesClusterState = "running"
	KubernetesClusterStateSuspended      KubernetesClusterState = "suspended"
	KubernetesClusterStateTerminated     KubernetesClusterState = "terminated"
	KubernetesClusterStateTerminating    KubernetesClusterState = "terminating"
	KubernetesClusterStateUnknown        KubernetesClusterState = "unknown"
	KubernetesClusterStateUpgradeFailed  KubernetesClusterState = "upgrade-failed"
	KubernetesClusterStateUpgradePending KubernetesClusterState = "upgrade-pending"
	KubernetesClusterStateUpgrading      KubernetesClusterState = "upgrading"
)

// Valid indicates whether the value is a known member of the KubernetesClusterState enum.
func (e KubernetesClusterState) Valid() bool {
	switch e {
	case KubernetesClusterStateFailed:
		return true
	case KubernetesClusterStatePending:
		return true
	case KubernetesClusterStateRunning:
		return true
	case KubernetesClusterStateSuspended:
		return true
	case KubernetesClusterStateTerminated:
		return true
	case KubernetesClusterStateTerminating:
		return true
	case KubernetesClusterStateUnknown:
		return true
	case KubernetesClusterStateUpgradeFailed:
		return true
	case KubernetesClusterStateUpgradePending:
		return true
	case KubernetesClusterStateUpgrading:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesClusterUpgradeStrategyType.
const (
	KubernetesClusterUpgradeStrategyTypeManual        KubernetesClusterUpgradeStrategyType = "manual"
	KubernetesClusterUpgradeStrategyTypeRollingUpdate KubernetesClusterUpgradeStrategyType = "rolling-update"
)

// Valid indicates whether the value is a known member of the KubernetesClusterUpgradeStrategyType enum.
func (e KubernetesClusterUpgradeStrategyType) Valid() bool {
	switch e {
	case KubernetesClusterUpgradeStrategyTypeManual:
		return true
	case KubernetesClusterUpgradeStrategyTypeRollingUpdate:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesDefaultStorageEncryption.
const (
	KubernetesDefaultStorageEncryptionDataAtRest KubernetesDefaultStorageEncryption = "data-at-rest"
	KubernetesDefaultStorageEncryptionNone       KubernetesDefaultStorageEncryption = "none"
)

// Valid indicates whether the value is a known member of the KubernetesDefaultStorageEncryption enum.
func (e KubernetesDefaultStorageEncryption) Valid() bool {
	switch e {
	case KubernetesDefaultStorageEncryptionDataAtRest:
		return true
	case KubernetesDefaultStorageEncryptionNone:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesEffect.
const (
	KubernetesEffectNoExecute        KubernetesEffect = "NoExecute"
	KubernetesEffectNoSchedule       KubernetesEffect = "NoSchedule"
	KubernetesEffectPreferNoSchedule KubernetesEffect = "PreferNoSchedule"
)

// Valid indicates whether the value is a known member of the KubernetesEffect enum.
func (e KubernetesEffect) Valid() bool {
	switch e {
	case KubernetesEffectNoExecute:
		return true
	case KubernetesEffectNoSchedule:
		return true
	case KubernetesEffectPreferNoSchedule:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesNodeGroupState.
const (
	KubernetesNodeGroupStateFailed      KubernetesNodeGroupState = "failed"
	KubernetesNodeGroupStatePending     KubernetesNodeGroupState = "pending"
	KubernetesNodeGroupStateRunning     KubernetesNodeGroupState = "running"
	KubernetesNodeGroupStateScalingDown KubernetesNodeGroupState = "scaling-down"
	KubernetesNodeGroupStateScalingUp   KubernetesNodeGroupState = "scaling-up"
	KubernetesNodeGroupStateTerminating KubernetesNodeGroupState = "terminating"
	KubernetesNodeGroupStateUnknown     KubernetesNodeGroupState = "unknown"
)

// Valid indicates whether the value is a known member of the KubernetesNodeGroupState enum.
func (e KubernetesNodeGroupState) Valid() bool {
	switch e {
	case KubernetesNodeGroupStateFailed:
		return true
	case KubernetesNodeGroupStatePending:
		return true
	case KubernetesNodeGroupStateRunning:
		return true
	case KubernetesNodeGroupStateScalingDown:
		return true
	case KubernetesNodeGroupStateScalingUp:
		return true
	case KubernetesNodeGroupStateTerminating:
		return true
	case KubernetesNodeGroupStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesNodeState.
const (
	KubernetesNodeStateFailed      KubernetesNodeState = "failed"
	KubernetesNodeStatePending     KubernetesNodeState = "pending"
	KubernetesNodeStateRunning     KubernetesNodeState = "running"
	KubernetesNodeStateTerminating KubernetesNodeState = "terminating"
	KubernetesNodeStateUnknown     KubernetesNodeState = "unknown"
)

// Valid indicates whether the value is a known member of the KubernetesNodeState enum.
func (e KubernetesNodeState) Valid() bool {
	switch e {
	case KubernetesNodeStateFailed:
		return true
	case KubernetesNodeStatePending:
		return true
	case KubernetesNodeStateRunning:
		return true
	case KubernetesNodeStateTerminating:
		return true
	case KubernetesNodeStateUnknown:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesNodeUpdatesScheduleDow.
const (
	KubernetesNodeUpdatesScheduleDowDaily     KubernetesNodeUpdatesScheduleDow = "daily"
	KubernetesNodeUpdatesScheduleDowFriday    KubernetesNodeUpdatesScheduleDow = "Friday"
	KubernetesNodeUpdatesScheduleDowMonday    KubernetesNodeUpdatesScheduleDow = "Monday"
	KubernetesNodeUpdatesScheduleDowSaturday  KubernetesNodeUpdatesScheduleDow = "Saturday"
	KubernetesNodeUpdatesScheduleDowSunday    KubernetesNodeUpdatesScheduleDow = "Sunday"
	KubernetesNodeUpdatesScheduleDowThursday  KubernetesNodeUpdatesScheduleDow = "Thursday"
	KubernetesNodeUpdatesScheduleDowTuesday   KubernetesNodeUpdatesScheduleDow = "Tuesday"
	KubernetesNodeUpdatesScheduleDowWednesday KubernetesNodeUpdatesScheduleDow = "Wednesday"
)

// Valid indicates whether the value is a known member of the KubernetesNodeUpdatesScheduleDow enum.
func (e KubernetesNodeUpdatesScheduleDow) Valid() bool {
	switch e {
	case KubernetesNodeUpdatesScheduleDowDaily:
		return true
	case KubernetesNodeUpdatesScheduleDowFriday:
		return true
	case KubernetesNodeUpdatesScheduleDowMonday:
		return true
	case KubernetesNodeUpdatesScheduleDowSaturday:
		return true
	case KubernetesNodeUpdatesScheduleDowSunday:
		return true
	case KubernetesNodeUpdatesScheduleDowThursday:
		return true
	case KubernetesNodeUpdatesScheduleDowTuesday:
		return true
	case KubernetesNodeUpdatesScheduleDowWednesday:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesStorageEncryption.
const (
	KubernetesStorageEncryptionDataAtRest KubernetesStorageEncryption = "data-at-rest"
	KubernetesStorageEncryptionNone       KubernetesStorageEncryption = "none"
)

// Valid indicates whether the value is a known member of the KubernetesStorageEncryption enum.
func (e KubernetesStorageEncryption) Valid() bool {
	switch e {
	case KubernetesStorageEncryptionDataAtRest:
		return true
	case KubernetesStorageEncryptionNone:
		return true
	default:
		return false
	}
}

// Defines values for KubernetesStorageTier.
const (
	KubernetesStorageTierHdd      KubernetesStorageTier = "hdd"
	KubernetesStorageTierMaxiops  KubernetesStorageTier = "maxiops"
	KubernetesStorageTierStandard KubernetesStorageTier = "standard"
)

// Valid indicates whether the value is a known member of the KubernetesStorageTier enum.
func (e KubernetesStorageTier) Valid() bool {
	switch e {
	case KubernetesStorageTierHdd:
		return true
	case KubernetesStorageTierMaxiops:
		return true
	case KubernetesStorageTierStandard:
		return true
	default:
		return false
	}
}

// KubernetesAccepted Message
type KubernetesAccepted struct {
	// Message Message text content
	Message *KubernetesMessage `json:"message,omitempty"`
}

// KubernetesAntiAffinity Enable anti-affinity policies
type KubernetesAntiAffinity = bool

// KubernetesAuthenticationConfiguration List of OIDC issuers and their claim validation rules.
type KubernetesAuthenticationConfiguration = []KubernetesAuthenticationIssuerConfig

// KubernetesAuthenticationConfigurationYAML kube-apiserver v1 AuthenticationConfiguration YAML document
type KubernetesAuthenticationConfigurationYAML = string

// KubernetesAuthenticationIssuerConfig defines model for kubernetesAuthenticationIssuerConfig.
type KubernetesAuthenticationIssuerConfig struct {
	AudienceMatchPolicy *KubernetesAuthenticationIssuerConfigAudienceMatchPolicy `json:"audience_match_policy,omitempty"`

	// Audiences Accepted audiences for tokens from this issuer. The first audience is used as the OIDC client id in generated kubeconfigs by default; the OIDC kubeconfig endpoint's `audience` query parameter can select a different one.
	Audiences []string `json:"audiences"`

	// CertificateAuthority Base64-encoded PEM certificate authority bundle.
	CertificateAuthority *string `json:"certificate_authority,omitempty"`

	// ClaimMappings Rules for mapping token claims to Kubernetes user attributes.
	ClaimMappings        *KubernetesClaimMappings         `json:"claim_mappings,omitempty"`
	ClaimValidationRules *[]KubernetesClaimValidationRule `json:"claim_validation_rules,omitempty"`
	DiscoveryUrl         *string                          `json:"discovery_url,omitempty"`
	IssuerUrl            string                           `json:"issuer_url"`

	// Name Name
	Name                KubernetesName                  `json:"name"`
	UserValidationRules *[]KubernetesUserValidationRule `json:"user_validation_rules,omitempty"`
}

// KubernetesAuthenticationIssuerConfigAudienceMatchPolicy defines model for KubernetesAuthenticationIssuerConfig.AudienceMatchPolicy.
type KubernetesAuthenticationIssuerConfigAudienceMatchPolicy string

// KubernetesClaimMappings Rules for mapping token claims to Kubernetes user attributes.
type KubernetesClaimMappings struct {
	Extra *[]KubernetesExtraMapping `json:"extra,omitempty"`

	// Groups Maps a user attribute from either a JWT claim (optionally prefixed) or a CEL expression. Claim and expression are mutually exclusive.
	Groups *KubernetesPrefixedClaimOrExpression `json:"groups,omitempty"`

	// Uid Maps a user attribute from either a JWT claim or a CEL expression. Claim and expression are mutually exclusive.
	Uid *KubernetesClaimOrExpression `json:"uid,omitempty"`

	// Username Maps a user attribute from either a JWT claim (optionally prefixed) or a CEL expression. Claim and expression are mutually exclusive.
	Username *KubernetesPrefixedClaimOrExpression `json:"username,omitempty"`
}

// KubernetesClaimOrExpression Maps a user attribute from either a JWT claim or a CEL expression. Claim and expression are mutually exclusive.
type KubernetesClaimOrExpression struct {
	// Claim JWT claim to use. Mutually exclusive with expression.
	Claim *string `json:"claim,omitempty"`

	// Expression CEL expression producing the attribute value. Mutually exclusive with claim.
	Expression *string `json:"expression,omitempty"`
}

// KubernetesClaimValidationRule CEL expression used to validate a token claim.
type KubernetesClaimValidationRule struct {
	Claim         *string `json:"claim,omitempty"`
	Expression    *string `json:"expression,omitempty"`
	Message       *string `json:"message,omitempty"`
	RequiredValue *string `json:"required_value,omitempty"`
}

// KubernetesCluster Kubernetes cluster
type KubernetesCluster struct {
	// Authentication List of OIDC issuers and their claim validation rules.
	Authentication *KubernetesAuthenticationConfiguration `json:"authentication,omitempty"`

	// ControlPlaneIpFilter List of IP blocks
	ControlPlaneIpFilter *KubernetesIPBlocks `json:"control_plane_ip_filter,omitempty"`
	Labels               interface{}         `json:"labels"`

	// Name Name
	Name KubernetesName `json:"name"`

	// Network Network UUID
	Network KubernetesNetwork `json:"network"`

	// NetworkCidr CIDR of the given network
	NetworkCidr *KubernetesNetworkCIDR `json:"network_cidr,omitempty"`

	// NodeGroups List of node groups
	NodeGroups *KubernetesNodeGroups `json:"node_groups,omitempty"`

	// Plan Cluster plan
	Plan *KubernetesClusterPlan `json:"plan,omitempty"`

	// PrivateNodeGroups Enable private node groups
	PrivateNodeGroups *KubernetesPrivateNodeGroups `json:"private_node_groups,omitempty"`

	// State Cluster operational state
	State             *KubernetesClusterState             `json:"state,omitempty"`
	StorageEncryption *KubernetesDefaultStorageEncryption `json:"storage_encryption,omitempty"`

	// Uuid UUID
	Uuid *KubernetesUuid `json:"uuid,omitempty"`

	// Version Kubernetes version identifier
	Version KubernetesClusterVersion `json:"version"`

	// Zone UpCloud zone to provision the Kubernetes cluster in
	Zone KubernetesZone `json:"zone"`
}

// KubernetesClusterAvailableUpgrades defines model for kubernetesClusterAvailableUpgrades.
type KubernetesClusterAvailableUpgrades struct {
	Versions []KubernetesClusterVersion `json:"versions"`
}

// KubernetesClusterAvailableUpgradesPost defines model for kubernetesClusterAvailableUpgradesPost.
type KubernetesClusterAvailableUpgradesPost struct {
	// Strategy upgrade strategy for node group upgrades
	Strategy *KubernetesClusterUpgradeStrategy `json:"strategy,omitempty"`

	// Version Kubernetes version identifier
	Version KubernetesClusterVersion `json:"version"`
}

// KubernetesClusterKubeconfig Kubernetes cluster kubeconfig
type KubernetesClusterKubeconfig struct {
	// Kubeconfig Kubeconfig
	Kubeconfig KubernetesKubeconfig `json:"kubeconfig"`
}

// KubernetesClusterPatch defines model for kubernetesClusterPatch.
type KubernetesClusterPatch struct {
	// ControlPlaneIpFilter List of IP blocks
	ControlPlaneIpFilter *KubernetesIPBlocks `json:"control_plane_ip_filter,omitempty"`
	Labels               interface{}         `json:"labels"`

	// Plan Cluster plan
	Plan *KubernetesClusterPlan `json:"plan,omitempty"`
}

// KubernetesClusterPlan Cluster plan
type KubernetesClusterPlan string

// KubernetesClusterState Cluster operational state
type KubernetesClusterState string

// KubernetesClusterUpgradeStrategy upgrade strategy for node group upgrades
type KubernetesClusterUpgradeStrategy struct {
	// Type upgrade strategy type
	Type KubernetesClusterUpgradeStrategyType `json:"type"`
}

// KubernetesClusterUpgradeStrategyType upgrade strategy type
type KubernetesClusterUpgradeStrategyType string

// KubernetesClusterVersion Kubernetes version identifier
type KubernetesClusterVersion = string

// KubernetesClusters List of Kubernetes clusters
type KubernetesClusters = []KubernetesCluster

// KubernetesCount Amount of nodes in a node group
type KubernetesCount = int32

// KubernetesDefaultStorageEncryption defines model for kubernetesDefaultStorageEncryption.
type KubernetesDefaultStorageEncryption string

// KubernetesDescription Plan description
type KubernetesDescription = string

// KubernetesEffect Taint effect
type KubernetesEffect string

// KubernetesError Response error
type KubernetesError struct {
	// CorrelationId unique string that identifies the request that caused the error
	CorrelationId KubernetesErrorCorrelationID `json:"correlation_id"`

	// InvalidParams list of parameters describing a specific part(s) of the request that caused the error
	InvalidParams *KubernetesErrorInvalidParams `json:"invalid_params,omitempty"`

	// Status HTTP Status code
	Status KubernetesErrorStatus `json:"status"`

	// Title human-readable description of the error
	Title KubernetesErrorTitle `json:"title"`

	// Type URI to a page describing the problem
	Type KubernetesErrorType `json:"type"`
}

// KubernetesErrorCorrelationID unique string that identifies the request that caused the error
type KubernetesErrorCorrelationID = string

// KubernetesErrorInvalidParams list of parameters describing a specific part(s) of the request that caused the error
type KubernetesErrorInvalidParams = string

// KubernetesErrorStatus HTTP Status code
type KubernetesErrorStatus = int32

// KubernetesErrorTitle human-readable description of the error
type KubernetesErrorTitle = string

// KubernetesErrorType URI to a page describing the problem
type KubernetesErrorType = string

// KubernetesExtraMapping Maps a token claim to an extra user attribute using a CEL expression.
type KubernetesExtraMapping struct {
	// Key Domain-prefixed, lowercase key for the extra attribute, e.g. example.org/foo.
	Key string `json:"key"`

	// ValueExpression CEL expression producing the extra attribute value (string or string array).
	ValueExpression string `json:"value_expression"`
}

// KubernetesIPBlock IP prefix of a single IPv4 address or a network CIDR
type KubernetesIPBlock = string

// KubernetesIPBlocks List of IP blocks
type KubernetesIPBlocks = []KubernetesIPBlock

// KubernetesKey Key of a key-value pair
type KubernetesKey = string

// KubernetesKubeconfig Kubeconfig
type KubernetesKubeconfig = string

// KubernetesKubeletArg Kubelet argument presented as key-value pair
type KubernetesKubeletArg struct {
	// Key Key of a key-value pair
	Key KubernetesKey `json:"key"`

	// Value Value of a key-value pair
	Value KubernetesValue `json:"value"`
}

// KubernetesKubeletArgs List of Kubelet arguments
type KubernetesKubeletArgs = []KubernetesKubeletArg

// KubernetesLabel Label for identifying node groups, presented as key-value pair
type KubernetesLabel struct {
	// Key Key of a key-value pair
	Key KubernetesKey `json:"key"`

	// Value Value of a key-value pair
	Value *KubernetesValue `json:"value,omitempty"`
}

// KubernetesLabels List of labels
type KubernetesLabels = []KubernetesLabel

// KubernetesMessage Message text content
type KubernetesMessage = string

// KubernetesName Name
type KubernetesName = string

// KubernetesNetwork Network UUID
type KubernetesNetwork = string

// KubernetesNetworkCIDR CIDR of the given network
type KubernetesNetworkCIDR = string

// KubernetesNode Kubernetes cluster node
type KubernetesNode struct {
	// KubeletVersion Kubernetes version identifier
	KubeletVersion KubernetesClusterVersion `json:"kubelet_version"`

	// Name Name
	Name KubernetesName `json:"name"`

	// State Node operational state
	State KubernetesNodeState `json:"state"`

	// Uuid Node UUID
	Uuid openapi_types.UUID `json:"uuid"`
}

// KubernetesNodeGroup Node group for a Kubernetes cluster
type KubernetesNodeGroup struct {
	// AntiAffinity Enable anti-affinity policies
	AntiAffinity *KubernetesAntiAffinity `json:"anti_affinity,omitempty"`

	// CloudNativePlan Node group cloud native plan properties
	CloudNativePlan *KubernetesNodeGroupCloudNativePlan `json:"cloud_native_plan,omitempty"`

	// Count Amount of nodes in a node group
	Count KubernetesCount `json:"count"`

	// CustomPlan Node group custom plan properties
	CustomPlan *KubernetesNodeGroupCustomPlan `json:"custom_plan,omitempty"`

	// GpuPlan Node group GPU plan properties
	GpuPlan *KubernetesNodeGroupGPUPlan `json:"gpu_plan,omitempty"`

	// KubeletArgs List of Kubelet arguments
	KubeletArgs *KubernetesKubeletArgs `json:"kubelet_args,omitempty"`

	// Labels List of labels
	Labels *KubernetesLabels `json:"labels,omitempty"`

	// Name Name
	Name KubernetesName `json:"name"`

	// NodeUpdates Enable periodic package updates on node
	NodeUpdates *KubernetesNodeUpdates `json:"node_updates,omitempty"`

	// Plan Node group plan
	Plan KubernetesNodeGroupPlan `json:"plan"`

	// SshKeys List of public SSH keys
	SshKeys *KubernetesSshKeys `json:"ssh_keys,omitempty"`

	// State Node group operational state
	State *KubernetesNodeGroupState `json:"state,omitempty"`

	// Storage Storage UUID to use as a template
	Storage *KubernetesStorage `json:"storage,omitempty"`

	// StorageEncryption The storage encryption strategy.
	StorageEncryption *KubernetesStorageEncryption `json:"storage_encryption,omitempty"`

	// Taints List of taints
	Taints *KubernetesTaints `json:"taints,omitempty"`

	// UtilityNetworkAccess Enable utility network access
	UtilityNetworkAccess *KubernetesUtilityNetworkAccess `json:"utility_network_access,omitempty"`
}

// KubernetesNodeGroupCloudNativePlan Node group cloud native plan properties
type KubernetesNodeGroupCloudNativePlan struct {
	// StorageSize The size of the storage device in gigabytes.
	StorageSize KubernetesStorageSize `json:"storage_size"`

	// StorageTier The storage tier to use.
	StorageTier *KubernetesStorageTier `json:"storage_tier,omitempty"`
}

// KubernetesNodeGroupCustomPlan Node group custom plan properties
type KubernetesNodeGroupCustomPlan struct {
	// Cores The number of CPU cores dedicated to individual node group nodes when using custom plan
	Cores int32 `json:"cores"`

	// Memory The amount of memory in megabytes to assign to individual node group node when using custom plan
	Memory int32 `json:"memory"`

	// StorageSize The size of the storage device in gigabytes.
	StorageSize KubernetesStorageSize `json:"storage_size"`

	// StorageTier The storage tier to use.
	StorageTier *KubernetesStorageTier `json:"storage_tier,omitempty"`
}

// KubernetesNodeGroupDetails Kubernetes cluster node
type KubernetesNodeGroupDetails struct {
	// AntiAffinity Enable anti-affinity policies
	AntiAffinity *KubernetesAntiAffinity `json:"anti_affinity,omitempty"`

	// CloudNativePlan Node group cloud native plan properties
	CloudNativePlan *KubernetesNodeGroupCloudNativePlan `json:"cloud_native_plan,omitempty"`

	// Count Amount of nodes in a node group
	Count KubernetesCount `json:"count"`

	// CustomPlan Node group custom plan properties
	CustomPlan *KubernetesNodeGroupCustomPlan `json:"custom_plan,omitempty"`

	// GpuPlan Node group GPU plan properties
	GpuPlan *KubernetesNodeGroupGPUPlan `json:"gpu_plan,omitempty"`

	// KubeletArgs List of Kubelet arguments
	KubeletArgs *KubernetesKubeletArgs `json:"kubelet_args,omitempty"`

	// Labels List of labels
	Labels *KubernetesLabels `json:"labels,omitempty"`

	// Name Name
	Name KubernetesName `json:"name"`

	// NodeUpdates Enable periodic package updates on node
	NodeUpdates *KubernetesNodeUpdates `json:"node_updates,omitempty"`

	// Nodes List of node group nodes (experimental)
	Nodes []KubernetesNode `json:"nodes"`

	// Plan Node group plan
	Plan KubernetesNodeGroupPlan `json:"plan"`

	// SshKeys List of public SSH keys
	SshKeys *KubernetesSshKeys `json:"ssh_keys,omitempty"`

	// State Node group operational state
	State *KubernetesNodeGroupState `json:"state,omitempty"`

	// Storage Storage UUID to use as a template
	Storage *KubernetesStorage `json:"storage,omitempty"`

	// StorageEncryption The storage encryption strategy.
	StorageEncryption *KubernetesStorageEncryption `json:"storage_encryption,omitempty"`

	// Taints List of taints
	Taints *KubernetesTaints `json:"taints,omitempty"`

	// UtilityNetworkAccess Enable utility network access
	UtilityNetworkAccess *KubernetesUtilityNetworkAccess `json:"utility_network_access,omitempty"`
}

// KubernetesNodeGroupGPUPlan Node group GPU plan properties
type KubernetesNodeGroupGPUPlan struct {
	// StorageSize The size of the storage device in gigabytes.
	StorageSize KubernetesStorageSize `json:"storage_size"`

	// StorageTier The storage tier to use.
	StorageTier *KubernetesStorageTier `json:"storage_tier,omitempty"`
}

// KubernetesNodeGroupPatch defines model for kubernetesNodeGroupPatch.
type KubernetesNodeGroupPatch struct {
	// Count Amount of nodes in a node group
	Count KubernetesCount `json:"count"`
}

// KubernetesNodeGroupPlan Node group plan
type KubernetesNodeGroupPlan = string

// KubernetesNodeGroupState Node group operational state
type KubernetesNodeGroupState string

// KubernetesNodeGroups List of node groups
type KubernetesNodeGroups = []KubernetesNodeGroup

// KubernetesNodeName Node name
type KubernetesNodeName = string

// KubernetesNodeState Node operational state
type KubernetesNodeState string

// KubernetesNodeUpdates Enable periodic package updates on node
type KubernetesNodeUpdates struct {
	// KubernetesPatches Include Kubernetes package patch updates (kubeadm, kubectl, kubelet)
	KubernetesPatches bool `json:"kubernetes_patches"`

	// ScheduleDow The day of the week on which updates will be performed
	ScheduleDow KubernetesNodeUpdatesScheduleDow `json:"schedule_dow"`

	// ScheduleTime The time at which the updates will be applied in UTC (HH:MM).
	ScheduleTime string `json:"schedule_time"`
}

// KubernetesNodeUpdatesScheduleDow The day of the week on which updates will be performed
type KubernetesNodeUpdatesScheduleDow string

// KubernetesPlan Plan to assign to a node group
type KubernetesPlan struct {
	// Description Plan description
	Description KubernetesDescription `json:"description"`

	// Name Name
	Name KubernetesName `json:"name"`
}

// KubernetesPlans List of plans
type KubernetesPlans = []KubernetesPlan

// KubernetesPrefixedClaimOrExpression Maps a user attribute from either a JWT claim (optionally prefixed) or a CEL expression. Claim and expression are mutually exclusive.
type KubernetesPrefixedClaimOrExpression struct {
	// Claim JWT claim to use. Mutually exclusive with expression.
	Claim *string `json:"claim,omitempty"`

	// Expression CEL expression producing the attribute value. Mutually exclusive with claim and prefix.
	Expression *string `json:"expression,omitempty"`

	// Prefix Prefix prepended to the claim's value. Must be set (may be empty) when claim is set. Mutually exclusive with expression.
	Prefix *string `json:"prefix,omitempty"`
}

// KubernetesPrivateNodeGroups Enable private node groups
type KubernetesPrivateNodeGroups = bool

// KubernetesSshKey Public SSH key for accessing the nodes in a group
type KubernetesSshKey = string

// KubernetesSshKeys List of public SSH keys
type KubernetesSshKeys = []KubernetesSshKey

// KubernetesStorage Storage UUID to use as a template
type KubernetesStorage = openapi_types.UUID

// KubernetesStorageEncryption The storage encryption strategy.
type KubernetesStorageEncryption string

// KubernetesStorageSize The size of the storage device in gigabytes.
type KubernetesStorageSize = int32

// KubernetesStorageTier The storage tier to use.
type KubernetesStorageTier string

// KubernetesTaint Kubernetes taint to assign to nodes in a group
type KubernetesTaint struct {
	// Effect Taint effect
	Effect KubernetesEffect `json:"effect"`

	// Key Key of a key-value pair
	Key KubernetesKey `json:"key"`

	// Value Value of a key-value pair
	Value KubernetesValue `json:"value"`
}

// KubernetesTaints List of taints
type KubernetesTaints = []KubernetesTaint

// KubernetesUserValidationRule CEL expression applied to the final authenticated user.
type KubernetesUserValidationRule struct {
	Expression string  `json:"expression"`
	Message    *string `json:"message,omitempty"`
}

// KubernetesUtilityNetworkAccess Enable utility network access
type KubernetesUtilityNetworkAccess = bool

// KubernetesUuid UUID
type KubernetesUuid = openapi_types.UUID

// KubernetesValue Value of a key-value pair
type KubernetesValue = string

// KubernetesVersion Kubernetes version
type KubernetesVersion struct {
	// Id Kubernetes version identifier
	Id KubernetesClusterVersion `json:"id"`

	// Version Kubernetes semantic version
	Version string `json:"version"`
}

// KubernetesVersions List of Kubernetes versions
type KubernetesVersions = []KubernetesVersion

// KubernetesZone UpCloud zone to provision the Kubernetes cluster in
type KubernetesZone = string

// GetKubernetesClusterOIDCKubeconfigAudience defines model for getKubernetesClusterOIDCKubeconfigAudience.
type GetKubernetesClusterOIDCKubeconfigAudience = string

// KubernetesNameParameter Name
type KubernetesNameParameter = KubernetesName

// KubernetesNodeNameParameter Node name
type KubernetesNodeNameParameter = KubernetesNodeName

// KubernetesUuidParameter UUID
type KubernetesUuidParameter = KubernetesUuid

// KubernetesBadRequest Response error
type KubernetesBadRequest = KubernetesError

// KubernetesConflict Response error
type KubernetesConflict = KubernetesError

// KubernetesCreateClusterAuthentication201 defines model for kubernetesCreateClusterAuthentication201.
type KubernetesCreateClusterAuthentication201 = KubernetesAuthenticationIssuerConfig

// KubernetesDeleteCluster Message
type KubernetesDeleteCluster = KubernetesAccepted

// KubernetesDeleteNodeGroup Message
type KubernetesDeleteNodeGroup = KubernetesAccepted

// KubernetesDeleteNodeGroupNode Message
type KubernetesDeleteNodeGroupNode = KubernetesAccepted

// KubernetesGetAvailableUpgrades defines model for kubernetesGetAvailableUpgrades.
type KubernetesGetAvailableUpgrades = KubernetesClusterAvailableUpgrades

// KubernetesGetCluster Kubernetes cluster
type KubernetesGetCluster = KubernetesCluster

// KubernetesGetClusterAuthentication200 defines model for kubernetesGetClusterAuthentication200.
type KubernetesGetClusterAuthentication200 = KubernetesAuthenticationIssuerConfig

// KubernetesGetClusterKubeconfig Kubernetes cluster kubeconfig
type KubernetesGetClusterKubeconfig = KubernetesClusterKubeconfig

// KubernetesGetClusters List of Kubernetes clusters
type KubernetesGetClusters = KubernetesClusters

// KubernetesGetNodeGroupDetails Kubernetes cluster node
type KubernetesGetNodeGroupDetails = KubernetesNodeGroupDetails

// KubernetesGetNodeGroups List of node groups
type KubernetesGetNodeGroups = KubernetesNodeGroups

// KubernetesGetPlan List of plans
type KubernetesGetPlan = KubernetesPlans

// KubernetesGetVersion List of Kubernetes versions
type KubernetesGetVersion = KubernetesVersions

// KubernetesImportClusterAuthentication200 List of OIDC issuers and their claim validation rules.
type KubernetesImportClusterAuthentication200 = KubernetesAuthenticationConfiguration

// KubernetesInternalServerError Response error
type KubernetesInternalServerError = KubernetesError

// KubernetesListClusterAuthentication200 List of OIDC issuers and their claim validation rules.
type KubernetesListClusterAuthentication200 = KubernetesAuthenticationConfiguration

// KubernetesNotFound Response error
type KubernetesNotFound = KubernetesError

// KubernetesPatchClusterResponse Kubernetes cluster
type KubernetesPatchClusterResponse = KubernetesCluster

// KubernetesPatchNodeGroupResponse Node group for a Kubernetes cluster
type KubernetesPatchNodeGroupResponse = KubernetesNodeGroup

// KubernetesPostClusterResponse Kubernetes cluster
type KubernetesPostClusterResponse = KubernetesCluster

// KubernetesPostNodeGroupResponse Node group for a Kubernetes cluster
type KubernetesPostNodeGroupResponse = KubernetesNodeGroup

// KubernetesPostUpgradeResponse defines model for kubernetesPostUpgrade.
type KubernetesPostUpgradeResponse = KubernetesClusterAvailableUpgradesPost

// KubernetesSetClusterAuthentication200 List of OIDC issuers and their claim validation rules.
type KubernetesSetClusterAuthentication200 = KubernetesAuthenticationConfiguration

// KubernetesUnAuthorized Response error
type KubernetesUnAuthorized = KubernetesError

// KubernetesUnProcessableEntity Response error
type KubernetesUnProcessableEntity = KubernetesError

// KubernetesUpdateClusterAuthentication200 defines model for kubernetesUpdateClusterAuthentication200.
type KubernetesUpdateClusterAuthentication200 = KubernetesAuthenticationIssuerConfig

// KubernetesCreateClusterAuthentication defines model for kubernetesCreateClusterAuthentication.
type KubernetesCreateClusterAuthentication = KubernetesAuthenticationIssuerConfig

// KubernetesPatchClusterRequestBody defines model for kubernetesPatchCluster.
type KubernetesPatchClusterRequestBody = KubernetesClusterPatch

// KubernetesPatchNodeGroupRequestBody defines model for kubernetesPatchNodeGroup.
type KubernetesPatchNodeGroupRequestBody = KubernetesNodeGroupPatch

// KubernetesPostClusterRequestBody Kubernetes cluster
type KubernetesPostClusterRequestBody = KubernetesCluster

// KubernetesPostNodeGroupRequestBody Node group for a Kubernetes cluster
type KubernetesPostNodeGroupRequestBody = KubernetesNodeGroup

// KubernetesPostUpgradeRequestBody defines model for kubernetesPostUpgrade.
type KubernetesPostUpgradeRequestBody = KubernetesClusterAvailableUpgradesPost

// KubernetesSetClusterAuthentication List of OIDC issuers and their claim validation rules.
type KubernetesSetClusterAuthentication = KubernetesAuthenticationConfiguration

// KubernetesUpdateClusterAuthentication defines model for kubernetesUpdateClusterAuthentication.
type KubernetesUpdateClusterAuthentication = KubernetesAuthenticationIssuerConfig

// GetKubernetesClusterOIDCKubeconfigParams defines parameters for GetKubernetesClusterOIDCKubeconfig.
type GetKubernetesClusterOIDCKubeconfigParams struct {
	// Audience Which of the issuer's configured audiences to use as the OIDC client id in the generated kubeconfig. When omitted, the issuer's first audience is used. Must match one of the issuer's audiences.
	Audience *GetKubernetesClusterOIDCKubeconfigAudience `form:"audience,omitempty" json:"audience,omitempty"`
}

// CreateKubernetesClusterJSONRequestBody defines body for CreateKubernetesCluster for application/json ContentType.
type CreateKubernetesClusterJSONRequestBody = KubernetesCluster

// ModifyKubernetesClusterJSONRequestBody defines body for ModifyKubernetesCluster for application/json ContentType.
type ModifyKubernetesClusterJSONRequestBody = KubernetesClusterPatch

// CreateClusterAuthenticationJSONRequestBody defines body for CreateClusterAuthentication for application/json ContentType.
type CreateClusterAuthenticationJSONRequestBody = KubernetesAuthenticationIssuerConfig

// SetClusterAuthenticationJSONRequestBody defines body for SetClusterAuthentication for application/json ContentType.
type SetClusterAuthenticationJSONRequestBody = KubernetesAuthenticationConfiguration

// UpdateClusterAuthenticationJSONRequestBody defines body for UpdateClusterAuthentication for application/json ContentType.
type UpdateClusterAuthenticationJSONRequestBody = KubernetesAuthenticationIssuerConfig

// UpgradeKubernetesClusterJSONRequestBody defines body for UpgradeKubernetesCluster for application/json ContentType.
type UpgradeKubernetesClusterJSONRequestBody = KubernetesClusterAvailableUpgradesPost

// CreateKubernetesClusterNodeGroupJSONRequestBody defines body for CreateKubernetesClusterNodeGroup for application/json ContentType.
type CreateKubernetesClusterNodeGroupJSONRequestBody = KubernetesNodeGroup

// ModifyKubernetesClusterNodeGroupJSONRequestBody defines body for ModifyKubernetesClusterNodeGroup for application/json ContentType.
type ModifyKubernetesClusterNodeGroupJSONRequestBody = KubernetesNodeGroupPatch
