// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// The interface specification for the client above.
type NetworkPeeringClientInterface interface {
	// ListNetworkPeerings request
	ListNetworkPeerings(ctx context.Context, params *ListNetworkPeeringsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateNetworkPeeringWithBody request with any body
	CreateNetworkPeeringWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateNetworkPeering(ctx context.Context, body CreateNetworkPeeringJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteNetworkPeering request
	DeleteNetworkPeering(ctx context.Context, peeringUuid DeleteNetworkPeeringPeeringUuid, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetNetworkPeering request
	GetNetworkPeering(ctx context.Context, peeringUuid GetNetworkPeeringPeeringUuid, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ModifyNetworkPeeringWithBody request with any body
	ModifyNetworkPeeringWithBody(ctx context.Context, peeringUuid ModifyNetworkPeeringPeeringUuid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ModifyNetworkPeering(ctx context.Context, peeringUuid ModifyNetworkPeeringPeeringUuid, body ModifyNetworkPeeringJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListNetworkPeerings(ctx context.Context, params *ListNetworkPeeringsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListNetworkPeeringsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNetworkPeeringWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNetworkPeeringRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateNetworkPeering(ctx context.Context, body CreateNetworkPeeringJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateNetworkPeeringRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteNetworkPeering(ctx context.Context, peeringUuid DeleteNetworkPeeringPeeringUuid, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteNetworkPeeringRequest(c.Server, peeringUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetNetworkPeering(ctx context.Context, peeringUuid GetNetworkPeeringPeeringUuid, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetNetworkPeeringRequest(c.Server, peeringUuid)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ModifyNetworkPeeringWithBody(ctx context.Context, peeringUuid ModifyNetworkPeeringPeeringUuid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewModifyNetworkPeeringRequestWithBody(c.Server, peeringUuid, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ModifyNetworkPeering(ctx context.Context, peeringUuid ModifyNetworkPeeringPeeringUuid, body ModifyNetworkPeeringJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewModifyNetworkPeeringRequest(c.Server, peeringUuid, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListNetworkPeeringsRequest generates requests for ListNetworkPeerings
func NewListNetworkPeeringsRequest(server string, params *ListNetworkPeeringsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/network-peering")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Uuid != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "uuid", *params.Uuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NetworkUuidLocal != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "network_uuid_local", *params.NetworkUuidLocal, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NetworkUuidPeer != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "network_uuid_peer", *params.NetworkUuidPeer, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "uuid"}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Label != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "label", *params.Label, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateNetworkPeeringRequest calls the generic CreateNetworkPeering builder with application/json body
func NewCreateNetworkPeeringRequest(server string, body CreateNetworkPeeringJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateNetworkPeeringRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateNetworkPeeringRequestWithBody generates requests for CreateNetworkPeering with any type of body
func NewCreateNetworkPeeringRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/network-peering")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteNetworkPeeringRequest generates requests for DeleteNetworkPeering
func NewDeleteNetworkPeeringRequest(server string, peeringUuid DeleteNetworkPeeringPeeringUuid) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "peering_uuid", peeringUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/network-peering/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetNetworkPeeringRequest generates requests for GetNetworkPeering
func NewGetNetworkPeeringRequest(server string, peeringUuid GetNetworkPeeringPeeringUuid) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "peering_uuid", peeringUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/network-peering/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewModifyNetworkPeeringRequest calls the generic ModifyNetworkPeering builder with application/json body
func NewModifyNetworkPeeringRequest(server string, peeringUuid ModifyNetworkPeeringPeeringUuid, body ModifyNetworkPeeringJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewModifyNetworkPeeringRequestWithBody(server, peeringUuid, "application/json", bodyReader)
}

// NewModifyNetworkPeeringRequestWithBody generates requests for ModifyNetworkPeering with any type of body
func NewModifyNetworkPeeringRequestWithBody(server string, peeringUuid ModifyNetworkPeeringPeeringUuid, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "peering_uuid", peeringUuid, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: "uuid"})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/network-peering/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type NetworkPeeringClientWithResponsesInterface interface {
	// ListNetworkPeeringsWithResponse request
	ListNetworkPeeringsWithResponse(ctx context.Context, params *ListNetworkPeeringsParams, reqEditors ...RequestEditorFn) (*ListNetworkPeeringsResp, error)

	// CreateNetworkPeeringWithBodyWithResponse request with any body
	CreateNetworkPeeringWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNetworkPeeringResp, error)

	CreateNetworkPeeringWithResponse(ctx context.Context, body CreateNetworkPeeringJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNetworkPeeringResp, error)

	// DeleteNetworkPeeringWithResponse request
	DeleteNetworkPeeringWithResponse(ctx context.Context, peeringUuid DeleteNetworkPeeringPeeringUuid, reqEditors ...RequestEditorFn) (*DeleteNetworkPeeringResp, error)

	// GetNetworkPeeringWithResponse request
	GetNetworkPeeringWithResponse(ctx context.Context, peeringUuid GetNetworkPeeringPeeringUuid, reqEditors ...RequestEditorFn) (*GetNetworkPeeringResp, error)

	// ModifyNetworkPeeringWithBodyWithResponse request with any body
	ModifyNetworkPeeringWithBodyWithResponse(ctx context.Context, peeringUuid ModifyNetworkPeeringPeeringUuid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ModifyNetworkPeeringResp, error)

	ModifyNetworkPeeringWithResponse(ctx context.Context, peeringUuid ModifyNetworkPeeringPeeringUuid, body ModifyNetworkPeeringJSONRequestBody, reqEditors ...RequestEditorFn) (*ModifyNetworkPeeringResp, error)
}

type ListNetworkPeeringsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListNetworkPeerings200
	JSONDefault  *ListNetworkPeeringsDefault
}

// Status returns HTTPResponse.Status
func (r ListNetworkPeeringsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListNetworkPeeringsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateNetworkPeeringResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *CreateNetworkPeering201
	JSON400      *CreateNetworkPeering400
	JSON404      *CreateNetworkPeering404
	JSON409      *CreateNetworkPeering409
	JSONDefault  *CreateNetworkPeeringDefault
}

// Status returns HTTPResponse.Status
func (r CreateNetworkPeeringResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateNetworkPeeringResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteNetworkPeeringResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON404      *DeleteNetworkPeering404
	JSONDefault  *DeleteNetworkPeeringDefault
}

// Status returns HTTPResponse.Status
func (r DeleteNetworkPeeringResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteNetworkPeeringResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetNetworkPeeringResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetNetworkPeering200
	JSON404      *GetNetworkPeering404
	JSONDefault  *GetNetworkPeeringDefault
}

// Status returns HTTPResponse.Status
func (r GetNetworkPeeringResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetNetworkPeeringResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ModifyNetworkPeeringResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ModifyNetworkPeering200
	JSON400      *ModifyNetworkPeering400
	JSON404      *ModifyNetworkPeering404
	JSONDefault  *ModifyNetworkPeeringDefault
}

// Status returns HTTPResponse.Status
func (r ModifyNetworkPeeringResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ModifyNetworkPeeringResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListNetworkPeeringsWithResponse request returning *ListNetworkPeeringsResp
func (c *ClientWithResponses) ListNetworkPeeringsWithResponse(ctx context.Context, params *ListNetworkPeeringsParams, reqEditors ...RequestEditorFn) (*ListNetworkPeeringsResp, error) {
	rsp, err := c.ListNetworkPeerings(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListNetworkPeeringsResp(rsp)
}

// CreateNetworkPeeringWithBodyWithResponse request with arbitrary body returning *CreateNetworkPeeringResp
func (c *ClientWithResponses) CreateNetworkPeeringWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateNetworkPeeringResp, error) {
	rsp, err := c.CreateNetworkPeeringWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNetworkPeeringResp(rsp)
}

func (c *ClientWithResponses) CreateNetworkPeeringWithResponse(ctx context.Context, body CreateNetworkPeeringJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateNetworkPeeringResp, error) {
	rsp, err := c.CreateNetworkPeering(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateNetworkPeeringResp(rsp)
}

// DeleteNetworkPeeringWithResponse request returning *DeleteNetworkPeeringResp
func (c *ClientWithResponses) DeleteNetworkPeeringWithResponse(ctx context.Context, peeringUuid DeleteNetworkPeeringPeeringUuid, reqEditors ...RequestEditorFn) (*DeleteNetworkPeeringResp, error) {
	rsp, err := c.DeleteNetworkPeering(ctx, peeringUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteNetworkPeeringResp(rsp)
}

// GetNetworkPeeringWithResponse request returning *GetNetworkPeeringResp
func (c *ClientWithResponses) GetNetworkPeeringWithResponse(ctx context.Context, peeringUuid GetNetworkPeeringPeeringUuid, reqEditors ...RequestEditorFn) (*GetNetworkPeeringResp, error) {
	rsp, err := c.GetNetworkPeering(ctx, peeringUuid, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetNetworkPeeringResp(rsp)
}

// ModifyNetworkPeeringWithBodyWithResponse request with arbitrary body returning *ModifyNetworkPeeringResp
func (c *ClientWithResponses) ModifyNetworkPeeringWithBodyWithResponse(ctx context.Context, peeringUuid ModifyNetworkPeeringPeeringUuid, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ModifyNetworkPeeringResp, error) {
	rsp, err := c.ModifyNetworkPeeringWithBody(ctx, peeringUuid, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseModifyNetworkPeeringResp(rsp)
}

func (c *ClientWithResponses) ModifyNetworkPeeringWithResponse(ctx context.Context, peeringUuid ModifyNetworkPeeringPeeringUuid, body ModifyNetworkPeeringJSONRequestBody, reqEditors ...RequestEditorFn) (*ModifyNetworkPeeringResp, error) {
	rsp, err := c.ModifyNetworkPeering(ctx, peeringUuid, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseModifyNetworkPeeringResp(rsp)
}

// ParseListNetworkPeeringsResp parses an HTTP response from a ListNetworkPeeringsWithResponse call
func ParseListNetworkPeeringsResp(rsp *http.Response) (*ListNetworkPeeringsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListNetworkPeeringsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListNetworkPeerings200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ListNetworkPeeringsDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreateNetworkPeeringResp parses an HTTP response from a CreateNetworkPeeringWithResponse call
func ParseCreateNetworkPeeringResp(rsp *http.Response) (*CreateNetworkPeeringResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateNetworkPeeringResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreateNetworkPeering201
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CreateNetworkPeering400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest CreateNetworkPeering404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest CreateNetworkPeering409
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest CreateNetworkPeeringDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseDeleteNetworkPeeringResp parses an HTTP response from a DeleteNetworkPeeringWithResponse call
func ParseDeleteNetworkPeeringResp(rsp *http.Response) (*DeleteNetworkPeeringResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteNetworkPeeringResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest DeleteNetworkPeering404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest DeleteNetworkPeeringDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetNetworkPeeringResp parses an HTTP response from a GetNetworkPeeringWithResponse call
func ParseGetNetworkPeeringResp(rsp *http.Response) (*GetNetworkPeeringResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetNetworkPeeringResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetNetworkPeering200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest GetNetworkPeering404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest GetNetworkPeeringDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseModifyNetworkPeeringResp parses an HTTP response from a ModifyNetworkPeeringWithResponse call
func ParseModifyNetworkPeeringResp(rsp *http.Response) (*ModifyNetworkPeeringResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ModifyNetworkPeeringResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ModifyNetworkPeering200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ModifyNetworkPeering400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest ModifyNetworkPeering404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ModifyNetworkPeeringDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
