// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for NetworkPeeringConfiguredStatus.
const (
	NetworkPeeringConfiguredStatusActive   NetworkPeeringConfiguredStatus = "active"
	NetworkPeeringConfiguredStatusDisabled NetworkPeeringConfiguredStatus = "disabled"
)

// Valid indicates whether the value is a known member of the NetworkPeeringConfiguredStatus enum.
func (e NetworkPeeringConfiguredStatus) Valid() bool {
	switch e {
	case NetworkPeeringConfiguredStatusActive:
		return true
	case NetworkPeeringConfiguredStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for NetworkPeeringCreateConfiguredStatus.
const (
	NetworkPeeringCreateConfiguredStatusActive   NetworkPeeringCreateConfiguredStatus = "active"
	NetworkPeeringCreateConfiguredStatusDisabled NetworkPeeringCreateConfiguredStatus = "disabled"
)

// Valid indicates whether the value is a known member of the NetworkPeeringCreateConfiguredStatus enum.
func (e NetworkPeeringCreateConfiguredStatus) Valid() bool {
	switch e {
	case NetworkPeeringCreateConfiguredStatusActive:
		return true
	case NetworkPeeringCreateConfiguredStatusDisabled:
		return true
	default:
		return false
	}
}

// Defines values for NetworkPeeringIpFamily.
const (
	IPv4 NetworkPeeringIpFamily = "IPv4"
	IPv6 NetworkPeeringIpFamily = "IPv6"
)

// Valid indicates whether the value is a known member of the NetworkPeeringIpFamily enum.
func (e NetworkPeeringIpFamily) Valid() bool {
	switch e {
	case IPv4:
		return true
	case IPv6:
		return true
	default:
		return false
	}
}

// Defines values for NetworkPeeringState.
const (
	Active             NetworkPeeringState = "active"
	ConflictSubnet     NetworkPeeringState = "conflict-subnet"
	DeletedPeerNetwork NetworkPeeringState = "deleted-peer-network"
	Disabled           NetworkPeeringState = "disabled"
	Error              NetworkPeeringState = "error"
	MissingLocalRouter NetworkPeeringState = "missing-local-router"
	MissingPeerRouter  NetworkPeeringState = "missing-peer-router"
	PeerDisabled       NetworkPeeringState = "peer-disabled"
	PendingPeer        NetworkPeeringState = "pending-peer"
	Provisioning       NetworkPeeringState = "provisioning"
)

// Valid indicates whether the value is a known member of the NetworkPeeringState enum.
func (e NetworkPeeringState) Valid() bool {
	switch e {
	case Active:
		return true
	case ConflictSubnet:
		return true
	case DeletedPeerNetwork:
		return true
	case Disabled:
		return true
	case Error:
		return true
	case MissingLocalRouter:
		return true
	case MissingPeerRouter:
		return true
	case PeerDisabled:
		return true
	case PendingPeer:
		return true
	case Provisioning:
		return true
	default:
		return false
	}
}

// DatabaseDependencyResponse a dependency definition
type DatabaseDependencyResponse struct {
	// Required List of required properties when this dependency is present
	Required *[]string `json:"required,omitempty"`
}

// DatabasePropertySchemaResponse Schema definition for a single property
type DatabasePropertySchemaResponse struct {
	// Id Schema identifier
	Id *string `json:"$id,omitempty"`

	// Schema JSON Schema URI
	Schema *string `json:"$schema,omitempty"`

	// AdditionalProperties Whether additional properties are allowed
	AdditionalProperties *bool `json:"additionalProperties,omitempty"`

	// CreateOnly Whether the property can only be set during creation
	CreateOnly *bool `json:"createOnly,omitempty"`

	// Default Any valid JSON value is allowed here
	Default *map[string]interface{} `json:"default,omitempty"`

	// Dependencies Property dependency collection
	Dependencies *map[string]DatabaseDependencyResponse `json:"dependencies,omitempty"`

	// Description Description of the property
	Description *string `json:"description,omitempty"`

	// Enum Enumeration of allowed values
	Enum *[]interface{} `json:"enum,omitempty"`

	// Example Any valid JSON value is allowed here
	Example *map[string]interface{} `json:"example,omitempty"`

	// Items Schema definition for a single property
	Items *DatabasePropertySchemaResponse `json:"items,omitempty"`

	// MaxItems Maximum number of items for arrays
	MaxItems *int32 `json:"maxItems,omitempty"`

	// MaxLength Maximum length for the property schema
	MaxLength *int32 `json:"maxLength,omitempty"`

	// Maximum Maximum values for numeric properties
	Maximum *[]map[string]interface{} `json:"maximum,omitempty"`

	// MinLength Minimum length for the property schema
	MinLength *int32 `json:"minLength,omitempty"`

	// Minimum Minimum values for numeric properties
	Minimum *[]map[string]interface{} `json:"minimum,omitempty"`

	// Pattern Allowed patterns for the property
	Pattern *string `json:"pattern,omitempty"`

	// Properties Properties for object type
	Properties *map[string]DatabasePropertySchemaResponse `json:"properties,omitempty"`

	// Required List of required properties
	Required *[]string `json:"required,omitempty"`

	// Title Human-readable title for the property
	Title *string `json:"title,omitempty"`

	// Type Data type of the property
	Type *string `json:"type,omitempty"`

	// UserError User-friendly error message
	UserError *string `json:"user_error,omitempty"`
}

// KubernetesName Name
type KubernetesName = string

// KubernetesNodeName Node name
type KubernetesNodeName = string

// KubernetesUuid UUID
type KubernetesUuid = openapi_types.UUID

// NetworkPeering Network peering object describes a peering relationship between two networks
type NetworkPeering struct {
	ConfiguredStatus *NetworkPeeringConfiguredStatus `json:"configured_status,omitempty"`
	Name             *NetworkPeeringName             `json:"name,omitempty"`

	// Network Describes the local side of the peering
	Network *struct {
		IpNetworks *struct {
			IpNetwork *[]struct {
				// Address IP CIDR
				Address *NetworkPeeringIpCidr `json:"address,omitempty"`

				// Family IP address family
				Family *NetworkPeeringIpFamily `json:"family,omitempty"`
			} `json:"ip_network,omitempty"`
		} `json:"ip_networks,omitempty"`

		// Uuid Universally unique identifier
		Uuid *NetworkPeeringUuid `json:"uuid,omitempty"`
	} `json:"network,omitempty"`

	// PeerNetwork Describes the peer side of the peering
	PeerNetwork *struct {
		// IpNetworks note: only visible if both sides have a peering defined
		IpNetworks *struct {
			IpNetwork *[]struct {
				// Address IP CIDR
				Address *NetworkPeeringIpCidr `json:"address,omitempty"`

				// Family IP address family
				Family *NetworkPeeringIpFamily `json:"family,omitempty"`
			} `json:"ip_network,omitempty"`
		} `json:"ip_networks,omitempty"`

		// Uuid Universally unique identifier
		Uuid *NetworkPeeringUuid `json:"uuid,omitempty"`
	} `json:"peer_network,omitempty"`
	State *NetworkPeeringState `json:"state,omitempty"`

	// Uuid Universally unique identifier
	Uuid *NetworkPeeringUuid `json:"uuid,omitempty"`
}

// NetworkPeeringConfiguredStatus defines model for NetworkPeering.ConfiguredStatus.
type NetworkPeeringConfiguredStatus string

// NetworkPeeringCreate Describes the mutable properties when creating a network-peering between two networks
type NetworkPeeringCreate struct {
	ConfiguredStatus *NetworkPeeringCreateConfiguredStatus `json:"configured_status,omitempty"`
	Name             string                                `json:"name"`

	// Network Describes the local side of the peering
	Network struct {
		// Uuid Universally unique identifier
		Uuid NetworkPeeringUuid `json:"uuid"`
	} `json:"network"`

	// PeerNetwork Describes the peer side of the peering
	PeerNetwork struct {
		// Uuid Universally unique identifier
		Uuid NetworkPeeringUuid `json:"uuid"`
	} `json:"peer_network"`
}

// NetworkPeeringCreateConfiguredStatus defines model for NetworkPeeringCreate.ConfiguredStatus.
type NetworkPeeringCreateConfiguredStatus string

// NetworkPeeringError A general error response indicating that the request could not be fulfilled due to a technical issue.
type NetworkPeeringError struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// NetworkPeeringIpCidr IP CIDR
type NetworkPeeringIpCidr = string

// NetworkPeeringIpFamily IP address family
type NetworkPeeringIpFamily string

// NetworkPeeringModify Describes the mutable properties when modifying a network-peering
type NetworkPeeringModify struct {
	ConfiguredStatus interface{} `json:"configured_status,omitempty"`
	Name             *string     `json:"name,omitempty"`
}

// NetworkPeeringName defines model for networkPeeringName.
type NetworkPeeringName = string

// NetworkPeeringState defines model for networkPeeringState.
type NetworkPeeringState string

// NetworkPeeringUuid Universally unique identifier
type NetworkPeeringUuid = openapi_types.UUID

// NetworkPeerings Network peerings
type NetworkPeerings struct {
	NetworkPeerings struct {
		NetworkPeering []NetworkPeering `json:"network_peering"`
	} `json:"network_peerings"`
}

// DeleteNetworkPeeringPeeringUuid defines model for deleteNetworkPeeringPeeringUuid.
type DeleteNetworkPeeringPeeringUuid = openapi_types.UUID

// GetNetworkPeeringPeeringUuid defines model for getNetworkPeeringPeeringUuid.
type GetNetworkPeeringPeeringUuid = openapi_types.UUID

// KubernetesNameParameter Name
type KubernetesNameParameter = KubernetesName

// KubernetesNodeNameParameter Node name
type KubernetesNodeNameParameter = KubernetesNodeName

// KubernetesUuidParameter UUID
type KubernetesUuidParameter = KubernetesUuid

// ListNetworkPeeringsLabel defines model for listNetworkPeeringsLabel.
type ListNetworkPeeringsLabel = string

// ListNetworkPeeringsNetworkUuidLocal Universally unique identifier
type ListNetworkPeeringsNetworkUuidLocal = NetworkPeeringUuid

// ListNetworkPeeringsNetworkUuidPeer Universally unique identifier
type ListNetworkPeeringsNetworkUuidPeer = NetworkPeeringUuid

// ListNetworkPeeringsUuid Universally unique identifier
type ListNetworkPeeringsUuid = NetworkPeeringUuid

// ModifyNetworkPeeringPeeringUuid defines model for modifyNetworkPeeringPeeringUuid.
type ModifyNetworkPeeringPeeringUuid = openapi_types.UUID

// CreateNetworkPeering201 Network peering object describes a peering relationship between two networks
type CreateNetworkPeering201 = NetworkPeering

// CreateNetworkPeering400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateNetworkPeering400 = NetworkPeeringError

// CreateNetworkPeering404 A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateNetworkPeering404 = NetworkPeeringError

// CreateNetworkPeering409 A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateNetworkPeering409 = NetworkPeeringError

// CreateNetworkPeeringDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateNetworkPeeringDefault = NetworkPeeringError

// DeleteNetworkPeering404 A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteNetworkPeering404 = NetworkPeeringError

// DeleteNetworkPeeringDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteNetworkPeeringDefault = NetworkPeeringError

// GetNetworkPeering200 Network peering object describes a peering relationship between two networks
type GetNetworkPeering200 = NetworkPeering

// GetNetworkPeering404 A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetNetworkPeering404 = NetworkPeeringError

// GetNetworkPeeringDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetNetworkPeeringDefault = NetworkPeeringError

// ListNetworkPeerings200 Network peerings
type ListNetworkPeerings200 = NetworkPeerings

// ListNetworkPeeringsDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ListNetworkPeeringsDefault = NetworkPeeringError

// ModifyNetworkPeering200 Network peering object describes a peering relationship between two networks
type ModifyNetworkPeering200 = NetworkPeering

// ModifyNetworkPeering400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyNetworkPeering400 = NetworkPeeringError

// ModifyNetworkPeering404 A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyNetworkPeering404 = NetworkPeeringError

// ModifyNetworkPeeringDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyNetworkPeeringDefault = NetworkPeeringError

// CreateNetworkPeering Describes the mutable properties when creating a network-peering between two networks
type CreateNetworkPeering = NetworkPeeringCreate

// ModifyNetworkPeering Describes the mutable properties when modifying a network-peering
type ModifyNetworkPeering = NetworkPeeringModify

// ListNetworkPeeringsParams defines parameters for ListNetworkPeerings.
type ListNetworkPeeringsParams struct {
	// Uuid Filter by network peering UUID.
	Uuid *ListNetworkPeeringsUuid `form:"uuid,omitempty" json:"uuid,omitempty"`

	// NetworkUuidLocal Filter by local network uuid.
	NetworkUuidLocal *ListNetworkPeeringsNetworkUuidLocal `form:"network_uuid_local,omitempty" json:"network_uuid_local,omitempty"`

	// NetworkUuidPeer Filter by peer network uuid.
	NetworkUuidPeer *ListNetworkPeeringsNetworkUuidPeer `form:"network_uuid_peer,omitempty" json:"network_uuid_peer,omitempty"`

	// Label Label filter in the form key=value. Can be specified multiple times to filter by multiple labels.
	Label *ListNetworkPeeringsLabel `form:"label,omitempty" json:"label,omitempty"`
}

// CreateNetworkPeeringJSONRequestBody defines body for CreateNetworkPeering for application/json ContentType.
type CreateNetworkPeeringJSONRequestBody = NetworkPeeringCreate

// ModifyNetworkPeeringJSONRequestBody defines body for ModifyNetworkPeering for application/json ContentType.
type ModifyNetworkPeeringJSONRequestBody = NetworkPeeringModify
