// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// The interface specification for the client above.
type PartnerClientInterface interface {

	// ListPartnerAccounts Get account list
	//
	// Returns list of accounts associated with the partner.
	//
	// Corresponds with GET /1.3/partner/accounts (the `ListPartnerAccounts` operationId).
	ListPartnerAccounts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePartnerAccountWithBody Create new account
	//
	// Creates new UpCloud account that will be linked to partner's existing invoicing.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /1.3/partner/accounts (the `CreatePartnerAccount` operationId).
	CreatePartnerAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreatePartnerAccount Create new account
	//
	// Creates new UpCloud account that will be linked to partner's existing invoicing.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /1.3/partner/accounts (the `CreatePartnerAccount` operationId).
	CreatePartnerAccount(ctx context.Context, body CreatePartnerAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListPartnerAccounts Get account list
//
// Returns list of accounts associated with the partner.
//
// Corresponds with GET /1.3/partner/accounts (the `ListPartnerAccounts` operationId).
func (c *Client) ListPartnerAccounts(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListPartnerAccountsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePartnerAccountWithBody Create new account
//
// Creates new UpCloud account that will be linked to partner's existing invoicing.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /1.3/partner/accounts (the `CreatePartnerAccount` operationId).
func (c *Client) CreatePartnerAccountWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePartnerAccountRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreatePartnerAccount Create new account
//
// Creates new UpCloud account that will be linked to partner's existing invoicing.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /1.3/partner/accounts (the `CreatePartnerAccount` operationId).
func (c *Client) CreatePartnerAccount(ctx context.Context, body CreatePartnerAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreatePartnerAccountRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListPartnerAccountsRequest constructs an http.Request for the ListPartnerAccounts method
func NewListPartnerAccountsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/partner/accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreatePartnerAccountRequest calls the generic CreatePartnerAccount builder with application/json body
func NewCreatePartnerAccountRequest(server string, body CreatePartnerAccountJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreatePartnerAccountRequestWithBody(server, "application/json", bodyReader)
}

// NewCreatePartnerAccountRequestWithBody constructs an http.Request for the CreatePartnerAccount method, with any body, and a specified content type
func NewCreatePartnerAccountRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/partner/accounts")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type PartnerClientWithResponsesInterface interface {

	// ListPartnerAccountsWithResponse Get account list
	//
	// Returns list of accounts associated with the partner.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /1.3/partner/accounts (the `ListPartnerAccounts` operationId).
	ListPartnerAccountsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPartnerAccountsResp, error)

	// CreatePartnerAccountWithBodyWithResponse Create new account
	//
	// Creates new UpCloud account that will be linked to partner's existing invoicing.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /1.3/partner/accounts (the `CreatePartnerAccount` operationId).
	CreatePartnerAccountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePartnerAccountResp, error)

	// CreatePartnerAccountWithResponse Create new account
	//
	// Creates new UpCloud account that will be linked to partner's existing invoicing.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /1.3/partner/accounts (the `CreatePartnerAccount` operationId).
	CreatePartnerAccountWithResponse(ctx context.Context, body CreatePartnerAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePartnerAccountResp, error)
}

type ListPartnerAccountsResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ListPartnerAccounts200
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ListPartnerAccountsDefault
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListPartnerAccountsResp) GetJSON200() *ListPartnerAccounts200 {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListPartnerAccountsResp) GetJSONDefault() *ListPartnerAccountsDefault {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListPartnerAccountsResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListPartnerAccountsResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListPartnerAccountsResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListPartnerAccountsResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreatePartnerAccountResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON201 the response for an HTTP 201 `application/json` response
	JSON201 *CreatePartnerAccount201
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *CreatePartnerAccount400
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *CreatePartnerAccount403
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *CreatePartnerAccount409
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *CreatePartnerAccountDefault
}

// GetJSON201 returns the response for an HTTP 201 `application/json` response
func (r CreatePartnerAccountResp) GetJSON201() *CreatePartnerAccount201 {
	return r.JSON201
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r CreatePartnerAccountResp) GetJSON400() *CreatePartnerAccount400 {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r CreatePartnerAccountResp) GetJSON403() *CreatePartnerAccount403 {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r CreatePartnerAccountResp) GetJSON409() *CreatePartnerAccount409 {
	return r.JSON409
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r CreatePartnerAccountResp) GetJSONDefault() *CreatePartnerAccountDefault {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r CreatePartnerAccountResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreatePartnerAccountResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreatePartnerAccountResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreatePartnerAccountResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListPartnerAccountsWithResponse Get account list
//
// Returns list of accounts associated with the partner.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /1.3/partner/accounts (the `ListPartnerAccounts` operationId).
func (c *ClientWithResponses) ListPartnerAccountsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListPartnerAccountsResp, error) {
	rsp, err := c.ListPartnerAccounts(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListPartnerAccountsResp(rsp)
}

// CreatePartnerAccountWithBodyWithResponse Create new account
//
// Creates new UpCloud account that will be linked to partner's existing invoicing.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /1.3/partner/accounts (the `CreatePartnerAccount` operationId).
func (c *ClientWithResponses) CreatePartnerAccountWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreatePartnerAccountResp, error) {
	rsp, err := c.CreatePartnerAccountWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePartnerAccountResp(rsp)
}

// CreatePartnerAccountWithResponse Create new account
//
// Creates new UpCloud account that will be linked to partner's existing invoicing.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /1.3/partner/accounts (the `CreatePartnerAccount` operationId).
func (c *ClientWithResponses) CreatePartnerAccountWithResponse(ctx context.Context, body CreatePartnerAccountJSONRequestBody, reqEditors ...RequestEditorFn) (*CreatePartnerAccountResp, error) {
	rsp, err := c.CreatePartnerAccount(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreatePartnerAccountResp(rsp)
}

// ParseListPartnerAccountsResp parses an HTTP response from a ListPartnerAccountsWithResponse call
func ParseListPartnerAccountsResp(rsp *http.Response) (*ListPartnerAccountsResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListPartnerAccountsResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListPartnerAccounts200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ListPartnerAccountsDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseCreatePartnerAccountResp parses an HTTP response from a CreatePartnerAccountWithResponse call
func ParseCreatePartnerAccountResp(rsp *http.Response) (*CreatePartnerAccountResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreatePartnerAccountResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest CreatePartnerAccount201
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest CreatePartnerAccount400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest CreatePartnerAccount403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest CreatePartnerAccount409
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest CreatePartnerAccountDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
