// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DatabaseDependencyResponse a dependency definition
type DatabaseDependencyResponse struct {
	// Required List of required properties when this dependency is present
	Required *[]string `json:"required,omitempty"`
}

// DatabasePropertySchemaResponse Schema definition for a single property
type DatabasePropertySchemaResponse struct {
	// Id Schema identifier
	Id *string `json:"$id,omitempty"`

	// Schema JSON Schema URI
	Schema *string `json:"$schema,omitempty"`

	// AdditionalProperties Whether additional properties are allowed
	AdditionalProperties *bool `json:"additionalProperties,omitempty"`

	// CreateOnly Whether the property can only be set during creation
	CreateOnly *bool `json:"createOnly,omitempty"`

	// Default Any valid JSON value is allowed here
	Default *map[string]interface{} `json:"default,omitempty"`

	// Dependencies Property dependency collection
	Dependencies *map[string]DatabaseDependencyResponse `json:"dependencies,omitempty"`

	// Description Description of the property
	Description *string `json:"description,omitempty"`

	// Enum Enumeration of allowed values
	Enum *[]interface{} `json:"enum,omitempty"`

	// Example Any valid JSON value is allowed here
	Example *map[string]interface{} `json:"example,omitempty"`

	// Items Schema definition for a single property
	Items *DatabasePropertySchemaResponse `json:"items,omitempty"`

	// MaxItems Maximum number of items for arrays
	MaxItems *int32 `json:"maxItems,omitempty"`

	// MaxLength Maximum length for the property schema
	MaxLength *int32 `json:"maxLength,omitempty"`

	// Maximum Maximum values for numeric properties
	Maximum *[]map[string]interface{} `json:"maximum,omitempty"`

	// MinLength Minimum length for the property schema
	MinLength *int32 `json:"minLength,omitempty"`

	// Minimum Minimum values for numeric properties
	Minimum *[]map[string]interface{} `json:"minimum,omitempty"`

	// Pattern Allowed patterns for the property
	Pattern *string `json:"pattern,omitempty"`

	// Properties Properties for object type
	Properties *map[string]DatabasePropertySchemaResponse `json:"properties,omitempty"`

	// Required List of required properties
	Required *[]string `json:"required,omitempty"`

	// Title Human-readable title for the property
	Title *string `json:"title,omitempty"`

	// Type Data type of the property
	Type *string `json:"type,omitempty"`

	// UserError User-friendly error message
	UserError *string `json:"user_error,omitempty"`
}

// KubernetesName Name
type KubernetesName = string

// KubernetesNodeName Node name
type KubernetesNodeName = string

// KubernetesUuid UUID
type KubernetesUuid = openapi_types.UUID

// Permission A single permission object.
type Permission struct {
	// Permission Permission document defining access rights for a sub-account to a specific resource.
	Permission *PermissionDocument `json:"permission,omitempty"`
}

// PermissionDocument Permission document defining access rights for a sub-account to a specific resource.
type PermissionDocument struct {
	// Options Target specific options.
	Options *map[string]interface{} `json:"options,omitempty"`

	// TargetIdentifier Target identifying string. This is type specific and in most cases is an UUID4. Wildcard value "*" can be used to
	// reference all target resources.
	TargetIdentifier PermissionTargetIdentifier `json:"target_identifier"`

	// TargetType Type of the target to grant permission to
	TargetType PermissionTargetType `json:"target_type"`

	// User Username for an account.
	User PermissionUserName `json:"user"`
}

// PermissionError A general error response indicating that the request could not be fulfilled due to a technical issue.
type PermissionError struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// PermissionTargetIdentifier Target identifying string. This is type specific and in most cases is an UUID4. Wildcard value "*" can be used to
// reference all target resources.
type PermissionTargetIdentifier = string

// PermissionTargetType Type of the target to grant permission to
type PermissionTargetType = interface{}

// PermissionUserName Username for an account.
type PermissionUserName = string

// Permissions List of permissions.
type Permissions struct {
	Permissions struct {
		Permission []PermissionDocument `json:"permission"`
	} `json:"permissions"`
}

// GrantPermissionSkipTargetCheck defines model for grantPermissionSkipTargetCheck.
type GrantPermissionSkipTargetCheck = bool

// KubernetesNameParameter Name
type KubernetesNameParameter = KubernetesName

// KubernetesNodeNameParameter Node name
type KubernetesNodeNameParameter = KubernetesNodeName

// KubernetesUuidParameter UUID
type KubernetesUuidParameter = KubernetesUuid

// RevokeAllPermissionsByTargetMainAccountId defines model for revokeAllPermissionsByTargetMainAccountId.
type RevokeAllPermissionsByTargetMainAccountId = int

// RevokeAllPermissionsByTargetTargetIdentifier defines model for revokeAllPermissionsByTargetTargetIdentifier.
type RevokeAllPermissionsByTargetTargetIdentifier = string

// RevokeAllPermissionsByTargetTargetType defines model for revokeAllPermissionsByTargetTargetType.
type RevokeAllPermissionsByTargetTargetType = string

// RevokeAllPermissionsByUserUser defines model for revokeAllPermissionsByUserUser.
type RevokeAllPermissionsByUserUser = string

// GrantPermission200 A single permission object.
type GrantPermission200 = Permission

// GrantPermissionDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GrantPermissionDefault = PermissionError

// ListPermissions200 List of permissions.
type ListPermissions200 = Permissions

// ListPermissionsDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ListPermissionsDefault = PermissionError

// ReplacePermissions200 List of permissions.
type ReplacePermissions200 = Permissions

// ReplacePermissionsDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ReplacePermissionsDefault = PermissionError

// RevokeAllPermissionsByTargetDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type RevokeAllPermissionsByTargetDefault = PermissionError

// RevokeAllPermissionsByUserDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type RevokeAllPermissionsByUserDefault = PermissionError

// RevokePermissionDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type RevokePermissionDefault = PermissionError

// GrantPermission A single permission object.
type GrantPermission = Permission

// ReplacePermissions A single permission object.
type ReplacePermissions = Permission

// RevokePermission A single permission object.
type RevokePermission = Permission

// GrantPermissionParams defines parameters for GrantPermission.
type GrantPermissionParams struct {
	// SkipTargetCheck If true, skips the check whether the target resource exists. Default is false.
	SkipTargetCheck *GrantPermissionSkipTargetCheck `form:"skip_target_check,omitempty" json:"skip_target_check,omitempty"`
}

// RevokeAllPermissionsByTargetParams defines parameters for RevokeAllPermissionsByTarget.
type RevokeAllPermissionsByTargetParams struct {
	// MainAccountId If specified, revokes permissions for resources owned by the specified main account ID. Default is the current main account.
	MainAccountId *RevokeAllPermissionsByTargetMainAccountId `form:"main_account_id,omitempty" json:"main_account_id,omitempty"`
}

// ReplacePermissionsJSONRequestBody defines body for ReplacePermissions for application/json ContentType.
type ReplacePermissionsJSONRequestBody = Permission

// GrantPermissionJSONRequestBody defines body for GrantPermission for application/json ContentType.
type GrantPermissionJSONRequestBody = Permission

// RevokePermissionJSONRequestBody defines body for RevokePermission for application/json ContentType.
type RevokePermissionJSONRequestBody = Permission
