// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PriceError400ErrorCode.
const (
	PRICEINVALID PriceError400ErrorCode = "PRICE_INVALID"
)

// Valid indicates whether the value is a known member of the PriceError400ErrorCode enum.
func (e PriceError400ErrorCode) Valid() bool {
	switch e {
	case PRICEINVALID:
		return true
	default:
		return false
	}
}

// DatabaseDependencyResponse a dependency definition
type DatabaseDependencyResponse struct {
	// Required List of required properties when this dependency is present
	Required *[]string `json:"required,omitempty"`
}

// DatabasePropertySchemaResponse Schema definition for a single property
type DatabasePropertySchemaResponse struct {
	// Id Schema identifier
	Id *string `json:"$id,omitempty"`

	// Schema JSON Schema URI
	Schema *string `json:"$schema,omitempty"`

	// AdditionalProperties Whether additional properties are allowed
	AdditionalProperties *bool `json:"additionalProperties,omitempty"`

	// CreateOnly Whether the property can only be set during creation
	CreateOnly *bool `json:"createOnly,omitempty"`

	// Default Any valid JSON value is allowed here
	Default *map[string]interface{} `json:"default,omitempty"`

	// Dependencies Property dependency collection
	Dependencies *map[string]DatabaseDependencyResponse `json:"dependencies,omitempty"`

	// Description Description of the property
	Description *string `json:"description,omitempty"`

	// Enum Enumeration of allowed values
	Enum *[]interface{} `json:"enum,omitempty"`

	// Example Any valid JSON value is allowed here
	Example *map[string]interface{} `json:"example,omitempty"`

	// Items Schema definition for a single property
	Items *DatabasePropertySchemaResponse `json:"items,omitempty"`

	// MaxItems Maximum number of items for arrays
	MaxItems *int32 `json:"maxItems,omitempty"`

	// MaxLength Maximum length for the property schema
	MaxLength *int32 `json:"maxLength,omitempty"`

	// Maximum Maximum values for numeric properties
	Maximum *[]map[string]interface{} `json:"maximum,omitempty"`

	// MinLength Minimum length for the property schema
	MinLength *int32 `json:"minLength,omitempty"`

	// Minimum Minimum values for numeric properties
	Minimum *[]map[string]interface{} `json:"minimum,omitempty"`

	// Pattern Allowed patterns for the property
	Pattern *string `json:"pattern,omitempty"`

	// Properties Properties for object type
	Properties *map[string]DatabasePropertySchemaResponse `json:"properties,omitempty"`

	// Required List of required properties
	Required *[]string `json:"required,omitempty"`

	// Title Human-readable title for the property
	Title *string `json:"title,omitempty"`

	// Type Data type of the property
	Type *string `json:"type,omitempty"`

	// UserError User-friendly error message
	UserError *string `json:"user_error,omitempty"`
}

// KubernetesName Name
type KubernetesName = string

// KubernetesNodeName Node name
type KubernetesNodeName = string

// KubernetesUuid UUID
type KubernetesUuid = openapi_types.UUID

// PriceCurrency ISO 4217 code
type PriceCurrency = string

// PriceError A general error response indicating that the request could not be fulfilled due to a technical issue.
type PriceError struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// PriceError400 Invalid price request error.
type PriceError400 struct {
	Error struct {
		Code    PriceError400ErrorCode `json:"code"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// PriceError400ErrorCode defines model for PriceError400.Error.Code.
type PriceError400ErrorCode string

// Prices Price list for UpCloud resources and services.
type Prices struct {
	Prices struct {
		// Currency ISO 4217 code
		Currency PriceCurrency `json:"currency"`
		Type     interface{}   `json:"type,omitempty"`
		Zone     interface{}   `json:"zone"`
	} `json:"prices"`
}

// ZonePrices Pricing information organized by zone.
type ZonePrices struct {
	Items *map[string]struct {
		Amount int32   `json:"amount"`
		Price  float64 `json:"price"`
	} `json:"items,omitempty"`
}

// KubernetesNameParameter Name
type KubernetesNameParameter = KubernetesName

// KubernetesNodeNameParameter Node name
type KubernetesNodeNameParameter = KubernetesNodeName

// KubernetesUuidParameter UUID
type KubernetesUuidParameter = KubernetesUuid

// GetPrice200 Price list for UpCloud resources and services.
type GetPrice200 = Prices

// GetPrice400 Invalid price request error.
type GetPrice400 = PriceError400

// GetPriceDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetPriceDefault = PriceError
