// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// The interface specification for the client above.
type PriceClientInterface interface {

	// GetPrice Returns a price list.
	//
	// Corresponds with GET /1.3/price (the `GetPrice` operationId).
	GetPrice(ctx context.Context, params *GetPriceParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetPrice Returns a price list.
//
// Corresponds with GET /1.3/price (the `GetPrice` operationId).
func (c *Client) GetPrice(ctx context.Context, params *GetPriceParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPriceRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetPriceRequest constructs an http.Request for the GetPrice method
func NewGetPriceRequest(server string, params *GetPriceParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/price")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Zone != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "zone", *params.Zone, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type PriceClientWithResponsesInterface interface {

	// GetPriceWithResponse Returns a price list.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /1.3/price (the `GetPrice` operationId).
	GetPriceWithResponse(ctx context.Context, params *GetPriceParams, reqEditors ...RequestEditorFn) (*GetPriceResp, error)
}

type GetPriceResp struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *GetPrice200
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *GetPrice400
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *GetPriceDefault
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetPriceResp) GetJSON200() *GetPrice200 {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r GetPriceResp) GetJSON400() *GetPrice400 {
	return r.JSON400
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r GetPriceResp) GetApplicationproblemJSONDefault() *GetPriceDefault {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r GetPriceResp) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetPriceResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPriceResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetPriceResp) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetPriceWithResponse Returns a price list.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /1.3/price (the `GetPrice` operationId).
func (c *ClientWithResponses) GetPriceWithResponse(ctx context.Context, params *GetPriceParams, reqEditors ...RequestEditorFn) (*GetPriceResp, error) {
	rsp, err := c.GetPrice(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPriceResp(rsp)
}

// ParseGetPriceResp parses an HTTP response from a GetPriceWithResponse call
func ParseGetPriceResp(rsp *http.Response) (*GetPriceResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPriceResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetPrice200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest GetPrice400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest GetPriceDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
