// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	"encoding/json"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for RouterCreateRouterStaticRoutesNexthop1.
const (
	RouterCreateRouterStaticRoutesNexthop1NoNexthop RouterCreateRouterStaticRoutesNexthop1 = "no-nexthop"
)

// Valid indicates whether the value is a known member of the RouterCreateRouterStaticRoutesNexthop1 enum.
func (e RouterCreateRouterStaticRoutesNexthop1) Valid() bool {
	switch e {
	case RouterCreateRouterStaticRoutesNexthop1NoNexthop:
		return true
	default:
		return false
	}
}

// Defines values for RouterModifyRouterStaticRoutesNexthop1.
const (
	RouterModifyRouterStaticRoutesNexthop1NoNexthop RouterModifyRouterStaticRoutesNexthop1 = "no-nexthop"
)

// Valid indicates whether the value is a known member of the RouterModifyRouterStaticRoutesNexthop1 enum.
func (e RouterModifyRouterStaticRoutesNexthop1) Valid() bool {
	switch e {
	case RouterModifyRouterStaticRoutesNexthop1NoNexthop:
		return true
	default:
		return false
	}
}

// Defines values for RouterRouteNexthopNexthop1.
const (
	RouterRouteNexthopNexthop1NoNexthop RouterRouteNexthopNexthop1 = "no-nexthop"
)

// Valid indicates whether the value is a known member of the RouterRouteNexthopNexthop1 enum.
func (e RouterRouteNexthopNexthop1) Valid() bool {
	switch e {
	case RouterRouteNexthopNexthop1NoNexthop:
		return true
	default:
		return false
	}
}

// Defines values for RouterStaticRouteType.
const (
	RouterStaticRouteTypeService RouterStaticRouteType = "service"
	RouterStaticRouteTypeUser    RouterStaticRouteType = "user"
)

// Valid indicates whether the value is a known member of the RouterStaticRouteType enum.
func (e RouterStaticRouteType) Valid() bool {
	switch e {
	case RouterStaticRouteTypeService:
		return true
	case RouterStaticRouteTypeUser:
		return true
	default:
		return false
	}
}

// Defines values for RouterType.
const (
	RouterTypeNormal  RouterType = "normal"
	RouterTypeService RouterType = "service"
)

// Valid indicates whether the value is a known member of the RouterType enum.
func (e RouterType) Valid() bool {
	switch e {
	case RouterTypeNormal:
		return true
	case RouterTypeService:
		return true
	default:
		return false
	}
}

// Router Schema for a single router
type Router struct {
	// Router Router describes a virtual router that can route between SDN networks
	Router RouterDetails `json:"router"`
}

// RouterCreate Request schema for creating a router
type RouterCreate struct {
	Router struct {
		Labels *[]RouterLabel `json:"labels,omitempty"`
		Name   string         `json:"name"`

		// StaticRoutes Static routes that will be added to the routing table of the SDN router
		StaticRoutes *[]struct {
			Name    *string                                  `json:"name,omitempty"`
			Nexthop RouterCreate_Router_StaticRoutes_Nexthop `json:"nexthop"`

			// Route IP CIDR
			Route RouterIpCidr `json:"route"`
		} `json:"static_routes,omitempty"`
	} `json:"router"`
}

// RouterCreateRouterStaticRoutesNexthop1 defines model for RouterCreate.Router.StaticRoutes.Nexthop.1.
type RouterCreateRouterStaticRoutesNexthop1 string

// RouterCreate_Router_StaticRoutes_Nexthop defines model for RouterCreate.Router.StaticRoutes.Nexthop.
type RouterCreate_Router_StaticRoutes_Nexthop struct {
	union json.RawMessage
}

// RouterDetails Router describes a virtual router that can route between SDN networks
type RouterDetails struct {
	// AttachedNetworkGateways Gateways of the networks attached to the router.
	AttachedNetworkGateways []struct {
		// Uuid Universally unique identifier
		Uuid RouterUuid `json:"uuid"`
	} `json:"attached_network_gateways"`

	// AttachedNetworks Networks attached to the router.
	AttachedNetworks struct {
		Network []struct {
			// Uuid Universally unique identifier
			Uuid RouterUuid `json:"uuid"`
		} `json:"network"`
	} `json:"attached_networks"`
	Labels       []RouterLabel        `json:"labels"`
	Name         string               `json:"name"`
	StaticRoutes []RouterRouteNexthop `json:"static_routes"`

	// Type Type of the router.
	Type RouterType `json:"type"`

	// Uuid Universally unique identifier
	Uuid RouterUuid `json:"uuid"`
}

// RouterError A general error response indicating that the request could not be fulfilled due to a technical issue.
type RouterError struct {
	Error struct {
		// ErrorCode Examples: GENERAL_FAILURE
		ErrorCode string `json:"error_code"`

		// ErrorMessage Examples: Your request could not be fulfilled due to a technical issue.
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// RouterIpAddress IP address
type RouterIpAddress struct {
	union json.RawMessage
}

// RouterIpAddress0 IPv4 address
type RouterIpAddress0 = string

// RouterIpAddress1 IPv6 address
type RouterIpAddress1 = string

// RouterIpCidr IP CIDR
type RouterIpCidr = string

// RouterLabel A key/value pair to label and categorize resources
type RouterLabel struct {
	// Key Label key used to classify the resource
	Key string `json:"key"`

	// Value Value associated with the label key
	Value string `json:"value"`
}

// RouterModify Request schema for modifying a router
type RouterModify struct {
	Router struct {
		Labels *[]RouterLabel `json:"labels,omitempty"`
		Name   *string        `json:"name,omitempty"`

		// StaticRoutes Static routes that will be added to the routing table of the SDN router
		StaticRoutes *[]struct {
			Name    *string                                  `json:"name,omitempty"`
			Nexthop RouterModify_Router_StaticRoutes_Nexthop `json:"nexthop"`

			// Route IP CIDR
			Route RouterIpCidr `json:"route"`
		} `json:"static_routes,omitempty"`
	} `json:"router"`
}

// RouterModifyRouterStaticRoutesNexthop1 defines model for RouterModify.Router.StaticRoutes.Nexthop.1.
type RouterModifyRouterStaticRoutesNexthop1 string

// RouterModify_Router_StaticRoutes_Nexthop defines model for RouterModify.Router.StaticRoutes.Nexthop.
type RouterModify_Router_StaticRoutes_Nexthop struct {
	union json.RawMessage
}

// RouterRouteNexthop Static route with nexthop information.
type RouterRouteNexthop struct {
	Name    string                     `json:"name"`
	Nexthop RouterRouteNexthop_Nexthop `json:"nexthop"`

	// Route IP CIDR
	Route RouterIpCidr `json:"route"`

	// Type Type of static route.
	Type RouterStaticRouteType `json:"type"`
}

// RouterRouteNexthopNexthop1 defines model for RouterRouteNexthop.Nexthop.1.
type RouterRouteNexthopNexthop1 string

// RouterRouteNexthop_Nexthop defines model for RouterRouteNexthop.Nexthop.
type RouterRouteNexthop_Nexthop struct {
	union json.RawMessage
}

// RouterStaticRouteType Type of static route.
type RouterStaticRouteType string

// RouterType Type of the router.
type RouterType string

// RouterUuid Universally unique identifier
type RouterUuid = openapi_types.UUID

// Routers A list of routers
type Routers struct {
	Routers struct {
		Router []RouterDetails `json:"router"`
	} `json:"routers"`
}

// DeleteRouterRouter Universally unique identifier
type DeleteRouterRouter = RouterUuid

// GetRouterRouter Universally unique identifier
type GetRouterRouter = RouterUuid

// ListRoutersLabel A key/value pair to label and categorize resources
type ListRoutersLabel = RouterLabel

// ModifyRouterRouter Universally unique identifier
type ModifyRouterRouter = RouterUuid

// CreateRouter201 Schema for a single router
type CreateRouter201 = Router

// CreateRouter400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateRouter400 = RouterError

// CreateRouter409 A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateRouter409 = RouterError

// CreateRouterDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateRouterDefault = RouterError

// DeleteRouter404 A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteRouter404 = RouterError

// DeleteRouter409 A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteRouter409 = RouterError

// DeleteRouterDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteRouterDefault = RouterError

// GetRouter200 Schema for a single router
type GetRouter200 = Router

// GetRouter404 A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetRouter404 = RouterError

// GetRouterDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetRouterDefault = RouterError

// ListRouters200 A list of routers
type ListRouters200 = Routers

// ListRoutersDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ListRoutersDefault = RouterError

// ModifyRouter200 Schema for a single router
type ModifyRouter200 = Router

// ModifyRouter400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyRouter400 = RouterError

// ModifyRouter404 A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyRouter404 = RouterError

// ModifyRouter409 A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyRouter409 = RouterError

// ModifyRouterDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyRouterDefault = RouterError

// CreateRouter Request schema for creating a router
type CreateRouter = RouterCreate

// ModifyRouter Request schema for modifying a router
type ModifyRouter = RouterModify

// ListRoutersParams defines parameters for ListRouters.
type ListRoutersParams struct {
	// Label A label filter. Can be specified multiple times to create an AND condition. Format: label=key:value
	Label *ListRoutersLabel `form:"label,omitempty" json:"label,omitempty"`
}

// CreateRouterJSONRequestBody defines body for CreateRouter for application/json ContentType.
type CreateRouterJSONRequestBody = RouterCreate

// ModifyRouterJSONRequestBody defines body for ModifyRouter for application/json ContentType.
type ModifyRouterJSONRequestBody = RouterModify

// AsRouterIpAddress returns the union data inside the RouterCreate_Router_StaticRoutes_Nexthop as a RouterIpAddress
func (t RouterCreate_Router_StaticRoutes_Nexthop) AsRouterIpAddress() (RouterIpAddress, error) {
	var body RouterIpAddress
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRouterIpAddress overwrites any union data inside the RouterCreate_Router_StaticRoutes_Nexthop as the provided RouterIpAddress
func (t *RouterCreate_Router_StaticRoutes_Nexthop) FromRouterIpAddress(v RouterIpAddress) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRouterIpAddress performs a merge with any union data inside the RouterCreate_Router_StaticRoutes_Nexthop, using the provided RouterIpAddress
func (t *RouterCreate_Router_StaticRoutes_Nexthop) MergeRouterIpAddress(v RouterIpAddress) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRouterCreateRouterStaticRoutesNexthop1 returns the union data inside the RouterCreate_Router_StaticRoutes_Nexthop as a RouterCreateRouterStaticRoutesNexthop1
func (t RouterCreate_Router_StaticRoutes_Nexthop) AsRouterCreateRouterStaticRoutesNexthop1() (RouterCreateRouterStaticRoutesNexthop1, error) {
	var body RouterCreateRouterStaticRoutesNexthop1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRouterCreateRouterStaticRoutesNexthop1 overwrites any union data inside the RouterCreate_Router_StaticRoutes_Nexthop as the provided RouterCreateRouterStaticRoutesNexthop1
func (t *RouterCreate_Router_StaticRoutes_Nexthop) FromRouterCreateRouterStaticRoutesNexthop1(v RouterCreateRouterStaticRoutesNexthop1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRouterCreateRouterStaticRoutesNexthop1 performs a merge with any union data inside the RouterCreate_Router_StaticRoutes_Nexthop, using the provided RouterCreateRouterStaticRoutesNexthop1
func (t *RouterCreate_Router_StaticRoutes_Nexthop) MergeRouterCreateRouterStaticRoutesNexthop1(v RouterCreateRouterStaticRoutesNexthop1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RouterCreate_Router_StaticRoutes_Nexthop) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RouterCreate_Router_StaticRoutes_Nexthop) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRouterIpAddress0 returns the union data inside the RouterIpAddress as a RouterIpAddress0
func (t RouterIpAddress) AsRouterIpAddress0() (RouterIpAddress0, error) {
	var body RouterIpAddress0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRouterIpAddress0 overwrites any union data inside the RouterIpAddress as the provided RouterIpAddress0
func (t *RouterIpAddress) FromRouterIpAddress0(v RouterIpAddress0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRouterIpAddress0 performs a merge with any union data inside the RouterIpAddress, using the provided RouterIpAddress0
func (t *RouterIpAddress) MergeRouterIpAddress0(v RouterIpAddress0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRouterIpAddress1 returns the union data inside the RouterIpAddress as a RouterIpAddress1
func (t RouterIpAddress) AsRouterIpAddress1() (RouterIpAddress1, error) {
	var body RouterIpAddress1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRouterIpAddress1 overwrites any union data inside the RouterIpAddress as the provided RouterIpAddress1
func (t *RouterIpAddress) FromRouterIpAddress1(v RouterIpAddress1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRouterIpAddress1 performs a merge with any union data inside the RouterIpAddress, using the provided RouterIpAddress1
func (t *RouterIpAddress) MergeRouterIpAddress1(v RouterIpAddress1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RouterIpAddress) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RouterIpAddress) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRouterIpAddress returns the union data inside the RouterModify_Router_StaticRoutes_Nexthop as a RouterIpAddress
func (t RouterModify_Router_StaticRoutes_Nexthop) AsRouterIpAddress() (RouterIpAddress, error) {
	var body RouterIpAddress
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRouterIpAddress overwrites any union data inside the RouterModify_Router_StaticRoutes_Nexthop as the provided RouterIpAddress
func (t *RouterModify_Router_StaticRoutes_Nexthop) FromRouterIpAddress(v RouterIpAddress) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRouterIpAddress performs a merge with any union data inside the RouterModify_Router_StaticRoutes_Nexthop, using the provided RouterIpAddress
func (t *RouterModify_Router_StaticRoutes_Nexthop) MergeRouterIpAddress(v RouterIpAddress) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRouterModifyRouterStaticRoutesNexthop1 returns the union data inside the RouterModify_Router_StaticRoutes_Nexthop as a RouterModifyRouterStaticRoutesNexthop1
func (t RouterModify_Router_StaticRoutes_Nexthop) AsRouterModifyRouterStaticRoutesNexthop1() (RouterModifyRouterStaticRoutesNexthop1, error) {
	var body RouterModifyRouterStaticRoutesNexthop1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRouterModifyRouterStaticRoutesNexthop1 overwrites any union data inside the RouterModify_Router_StaticRoutes_Nexthop as the provided RouterModifyRouterStaticRoutesNexthop1
func (t *RouterModify_Router_StaticRoutes_Nexthop) FromRouterModifyRouterStaticRoutesNexthop1(v RouterModifyRouterStaticRoutesNexthop1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRouterModifyRouterStaticRoutesNexthop1 performs a merge with any union data inside the RouterModify_Router_StaticRoutes_Nexthop, using the provided RouterModifyRouterStaticRoutesNexthop1
func (t *RouterModify_Router_StaticRoutes_Nexthop) MergeRouterModifyRouterStaticRoutesNexthop1(v RouterModifyRouterStaticRoutesNexthop1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RouterModify_Router_StaticRoutes_Nexthop) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RouterModify_Router_StaticRoutes_Nexthop) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsRouterIpAddress returns the union data inside the RouterRouteNexthop_Nexthop as a RouterIpAddress
func (t RouterRouteNexthop_Nexthop) AsRouterIpAddress() (RouterIpAddress, error) {
	var body RouterIpAddress
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRouterIpAddress overwrites any union data inside the RouterRouteNexthop_Nexthop as the provided RouterIpAddress
func (t *RouterRouteNexthop_Nexthop) FromRouterIpAddress(v RouterIpAddress) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRouterIpAddress performs a merge with any union data inside the RouterRouteNexthop_Nexthop, using the provided RouterIpAddress
func (t *RouterRouteNexthop_Nexthop) MergeRouterIpAddress(v RouterIpAddress) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRouterRouteNexthopNexthop1 returns the union data inside the RouterRouteNexthop_Nexthop as a RouterRouteNexthopNexthop1
func (t RouterRouteNexthop_Nexthop) AsRouterRouteNexthopNexthop1() (RouterRouteNexthopNexthop1, error) {
	var body RouterRouteNexthopNexthop1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRouterRouteNexthopNexthop1 overwrites any union data inside the RouterRouteNexthop_Nexthop as the provided RouterRouteNexthopNexthop1
func (t *RouterRouteNexthop_Nexthop) FromRouterRouteNexthopNexthop1(v RouterRouteNexthopNexthop1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRouterRouteNexthopNexthop1 performs a merge with any union data inside the RouterRouteNexthop_Nexthop, using the provided RouterRouteNexthopNexthop1
func (t *RouterRouteNexthop_Nexthop) MergeRouterRouteNexthopNexthop1(v RouterRouteNexthopNexthop1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RouterRouteNexthop_Nexthop) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RouterRouteNexthop_Nexthop) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
