// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	"encoding/json"
	"fmt"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ServerAccess.
const (
	ServerAccessPrivate ServerAccess = "private"
	ServerAccessPublic  ServerAccess = "public"
	ServerAccessUtility ServerAccess = "utility"
)

// Valid indicates whether the value is a known member of the ServerAccess enum.
func (e ServerAccess) Valid() bool {
	switch e {
	case ServerAccessPrivate:
		return true
	case ServerAccessPublic:
		return true
	case ServerAccessUtility:
		return true
	default:
		return false
	}
}

// Defines values for ServerBooleanOnoff.
const (
	ServerBooleanOnoffOff ServerBooleanOnoff = "off"
	ServerBooleanOnoffOn  ServerBooleanOnoff = "on"
)

// Valid indicates whether the value is a known member of the ServerBooleanOnoff enum.
func (e ServerBooleanOnoff) Valid() bool {
	switch e {
	case ServerBooleanOnoffOff:
		return true
	case ServerBooleanOnoffOn:
		return true
	default:
		return false
	}
}

// Defines values for ServerBooleanYesno.
const (
	ServerBooleanYesnoNo  ServerBooleanYesno = "no"
	ServerBooleanYesnoYes ServerBooleanYesno = "yes"
)

// Valid indicates whether the value is a known member of the ServerBooleanYesno enum.
func (e ServerBooleanYesno) Valid() bool {
	switch e {
	case ServerBooleanYesnoNo:
		return true
	case ServerBooleanYesnoYes:
		return true
	default:
		return false
	}
}

// Defines values for ServerError400ErrorCode.
const (
	ServerError400ErrorCodeASYNCINVALID                 ServerError400ErrorCode = "ASYNC_INVALID"
	ServerError400ErrorCodeBACKUPDELETIONPOLICYINVALID  ServerError400ErrorCode = "BACKUP_DELETION_POLICY_INVALID"
	ServerError400ErrorCodeDEVICESNOTAVAILABLE          ServerError400ErrorCode = "DEVICES_NOT_AVAILABLE"
	ServerError400ErrorCodeDEVICESREQUIREHOST           ServerError400ErrorCode = "DEVICES_REQUIRE_HOST"
	ServerError400ErrorCodeINVALIDDEVICEFILTER          ServerError400ErrorCode = "INVALID_DEVICE_FILTER"
	ServerError400ErrorCodeINVALIDDEVICEFILTERKEY       ServerError400ErrorCode = "INVALID_DEVICE_FILTER_KEY"
	ServerError400ErrorCodeINVALIDDEVICEFILTERTYPEVALUE ServerError400ErrorCode = "INVALID_DEVICE_FILTER_TYPE_VALUE"
	ServerError400ErrorCodeINVALIDDEVICEFILTERVALUE     ServerError400ErrorCode = "INVALID_DEVICE_FILTER_VALUE"
	ServerError400ErrorCodeINVALIDHOSTID                ServerError400ErrorCode = "INVALID_HOST_ID"
	ServerError400ErrorCodeINVALIDORDERBY               ServerError400ErrorCode = "INVALID_ORDER_BY"
	ServerError400ErrorCodeINVALIDSEARCH                ServerError400ErrorCode = "INVALID_SEARCH"
	ServerError400ErrorCodeREQUESTINVALID               ServerError400ErrorCode = "REQUEST_INVALID"
	ServerError400ErrorCodeSERVERINVALID                ServerError400ErrorCode = "SERVER_INVALID"
	ServerError400ErrorCodeSTORAGEDELETIONPOLICYINVALID ServerError400ErrorCode = "STORAGE_DELETION_POLICY_INVALID"
)

// Valid indicates whether the value is a known member of the ServerError400ErrorCode enum.
func (e ServerError400ErrorCode) Valid() bool {
	switch e {
	case ServerError400ErrorCodeASYNCINVALID:
		return true
	case ServerError400ErrorCodeBACKUPDELETIONPOLICYINVALID:
		return true
	case ServerError400ErrorCodeDEVICESNOTAVAILABLE:
		return true
	case ServerError400ErrorCodeDEVICESREQUIREHOST:
		return true
	case ServerError400ErrorCodeINVALIDDEVICEFILTER:
		return true
	case ServerError400ErrorCodeINVALIDDEVICEFILTERKEY:
		return true
	case ServerError400ErrorCodeINVALIDDEVICEFILTERTYPEVALUE:
		return true
	case ServerError400ErrorCodeINVALIDDEVICEFILTERVALUE:
		return true
	case ServerError400ErrorCodeINVALIDHOSTID:
		return true
	case ServerError400ErrorCodeINVALIDORDERBY:
		return true
	case ServerError400ErrorCodeINVALIDSEARCH:
		return true
	case ServerError400ErrorCodeREQUESTINVALID:
		return true
	case ServerError400ErrorCodeSERVERINVALID:
		return true
	case ServerError400ErrorCodeSTORAGEDELETIONPOLICYINVALID:
		return true
	default:
		return false
	}
}

// Defines values for ServerError403ErrorCode.
const (
	ServerError403ErrorCodeSERVERFORBIDDEN ServerError403ErrorCode = "SERVER_FORBIDDEN"
)

// Valid indicates whether the value is a known member of the ServerError403ErrorCode enum.
func (e ServerError403ErrorCode) Valid() bool {
	switch e {
	case ServerError403ErrorCodeSERVERFORBIDDEN:
		return true
	default:
		return false
	}
}

// Defines values for ServerError404ErrorCode.
const (
	ServerError404ErrorCodeDEVICENOTFOUND ServerError404ErrorCode = "DEVICE_NOT_FOUND"
	ServerError404ErrorCodeSERVERNOTFOUND ServerError404ErrorCode = "SERVER_NOT_FOUND"
)

// Valid indicates whether the value is a known member of the ServerError404ErrorCode enum.
func (e ServerError404ErrorCode) Valid() bool {
	switch e {
	case ServerError404ErrorCodeDEVICENOTFOUND:
		return true
	case ServerError404ErrorCodeSERVERNOTFOUND:
		return true
	default:
		return false
	}
}

// Defines values for ServerError409ErrorCode.
const (
	ServerError409ErrorCodeDEVICEALLOCATIONFAILED   ServerError409ErrorCode = "DEVICE_ALLOCATION_FAILED"
	ServerError409ErrorCodeDEVICEDISABLED           ServerError409ErrorCode = "DEVICE_DISABLED"
	ServerError409ErrorCodeDEVICEFILTERLIMITREACHED ServerError409ErrorCode = "DEVICE_FILTER_LIMIT_REACHED"
	ServerError409ErrorCodeDEVICEHOSTMISMATCH       ServerError409ErrorCode = "DEVICE_HOST_MISMATCH"
	ServerError409ErrorCodeDEVICEUNAVAILABLE        ServerError409ErrorCode = "DEVICE_UNAVAILABLE"
	ServerError409ErrorCodeINVALIDUUID              ServerError409ErrorCode = "INVALID_UUID"
	ServerError409ErrorCodeUUIDFILTERLIMITREACHED   ServerError409ErrorCode = "UUID_FILTER_LIMIT_REACHED"
)

// Valid indicates whether the value is a known member of the ServerError409ErrorCode enum.
func (e ServerError409ErrorCode) Valid() bool {
	switch e {
	case ServerError409ErrorCodeDEVICEALLOCATIONFAILED:
		return true
	case ServerError409ErrorCodeDEVICEDISABLED:
		return true
	case ServerError409ErrorCodeDEVICEFILTERLIMITREACHED:
		return true
	case ServerError409ErrorCodeDEVICEHOSTMISMATCH:
		return true
	case ServerError409ErrorCodeDEVICEUNAVAILABLE:
		return true
	case ServerError409ErrorCodeINVALIDUUID:
		return true
	case ServerError409ErrorCodeUUIDFILTERLIMITREACHED:
		return true
	default:
		return false
	}
}

// Defines values for ServerIpFamily.
const (
	ServerIpFamilyIPv4 ServerIpFamily = "IPv4"
	ServerIpFamilyIPv6 ServerIpFamily = "IPv6"
)

// Valid indicates whether the value is a known member of the ServerIpFamily enum.
func (e ServerIpFamily) Valid() bool {
	switch e {
	case ServerIpFamilyIPv4:
		return true
	case ServerIpFamilyIPv6:
		return true
	default:
		return false
	}
}

// Defines values for ServerIpReleasePolicy.
const (
	ServerIpReleasePolicyKeep    ServerIpReleasePolicy = "keep"
	ServerIpReleasePolicyRelease ServerIpReleasePolicy = "release"
)

// Valid indicates whether the value is a known member of the ServerIpReleasePolicy enum.
func (e ServerIpReleasePolicy) Valid() bool {
	switch e {
	case ServerIpReleasePolicyKeep:
		return true
	case ServerIpReleasePolicyRelease:
		return true
	default:
		return false
	}
}

// Defines values for ServerNetworkType.
const (
	ServerNetworkTypePrivate ServerNetworkType = "private"
	ServerNetworkTypePublic  ServerNetworkType = "public"
	ServerNetworkTypeUtility ServerNetworkType = "utility"
)

// Valid indicates whether the value is a known member of the ServerNetworkType enum.
func (e ServerNetworkType) Valid() bool {
	switch e {
	case ServerNetworkTypePrivate:
		return true
	case ServerNetworkTypePublic:
		return true
	case ServerNetworkTypeUtility:
		return true
	default:
		return false
	}
}

// Defines values for ServerNicModel.
const (
	ServerNicModelE1000   ServerNicModel = "e1000"
	ServerNicModelRtl8139 ServerNicModel = "rtl8139"
	ServerNicModelVirtio  ServerNicModel = "virtio"
)

// Valid indicates whether the value is a known member of the ServerNicModel enum.
func (e ServerNicModel) Valid() bool {
	switch e {
	case ServerNicModelE1000:
		return true
	case ServerNicModelRtl8139:
		return true
	case ServerNicModelVirtio:
		return true
	default:
		return false
	}
}

// Defines values for ServerOsType.
const (
	ServerOsTypeCentos      ServerOsType = "centos"
	ServerOsTypeCoreos      ServerOsType = "coreos"
	ServerOsTypeDebian      ServerOsType = "debian"
	ServerOsTypeFedora      ServerOsType = "fedora"
	ServerOsTypeUbuntu      ServerOsType = "ubuntu"
	ServerOsTypeUnknown     ServerOsType = "unknown"
	ServerOsTypeWindows2003 ServerOsType = "windows2003"
	ServerOsTypeWindows2008 ServerOsType = "windows2008"
	ServerOsTypeWindows2012 ServerOsType = "windows2012"
)

// Valid indicates whether the value is a known member of the ServerOsType enum.
func (e ServerOsType) Valid() bool {
	switch e {
	case ServerOsTypeCentos:
		return true
	case ServerOsTypeCoreos:
		return true
	case ServerOsTypeDebian:
		return true
	case ServerOsTypeFedora:
		return true
	case ServerOsTypeUbuntu:
		return true
	case ServerOsTypeUnknown:
		return true
	case ServerOsTypeWindows2003:
		return true
	case ServerOsTypeWindows2008:
		return true
	case ServerOsTypeWindows2012:
		return true
	default:
		return false
	}
}

// Defines values for ServerState.
const (
	ServerStateError         ServerState = "error"
	ServerStateMaintenance   ServerState = "maintenance"
	ServerStatePendingDelete ServerState = "pending_delete"
	ServerStateStarted       ServerState = "started"
	ServerStateStopped       ServerState = "stopped"
)

// Valid indicates whether the value is a known member of the ServerState enum.
func (e ServerState) Valid() bool {
	switch e {
	case ServerStateError:
		return true
	case ServerStateMaintenance:
		return true
	case ServerStatePendingDelete:
		return true
	case ServerStateStarted:
		return true
	case ServerStateStopped:
		return true
	default:
		return false
	}
}

// CreateServer Server creation parameters
type CreateServer struct {
	Server struct {
		// AvoidHost Encoded host id
		AvoidHost *ServerEncodedHostId `json:"avoid_host,omitempty"`

		// BootOrder Boot device order (comma-separated list)
		BootOrder *ServerBootOrder `json:"boot_order,omitempty"`

		// CloneSource UUID of server or storage to clone from
		CloneSource *ServerCloneSource `json:"clone_source,omitempty"`

		// CoreNumber Number of CPU cores
		CoreNumber *ServerCoreNumber `json:"core_number,omitempty"`

		// Firewall Boolean value represented as on/off
		Firewall *ServerBooleanOnoff `json:"firewall,omitempty"`

		// Host Encoded host id
		Host *ServerEncodedHostId `json:"host,omitempty"`

		// Hostname Server hostname
		Hostname ServerHostname `json:"hostname"`

		// IpAddresses IP addresses assigned to the server
		IpAddresses *ServerIpAddresses `json:"ip_addresses,omitempty"`

		// Labels Server labels
		Labels *ServerLabels `json:"labels,omitempty"`

		// LoginUser Login user configuration for server creation
		LoginUser *ServerLoginUser `json:"login_user,omitempty"`

		// MemoryAmount Amount of memory in MB
		MemoryAmount *ServerMemoryAmount `json:"memory_amount,omitempty"`

		// Networking Network configuration for the server
		Networking *ServerNetworking `json:"networking,omitempty"`

		// NicModel Network interface card model
		NicModel *ServerNicModel `json:"nic_model,omitempty"`

		// PasswordDelivery Password delivery method
		PasswordDelivery *ServerPasswordDelivery `json:"password_delivery,omitempty"`

		// Plan Server plan name
		Plan *ServerPlan `json:"plan,omitempty"`

		// ServerGroup UUID string or null
		ServerGroup *ServerServerGroup `json:"server_group,omitempty"`

		// SimpleBackup HHMM, with dailies, weeklies, or monthlies option separated by comma, or no
		SimpleBackup *ServerSimpleBackup `json:"simple_backup,omitempty"`

		// StorageDevices Storage devices attached to the server
		StorageDevices ServerStorageDevices `json:"storage_devices"`

		// StorageSizeFactor Storage size multiplication factor
		StorageSizeFactor *ServerStorageSizeFactor `json:"storage_size_factor,omitempty"`

		// Timezone Server timezone
		Timezone *ServerTimezone `json:"timezone,omitempty"`

		// Title Server title
		Title ServerTitle `json:"title"`

		// UserData User data (cloud-init script) to run on server creation
		UserData *ServerUserData `json:"user_data,omitempty"`

		// VideoModel Video adapter model
		VideoModel *ServerVideoModel `json:"video_model,omitempty"`

		// Vnc VNC enabled status (yes/no)
		Vnc *ServerVnc `json:"vnc,omitempty"`

		// VncKeymap VNC keyboard layout
		VncKeymap *ServerVncKeymap `json:"vnc_keymap,omitempty"`

		// VncPassword VNC password
		VncPassword *ServerVncPassword `json:"vnc_password,omitempty"`

		// Zone Zone identifier
		Zone ServerZone `json:"zone"`
	} `json:"server"`
}

// CreateServerResponse Response schema for creating a server
type CreateServerResponse struct {
	Server struct {
		// AvoidHost Encoded host id
		AvoidHost   *ServerEncodedHostId `json:"avoid_host,omitempty"`
		BootOrder   *string              `json:"boot_order,omitempty"`
		CloneSource *string              `json:"clone_source,omitempty"`
		CoreNumber  *string              `json:"core_number,omitempty"`

		// Firewall Boolean value represented as on/off
		Firewall *ServerBooleanOnoff `json:"firewall,omitempty"`

		// Host Encoded host id
		Host        *ServerEncodedHostId `json:"host,omitempty"`
		Hostname    string               `json:"hostname"`
		IpAddresses *struct {
			IpAddress []struct {
				// Access Network access level
				Access ServerAccess   `json:"access"`
				Family ServerIpFamily `json:"family"`
				VlanId *string        `json:"vlan_id,omitempty"`
			} `json:"ip_address"`
		} `json:"ip_addresses,omitempty"`
		Labels *struct {
			Label *[]ServerLabel `json:"label,omitempty"`
		} `json:"labels,omitempty"`
		LoginUser *struct {
			// CreatePassword Boolean value represented as yes/no
			CreatePassword *ServerBooleanYesno `json:"create_password,omitempty"`
			SshKeys        *struct {
				SshKey *[]string `json:"ssh_key,omitempty"`
			} `json:"ssh_keys,omitempty"`
			Username *string `json:"username,omitempty"`
		} `json:"login_user,omitempty"`
		MemoryAmount *string `json:"memory_amount,omitempty"`

		// Networking Network configuration for the server
		Networking *ServerNetworking `json:"networking,omitempty"`

		// NicModel Network interface card model
		NicModel         *ServerNicModel `json:"nic_model,omitempty"`
		Password         *string         `json:"password,omitempty"`
		PasswordDelivery *string         `json:"password_delivery,omitempty"`

		// Plan Server plan identifier
		Plan *ServerPlanName `json:"plan,omitempty"`

		// ServerGroup UUID string or null
		ServerGroup *ServerServerGroup `json:"server_group,omitempty"`

		// SimpleBackup HHMM, with dailies, weeklies, or monthlies option separated by comma, or no
		SimpleBackup   *ServerSimpleBackup `json:"simple_backup,omitempty"`
		StorageDevices struct {
			StorageDevice *[]struct {
				Action     *string `json:"action,omitempty"`
				Address    *string `json:"address,omitempty"`
				BackupRule *string `json:"backup_rule,omitempty"`
				Size       *string `json:"size,omitempty"`
				Storage    *string `json:"storage,omitempty"`
				Tier       *string `json:"tier,omitempty"`
				Title      *string `json:"title,omitempty"`
				Type       *string `json:"type,omitempty"`
			} `json:"storage_device,omitempty"`
		} `json:"storage_devices"`
		StorageSizeFactor *string `json:"storage_size_factor,omitempty"`
		Timezone          *string `json:"timezone,omitempty"`
		Title             string  `json:"title"`
		UserData          *string `json:"user_data,omitempty"`
		VideoModel        *string `json:"video_model,omitempty"`
		Vnc               *string `json:"vnc,omitempty"`
		VncKeymap         *string `json:"vnc_keymap,omitempty"`
		VncPassword       *string `json:"vnc_password,omitempty"`

		// Zone Zone identifier
		Zone ServerZone `json:"zone"`
	} `json:"server"`
}

// Server Server object returned in responses
type Server struct {
	// Server Detailed information about a server
	Server ServerDetails `json:"server"`
}

// ServerAccess Network access level
type ServerAccess string

// ServerBooleanOnoff Boolean value represented as on/off
type ServerBooleanOnoff string

// ServerBooleanYesno Boolean value represented as yes/no
type ServerBooleanYesno string

// ServerBootOrder Boot device order (comma-separated list)
type ServerBootOrder = string

// ServerCloneSource UUID of server or storage to clone from
type ServerCloneSource = string

// ServerCoreNumber Number of CPU cores
type ServerCoreNumber = int32

// ServerCreated Creation timestamp (Unix epoch time)
type ServerCreated = int64

// ServerDetails Detailed information about a server
type ServerDetails struct {
	// BootOrder Boot device order (comma-separated list)
	BootOrder *ServerBootOrder `json:"boot_order,omitempty"`

	// CoreNumber Number of CPU cores
	CoreNumber ServerCoreNumber `json:"core_number"`

	// Created Creation timestamp (Unix epoch time)
	Created ServerCreated `json:"created"`

	// Firewall Boolean value represented as on/off
	Firewall *ServerBooleanOnoff `json:"firewall,omitempty"`

	// Host Encoded host id
	Host     *ServerEncodedHostId `json:"host,omitempty"`
	Hostname string               `json:"hostname"`
	Labels   *struct {
		Label *[]ServerLabel `json:"label,omitempty"`
	} `json:"labels,omitempty"`

	// License License type
	License int64 `json:"license"`

	// MemoryAmount Amount of memory in MB
	MemoryAmount ServerMemoryAmount `json:"memory_amount"`

	// NicModel Network interface card model
	NicModel *ServerNicModel `json:"nic_model,omitempty"`

	// OsType Operating system type
	OsType *ServerOsType `json:"os_type,omitempty"`

	// Password Only present on server create
	Password *string `json:"password,omitempty"`

	// Plan Server plan identifier
	Plan *ServerPlanName `json:"plan,omitempty"`

	// PlanIpv4Bytes Plan IPv4 traffic limit in bytes
	PlanIpv4Bytes *int64 `json:"plan_ipv4_bytes,omitempty"`

	// PlanIpv6Bytes Plan IPv6 traffic limit in bytes
	PlanIpv6Bytes *int64 `json:"plan_ipv6_bytes,omitempty"`

	// Progress TODO
	Progress *string `json:"progress,omitempty"`

	// ServerGroup UUID string or null
	ServerGroup *ServerServerGroup `json:"server_group,omitempty"`

	// SimpleBackup HHMM, with dailies, weeklies, or monthlies option separated by comma, or no
	SimpleBackup *ServerSimpleBackup `json:"simple_backup,omitempty"`

	// State Current state of the server
	State ServerState `json:"state"`

	// Tags tags can be an empty array or an object with a tag array
	Tags *ServerTags `json:"tags,omitempty"`

	// Timezone TODO
	Timezone *string `json:"timezone,omitempty"`
	Title    string  `json:"title"`

	// Username Username for an account.
	Username *ServerUserName `json:"username,omitempty"`

	// Uuid Universally unique identifier
	Uuid ServerUuid `json:"uuid"`

	// Zone Zone identifier
	Zone                 ServerZone             `json:"zone"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// ServerEncodedHostId Encoded host id
type ServerEncodedHostId = int64

// ServerError A general error response indicating that the request could not be fulfilled due to a technical issue.
type ServerError struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// ServerError400 Bad request error
type ServerError400 struct {
	Error struct {
		Code    ServerError400ErrorCode `json:"code"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ServerError400ErrorCode defines model for ServerError400.Error.Code.
type ServerError400ErrorCode string

// ServerError403 Forbidden error
type ServerError403 struct {
	Error struct {
		Code    ServerError403ErrorCode `json:"code"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ServerError403ErrorCode defines model for ServerError403.Error.Code.
type ServerError403ErrorCode string

// ServerError404 defines model for serverError404.
type ServerError404 struct {
	Error struct {
		Code    ServerError404ErrorCode `json:"code"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ServerError404ErrorCode defines model for ServerError404.Error.Code.
type ServerError404ErrorCode string

// ServerError409 Conflict error
type ServerError409 struct {
	Error struct {
		Code    ServerError409ErrorCode `json:"code"`
		Message string                  `json:"message"`
	} `json:"error"`
}

// ServerError409ErrorCode defines model for ServerError409.Error.Code.
type ServerError409ErrorCode string

// ServerHostname Server hostname
type ServerHostname = string

// ServerInterface Network interface
type ServerInterface struct {
	// Bootable Boolean value represented as yes/no
	Bootable    *ServerBooleanYesno `json:"bootable,omitempty"`
	Index       *int32              `json:"index,omitempty"`
	IpAddresses *struct {
		IpAddress []ServerInterfaceIpAddress `json:"ip_address"`
	} `json:"ip_addresses,omitempty"`

	// Mac MAC address
	Mac *ServerMacAddress `json:"mac,omitempty"`

	// Network Universally unique identifier
	Network ServerUuid `json:"network"`

	// SourceIpFiltering Boolean value represented as yes/no
	SourceIpFiltering *ServerBooleanYesno `json:"source_ip_filtering,omitempty"`

	// Type Network access type
	Type *ServerNetworkType `json:"type,omitempty"`
}

// ServerInterfaceIpAddress Network interface IP address
type ServerInterfaceIpAddress struct {
	// Address IP address
	Address ServerIpAddress `json:"address"`

	// DhcpProvided Boolean value represented as yes/no
	DhcpProvided *ServerBooleanYesno `json:"dhcp_provided,omitempty"`
	Family       ServerIpFamily      `json:"family"`

	// Floating Boolean value represented as yes/no
	Floating ServerBooleanYesno `json:"floating"`

	// ReleasePolicy IP Release policy defines what happens to the address when the referencing resource is deleted
	ReleasePolicy *ServerIpReleasePolicy `json:"release_policy,omitempty"`
}

// ServerIpAddress IP address
type ServerIpAddress struct {
	union json.RawMessage
}

// ServerIpAddress0 IPv4 address
type ServerIpAddress0 = string

// ServerIpAddress1 IPv6 address
type ServerIpAddress1 = string

// ServerIpAddresses IP addresses assigned to the server
type ServerIpAddresses struct {
	IpAddress []struct {
		// Access Network access type
		Access ServerNetworkType `json:"access"`
		Family ServerIpFamily    `json:"family"`
		VlanId *string           `json:"vlan_id,omitempty"`
	} `json:"ip_address"`
}

// ServerIpFamily defines model for serverIpFamily.
type ServerIpFamily string

// ServerIpReleasePolicy IP Release policy defines what happens to the address when the referencing resource is deleted
type ServerIpReleasePolicy string

// ServerLabel A key/value pair to label and categorize resources
type ServerLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// ServerLabels Server labels
type ServerLabels struct {
	Label *[]ServerLabel `json:"label,omitempty"`
}

// ServerLoginUser Login user configuration for server creation
type ServerLoginUser struct {
	// CreatePassword Boolean value represented as yes/no
	CreatePassword *ServerBooleanYesno `json:"create_password,omitempty"`
	SshKeys        *struct {
		SshKey *[]string `json:"ssh_key,omitempty"`
	} `json:"ssh_keys,omitempty"`
	Username *string `json:"username,omitempty"`
}

// ServerMacAddress MAC address
type ServerMacAddress = string

// ServerMemoryAmount Amount of memory in MB
type ServerMemoryAmount = int32

// ServerNetworkType Network access type
type ServerNetworkType string

// ServerNetworking Network configuration for the server
type ServerNetworking struct {
	Interfaces *struct {
		Interface []ServerInterface `json:"interface"`
	} `json:"interfaces,omitempty"`
}

// ServerNicModel Network interface card model
type ServerNicModel string

// ServerOsType Operating system type
type ServerOsType string

// ServerPasswordDelivery Password delivery method
type ServerPasswordDelivery = string

// ServerPlan Server plan name
type ServerPlan = string

// ServerPlanName Server plan identifier
type ServerPlanName = string

// ServerServerGroup UUID string or null
type ServerServerGroup = string

// ServerSimpleBackup HHMM, with dailies, weeklies, or monthlies option separated by comma, or no
type ServerSimpleBackup = string

// ServerState Current state of the server
type ServerState string

// ServerStorageDevices Storage devices attached to the server
type ServerStorageDevices struct {
	StorageDevice *[]struct {
		Action     *string `json:"action,omitempty"`
		Address    *string `json:"address,omitempty"`
		BackupRule *string `json:"backup_rule,omitempty"`
		Size       *string `json:"size,omitempty"`
		Storage    *string `json:"storage,omitempty"`
		Tier       *string `json:"tier,omitempty"`
		Title      *string `json:"title,omitempty"`
		Type       *string `json:"type,omitempty"`
	} `json:"storage_device,omitempty"`
}

// ServerStorageSizeFactor Storage size multiplication factor
type ServerStorageSizeFactor = string

// ServerTags tags can be an empty array or an object with a tag array
type ServerTags struct {
	union json.RawMessage
}

// ServerTags0 defines model for .
type ServerTags0 = []interface{}

// ServerTags1 defines model for .
type ServerTags1 struct {
	Tag []string `json:"tag"`
}

// ServerTimezone Server timezone
type ServerTimezone = string

// ServerTitle Server title
type ServerTitle = string

// ServerUserData User data (cloud-init script) to run on server creation
type ServerUserData = string

// ServerUserName Username for an account.
type ServerUserName = string

// ServerUuid Universally unique identifier
type ServerUuid = openapi_types.UUID

// ServerVideoModel Video adapter model
type ServerVideoModel = string

// ServerVnc VNC enabled status (yes/no)
type ServerVnc = string

// ServerVncKeymap VNC keyboard layout
type ServerVncKeymap = string

// ServerVncPassword VNC password
type ServerVncPassword = string

// ServerZone Zone identifier
type ServerZone = string

// CreateServer202 Response schema for creating a server
type CreateServer202 = CreateServerResponse

// CreateServer400 Bad request error
type CreateServer400 = ServerError400

// CreateServer403 Forbidden error
type CreateServer403 = ServerError403

// CreateServer404 defines model for createServer404.
type CreateServer404 = ServerError404

// CreateServer409 Conflict error
type CreateServer409 = ServerError409

// CreateServerDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateServerDefault = ServerError

// ModifyServer202 Server object returned in responses
type ModifyServer202 = Server

// ModifyServer400 Bad request error
type ModifyServer400 = ServerError400

// ModifyServer403 Forbidden error
type ModifyServer403 = ServerError403

// ModifyServer409 Conflict error
type ModifyServer409 = ServerError409

// ModifyServerDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyServerDefault = ServerError

// CreateServerRequestBody Server creation parameters
type CreateServerRequestBody = CreateServer

// ModifyServer Server object returned in responses
type ModifyServer = Server

// CreateServerJSONRequestBody defines body for CreateServer for application/json ContentType.
type CreateServerJSONRequestBody = CreateServer

// ModifyServerJSONRequestBody defines body for ModifyServer for application/json ContentType.
type ModifyServerJSONRequestBody = Server

// Getter for additional properties for ServerDetails. Returns the specified
// element and whether it was found
func (a ServerDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ServerDetails
func (a *ServerDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ServerDetails to handle AdditionalProperties
func (a *ServerDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["boot_order"]; found {
		err = json.Unmarshal(raw, &a.BootOrder)
		if err != nil {
			return fmt.Errorf("error reading 'boot_order': %w", err)
		}
		delete(object, "boot_order")
	}

	if raw, found := object["core_number"]; found {
		err = json.Unmarshal(raw, &a.CoreNumber)
		if err != nil {
			return fmt.Errorf("error reading 'core_number': %w", err)
		}
		delete(object, "core_number")
	}

	if raw, found := object["created"]; found {
		err = json.Unmarshal(raw, &a.Created)
		if err != nil {
			return fmt.Errorf("error reading 'created': %w", err)
		}
		delete(object, "created")
	}

	if raw, found := object["firewall"]; found {
		err = json.Unmarshal(raw, &a.Firewall)
		if err != nil {
			return fmt.Errorf("error reading 'firewall': %w", err)
		}
		delete(object, "firewall")
	}

	if raw, found := object["host"]; found {
		err = json.Unmarshal(raw, &a.Host)
		if err != nil {
			return fmt.Errorf("error reading 'host': %w", err)
		}
		delete(object, "host")
	}

	if raw, found := object["hostname"]; found {
		err = json.Unmarshal(raw, &a.Hostname)
		if err != nil {
			return fmt.Errorf("error reading 'hostname': %w", err)
		}
		delete(object, "hostname")
	}

	if raw, found := object["labels"]; found {
		err = json.Unmarshal(raw, &a.Labels)
		if err != nil {
			return fmt.Errorf("error reading 'labels': %w", err)
		}
		delete(object, "labels")
	}

	if raw, found := object["license"]; found {
		err = json.Unmarshal(raw, &a.License)
		if err != nil {
			return fmt.Errorf("error reading 'license': %w", err)
		}
		delete(object, "license")
	}

	if raw, found := object["memory_amount"]; found {
		err = json.Unmarshal(raw, &a.MemoryAmount)
		if err != nil {
			return fmt.Errorf("error reading 'memory_amount': %w", err)
		}
		delete(object, "memory_amount")
	}

	if raw, found := object["nic_model"]; found {
		err = json.Unmarshal(raw, &a.NicModel)
		if err != nil {
			return fmt.Errorf("error reading 'nic_model': %w", err)
		}
		delete(object, "nic_model")
	}

	if raw, found := object["os_type"]; found {
		err = json.Unmarshal(raw, &a.OsType)
		if err != nil {
			return fmt.Errorf("error reading 'os_type': %w", err)
		}
		delete(object, "os_type")
	}

	if raw, found := object["password"]; found {
		err = json.Unmarshal(raw, &a.Password)
		if err != nil {
			return fmt.Errorf("error reading 'password': %w", err)
		}
		delete(object, "password")
	}

	if raw, found := object["plan"]; found {
		err = json.Unmarshal(raw, &a.Plan)
		if err != nil {
			return fmt.Errorf("error reading 'plan': %w", err)
		}
		delete(object, "plan")
	}

	if raw, found := object["plan_ipv4_bytes"]; found {
		err = json.Unmarshal(raw, &a.PlanIpv4Bytes)
		if err != nil {
			return fmt.Errorf("error reading 'plan_ipv4_bytes': %w", err)
		}
		delete(object, "plan_ipv4_bytes")
	}

	if raw, found := object["plan_ipv6_bytes"]; found {
		err = json.Unmarshal(raw, &a.PlanIpv6Bytes)
		if err != nil {
			return fmt.Errorf("error reading 'plan_ipv6_bytes': %w", err)
		}
		delete(object, "plan_ipv6_bytes")
	}

	if raw, found := object["progress"]; found {
		err = json.Unmarshal(raw, &a.Progress)
		if err != nil {
			return fmt.Errorf("error reading 'progress': %w", err)
		}
		delete(object, "progress")
	}

	if raw, found := object["server_group"]; found {
		err = json.Unmarshal(raw, &a.ServerGroup)
		if err != nil {
			return fmt.Errorf("error reading 'server_group': %w", err)
		}
		delete(object, "server_group")
	}

	if raw, found := object["simple_backup"]; found {
		err = json.Unmarshal(raw, &a.SimpleBackup)
		if err != nil {
			return fmt.Errorf("error reading 'simple_backup': %w", err)
		}
		delete(object, "simple_backup")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["tags"]; found {
		err = json.Unmarshal(raw, &a.Tags)
		if err != nil {
			return fmt.Errorf("error reading 'tags': %w", err)
		}
		delete(object, "tags")
	}

	if raw, found := object["timezone"]; found {
		err = json.Unmarshal(raw, &a.Timezone)
		if err != nil {
			return fmt.Errorf("error reading 'timezone': %w", err)
		}
		delete(object, "timezone")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &a.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
		delete(object, "username")
	}

	if raw, found := object["uuid"]; found {
		err = json.Unmarshal(raw, &a.Uuid)
		if err != nil {
			return fmt.Errorf("error reading 'uuid': %w", err)
		}
		delete(object, "uuid")
	}

	if raw, found := object["zone"]; found {
		err = json.Unmarshal(raw, &a.Zone)
		if err != nil {
			return fmt.Errorf("error reading 'zone': %w", err)
		}
		delete(object, "zone")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ServerDetails to handle AdditionalProperties
func (a ServerDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.BootOrder != nil {
		object["boot_order"], err = json.Marshal(a.BootOrder)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'boot_order': %w", err)
		}
	}

	object["core_number"], err = json.Marshal(a.CoreNumber)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'core_number': %w", err)
	}

	object["created"], err = json.Marshal(a.Created)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'created': %w", err)
	}

	if a.Firewall != nil {
		object["firewall"], err = json.Marshal(a.Firewall)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'firewall': %w", err)
		}
	}

	if a.Host != nil {
		object["host"], err = json.Marshal(a.Host)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'host': %w", err)
		}
	}

	object["hostname"], err = json.Marshal(a.Hostname)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'hostname': %w", err)
	}

	if a.Labels != nil {
		object["labels"], err = json.Marshal(a.Labels)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'labels': %w", err)
		}
	}

	object["license"], err = json.Marshal(a.License)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'license': %w", err)
	}

	object["memory_amount"], err = json.Marshal(a.MemoryAmount)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'memory_amount': %w", err)
	}

	if a.NicModel != nil {
		object["nic_model"], err = json.Marshal(a.NicModel)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'nic_model': %w", err)
		}
	}

	if a.OsType != nil {
		object["os_type"], err = json.Marshal(a.OsType)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'os_type': %w", err)
		}
	}

	if a.Password != nil {
		object["password"], err = json.Marshal(a.Password)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'password': %w", err)
		}
	}

	if a.Plan != nil {
		object["plan"], err = json.Marshal(a.Plan)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'plan': %w", err)
		}
	}

	if a.PlanIpv4Bytes != nil {
		object["plan_ipv4_bytes"], err = json.Marshal(a.PlanIpv4Bytes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'plan_ipv4_bytes': %w", err)
		}
	}

	if a.PlanIpv6Bytes != nil {
		object["plan_ipv6_bytes"], err = json.Marshal(a.PlanIpv6Bytes)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'plan_ipv6_bytes': %w", err)
		}
	}

	if a.Progress != nil {
		object["progress"], err = json.Marshal(a.Progress)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'progress': %w", err)
		}
	}

	if a.ServerGroup != nil {
		object["server_group"], err = json.Marshal(a.ServerGroup)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'server_group': %w", err)
		}
	}

	if a.SimpleBackup != nil {
		object["simple_backup"], err = json.Marshal(a.SimpleBackup)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'simple_backup': %w", err)
		}
	}

	object["state"], err = json.Marshal(a.State)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'state': %w", err)
	}

	if a.Tags != nil {
		object["tags"], err = json.Marshal(a.Tags)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tags': %w", err)
		}
	}

	if a.Timezone != nil {
		object["timezone"], err = json.Marshal(a.Timezone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'timezone': %w", err)
		}
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	if a.Username != nil {
		object["username"], err = json.Marshal(a.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}

	object["uuid"], err = json.Marshal(a.Uuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'uuid': %w", err)
	}

	object["zone"], err = json.Marshal(a.Zone)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'zone': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsServerIpAddress0 returns the union data inside the ServerIpAddress as a ServerIpAddress0
func (t ServerIpAddress) AsServerIpAddress0() (ServerIpAddress0, error) {
	var body ServerIpAddress0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerIpAddress0 overwrites any union data inside the ServerIpAddress as the provided ServerIpAddress0
func (t *ServerIpAddress) FromServerIpAddress0(v ServerIpAddress0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerIpAddress0 performs a merge with any union data inside the ServerIpAddress, using the provided ServerIpAddress0
func (t *ServerIpAddress) MergeServerIpAddress0(v ServerIpAddress0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServerIpAddress1 returns the union data inside the ServerIpAddress as a ServerIpAddress1
func (t ServerIpAddress) AsServerIpAddress1() (ServerIpAddress1, error) {
	var body ServerIpAddress1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerIpAddress1 overwrites any union data inside the ServerIpAddress as the provided ServerIpAddress1
func (t *ServerIpAddress) FromServerIpAddress1(v ServerIpAddress1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerIpAddress1 performs a merge with any union data inside the ServerIpAddress, using the provided ServerIpAddress1
func (t *ServerIpAddress) MergeServerIpAddress1(v ServerIpAddress1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServerIpAddress) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServerIpAddress) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsServerTags0 returns the union data inside the ServerTags as a ServerTags0
func (t ServerTags) AsServerTags0() (ServerTags0, error) {
	var body ServerTags0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerTags0 overwrites any union data inside the ServerTags as the provided ServerTags0
func (t *ServerTags) FromServerTags0(v ServerTags0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerTags0 performs a merge with any union data inside the ServerTags, using the provided ServerTags0
func (t *ServerTags) MergeServerTags0(v ServerTags0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsServerTags1 returns the union data inside the ServerTags as a ServerTags1
func (t ServerTags) AsServerTags1() (ServerTags1, error) {
	var body ServerTags1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromServerTags1 overwrites any union data inside the ServerTags as the provided ServerTags1
func (t *ServerTags) FromServerTags1(v ServerTags1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeServerTags1 performs a merge with any union data inside the ServerTags, using the provided ServerTags1
func (t *ServerTags) MergeServerTags1(v ServerTags1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServerTags) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServerTags) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
