// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ServerGroupAntiAffinity.
const (
	ServerGroupAntiAffinityNo     ServerGroupAntiAffinity = "no"
	ServerGroupAntiAffinityStrict ServerGroupAntiAffinity = "strict"
	ServerGroupAntiAffinityYes    ServerGroupAntiAffinity = "yes"
)

// Valid indicates whether the value is a known member of the ServerGroupAntiAffinity enum.
func (e ServerGroupAntiAffinity) Valid() bool {
	switch e {
	case ServerGroupAntiAffinityNo:
		return true
	case ServerGroupAntiAffinityStrict:
		return true
	case ServerGroupAntiAffinityYes:
		return true
	default:
		return false
	}
}

// Defines values for ServerGroupAntiAffinityStatusStatus.
const (
	ServerGroupAntiAffinityStatusStatusMet   ServerGroupAntiAffinityStatusStatus = "met"
	ServerGroupAntiAffinityStatusStatusUnmet ServerGroupAntiAffinityStatusStatus = "unmet"
)

// Valid indicates whether the value is a known member of the ServerGroupAntiAffinityStatusStatus enum.
func (e ServerGroupAntiAffinityStatusStatus) Valid() bool {
	switch e {
	case ServerGroupAntiAffinityStatusStatusMet:
		return true
	case ServerGroupAntiAffinityStatusStatusUnmet:
		return true
	default:
		return false
	}
}

// ServerGroup A single server group
type ServerGroup struct {
	// ServerGroup Details of a server group
	ServerGroup ServerGroupDetails `json:"server_group"`
}

// ServerGroupAntiAffinity Anti-affinity policy for server groups. Possible values are 'strict', 'yes', or 'no'. 'strict' ensures that no two servers in the group are placed on the same physical host. 'yes' indicates a preference for anti-affinity but does not guarantee it. 'no' means there is no anti-affinity requirement.
type ServerGroupAntiAffinity string

// ServerGroupAntiAffinityStatus Status of anti-affinity policy
type ServerGroupAntiAffinityStatus struct {
	// Status Indicates whether the anti-affinity policy is currently being met ('met') or not ('unmet')
	Status ServerGroupAntiAffinityStatusStatus `json:"status"`

	// Uuid Universally unique identifier
	//
	// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
	Uuid ServerGroupUuid `json:"uuid"`
}

// ServerGroupAntiAffinityStatusStatus Indicates whether the anti-affinity policy is currently being met ('met') or not ('unmet')
type ServerGroupAntiAffinityStatusStatus string

// ServerGroupDetails Details of a server group
type ServerGroupDetails struct {
	// AntiAffinity Anti-affinity policy for server groups. Possible values are 'strict', 'yes', or 'no'. 'strict' ensures that no two servers in the group are placed on the same physical host. 'yes' indicates a preference for anti-affinity but does not guarantee it. 'no' means there is no anti-affinity requirement.
	AntiAffinity       ServerGroupAntiAffinity         `json:"anti_affinity"`
	AntiAffinityStatus []ServerGroupAntiAffinityStatus `json:"anti_affinity_status"`

	// Labels List of labels associated with the server group.
	Labels struct {
		Label []ServerGroupLabel `json:"label"`
	} `json:"labels"`

	// Servers List of servers associated with the server group.
	Servers struct {
		Server []ServerGroupUuid `json:"server"`
	} `json:"servers"`
	Title string `json:"title"`

	// Uuid Universally unique identifier
	//
	// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
	Uuid ServerGroupUuid `json:"uuid"`
}

// ServerGroupError A general error response indicating that the request could not be fulfilled due to a technical issue.
type ServerGroupError struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// ServerGroupLabel A key/value pair to label and categorize resources
//
// Example: {"key":"env","value":"production"}
type ServerGroupLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// ServerGroupModify A schema for creating/modifying a server group
type ServerGroupModify struct {
	ServerGroup struct {
		// AntiAffinity Anti-affinity policy for server groups. Possible values are 'strict', 'yes', or 'no'. 'strict' ensures that no two servers in the group are placed on the same physical host. 'yes' indicates a preference for anti-affinity but does not guarantee it. 'no' means there is no anti-affinity requirement.
		AntiAffinity *ServerGroupAntiAffinity `json:"anti_affinity,omitempty"`

		// Labels Labels to categorize the server group
		Labels *struct {
			Label *[]ServerGroupLabel `json:"label,omitempty"`
		} `json:"labels,omitempty"`

		// Servers List of server UUIDs in the server group
		Servers *ServerGroupServers `json:"servers,omitempty"`

		// Title The name of the server group
		Title *string `json:"title,omitempty"`
	} `json:"server_group"`
}

// ServerGroupServerAdd Schema for adding a server to a server group
type ServerGroupServerAdd struct {
	Server struct {
		// Uuid Universally unique identifier
		//
		// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
		Uuid ServerGroupUuid `json:"uuid"`
	} `json:"server"`
}

// ServerGroupServers List of server UUIDs in the server group
type ServerGroupServers struct {
	Servers []ServerGroupUuid `json:"servers"`
}

// ServerGroupUuid Universally unique identifier
//
// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
type ServerGroupUuid = openapi_types.UUID

// ServerGroups List of server groups
type ServerGroups struct {
	ServerGroups struct {
		ServerGroup []ServerGroupDetails `json:"server_group"`
	} `json:"server_groups"`
}

// DeleteServerGroupUuid Universally unique identifier
//
// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
type DeleteServerGroupUuid = ServerGroupUuid

// GetServerGroupUuid Universally unique identifier
//
// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
type GetServerGroupUuid = ServerGroupUuid

// ListServerGroupMembersUuid Universally unique identifier
//
// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
type ListServerGroupMembersUuid = ServerGroupUuid

// ListServerGroupsLabel A key/value pair to label and categorize resources
//
// Example: {"key":"env","value":"production"}
type ListServerGroupsLabel = ServerGroupLabel

// ModifyServerGroupUuid Universally unique identifier
//
// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
type ModifyServerGroupUuid = ServerGroupUuid

// ServerGroupAddServerToGroupUuid Universally unique identifier
//
// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
type ServerGroupAddServerToGroupUuid = ServerGroupUuid

// ServerGroupRemoveServerFromGroupServerUuid Universally unique identifier
//
// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
type ServerGroupRemoveServerFromGroupServerUuid = ServerGroupUuid

// ServerGroupRemoveServerFromGroupUuid Universally unique identifier
//
// Example: 0414e0d7-4436-4037-9dd8-6eaf47dce599
type ServerGroupRemoveServerFromGroupUuid = ServerGroupUuid

// CreateServerGroup200 A single server group
type CreateServerGroup200 = ServerGroup

// CreateServerGroupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateServerGroupDefault = ServerGroupError

// DeleteServerGroupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteServerGroupDefault = ServerGroupError

// GetServerGroup200 A single server group
type GetServerGroup200 = ServerGroup

// GetServerGroupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetServerGroupDefault = ServerGroupError

// ListServerGroupMembers200 List of server UUIDs in the server group
type ListServerGroupMembers200 = ServerGroupServers

// ListServerGroupMembersDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ListServerGroupMembersDefault = ServerGroupError

// ListServerGroups200 List of server groups
type ListServerGroups200 = ServerGroups

// ListServerGroupsDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ListServerGroupsDefault = ServerGroupError

// ModifyServerGroup200 A single server group
type ModifyServerGroup200 = ServerGroup

// ModifyServerGroupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyServerGroupDefault = ServerGroupError

// ServerGroupAddServerToGroupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ServerGroupAddServerToGroupDefault = ServerGroupError

// ServerGroupRemoveServerFromGroupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ServerGroupRemoveServerFromGroupDefault = ServerGroupError

// CreateServerGroup A schema for creating/modifying a server group
type CreateServerGroup = ServerGroupModify

// ModifyServerGroup A schema for creating/modifying a server group
type ModifyServerGroup = ServerGroupModify

// ServerGroupAddServerToGroup Schema for adding a server to a server group
type ServerGroupAddServerToGroup = ServerGroupServerAdd

// ListServerGroupsParams defines parameters for ListServerGroups.
type ListServerGroupsParams struct {
	// Label A label filter to apply. Format: key:value. Multiple labels can be specified by repeating the parameter.
	Label *ListServerGroupsLabel `form:"label,omitempty" json:"label,omitempty"`
}

// CreateServerGroupJSONRequestBody defines body for CreateServerGroup for application/json ContentType.
type CreateServerGroupJSONRequestBody = ServerGroupModify

// ModifyServerGroupJSONRequestBody defines body for ModifyServerGroup for application/json ContentType.
type ModifyServerGroupJSONRequestBody = ServerGroupModify

// AddServerToGroupJSONRequestBody defines body for AddServerToGroup for application/json ContentType.
type AddServerToGroupJSONRequestBody = ServerGroupServerAdd
