// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package upcloud

import (
	"encoding/json"
	"fmt"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for StorageAccess.
const (
	StorageAccessPrivate StorageAccess = "private"
	StorageAccessPublic  StorageAccess = "public"
	StorageAccessUtility StorageAccess = "utility"
)

// Valid indicates whether the value is a known member of the StorageAccess enum.
func (e StorageAccess) Valid() bool {
	switch e {
	case StorageAccessPrivate:
		return true
	case StorageAccessPublic:
		return true
	case StorageAccessUtility:
		return true
	default:
		return false
	}
}

// Defines values for StorageAccessFilter.
const (
	StorageAccessFilterPrivate StorageAccessFilter = "private"
	StorageAccessFilterPublic  StorageAccessFilter = "public"
)

// Valid indicates whether the value is a known member of the StorageAccessFilter enum.
func (e StorageAccessFilter) Valid() bool {
	switch e {
	case StorageAccessFilterPrivate:
		return true
	case StorageAccessFilterPublic:
		return true
	default:
		return false
	}
}

// Defines values for StorageAllowHidden.
const (
	StorageAllowHiddenN0  StorageAllowHidden = "0"
	StorageAllowHiddenN1  StorageAllowHidden = "1"
	StorageAllowHiddenNo  StorageAllowHidden = "no"
	StorageAllowHiddenYes StorageAllowHidden = "yes"
)

// Valid indicates whether the value is a known member of the StorageAllowHidden enum.
func (e StorageAllowHidden) Valid() bool {
	switch e {
	case StorageAllowHiddenN0:
		return true
	case StorageAllowHiddenN1:
		return true
	case StorageAllowHiddenNo:
		return true
	case StorageAllowHiddenYes:
		return true
	default:
		return false
	}
}

// Defines values for StorageDetailsPartOfPlan.
const (
	StorageDetailsPartOfPlanNo  StorageDetailsPartOfPlan = "no"
	StorageDetailsPartOfPlanYes StorageDetailsPartOfPlan = "yes"
)

// Valid indicates whether the value is a known member of the StorageDetailsPartOfPlan enum.
func (e StorageDetailsPartOfPlan) Valid() bool {
	switch e {
	case StorageDetailsPartOfPlanNo:
		return true
	case StorageDetailsPartOfPlanYes:
		return true
	default:
		return false
	}
}

// Defines values for StorageEncrypted.
const (
	StorageEncryptedNo  StorageEncrypted = "no"
	StorageEncryptedYes StorageEncrypted = "yes"
)

// Valid indicates whether the value is a known member of the StorageEncrypted enum.
func (e StorageEncrypted) Valid() bool {
	switch e {
	case StorageEncryptedNo:
		return true
	case StorageEncryptedYes:
		return true
	default:
		return false
	}
}

// Defines values for StorageFavorite.
const (
	StorageFavoriteN0  StorageFavorite = "0"
	StorageFavoriteN1  StorageFavorite = "1"
	StorageFavoriteNo  StorageFavorite = "no"
	StorageFavoriteYes StorageFavorite = "yes"
)

// Valid indicates whether the value is a known member of the StorageFavorite enum.
func (e StorageFavorite) Valid() bool {
	switch e {
	case StorageFavoriteN0:
		return true
	case StorageFavoriteN1:
		return true
	case StorageFavoriteNo:
		return true
	case StorageFavoriteYes:
		return true
	default:
		return false
	}
}

// Defines values for StorageMetadata.
const (
	StorageMetadataN0  StorageMetadata = "0"
	StorageMetadataN1  StorageMetadata = "1"
	StorageMetadataNo  StorageMetadata = "no"
	StorageMetadataYes StorageMetadata = "yes"
)

// Valid indicates whether the value is a known member of the StorageMetadata enum.
func (e StorageMetadata) Valid() bool {
	switch e {
	case StorageMetadataN0:
		return true
	case StorageMetadataN1:
		return true
	case StorageMetadataNo:
		return true
	case StorageMetadataYes:
		return true
	default:
		return false
	}
}

// Defines values for StorageOrderBy.
const (
	StorageOrderByAsc  StorageOrderBy = "asc"
	StorageOrderByDesc StorageOrderBy = "desc"
)

// Valid indicates whether the value is a known member of the StorageOrderBy enum.
func (e StorageOrderBy) Valid() bool {
	switch e {
	case StorageOrderByAsc:
		return true
	case StorageOrderByDesc:
		return true
	default:
		return false
	}
}

// Defines values for StorageServers.
const (
	StorageServersN0  StorageServers = "0"
	StorageServersN1  StorageServers = "1"
	StorageServersNo  StorageServers = "no"
	StorageServersYes StorageServers = "yes"
)

// Valid indicates whether the value is a known member of the StorageServers enum.
func (e StorageServers) Valid() bool {
	switch e {
	case StorageServersN0:
		return true
	case StorageServersN1:
		return true
	case StorageServersNo:
		return true
	case StorageServersYes:
		return true
	default:
		return false
	}
}

// Defines values for StorageSortBy.
const (
	StorageSortByCreated StorageSortBy = "created"
	StorageSortBySize    StorageSortBy = "size"
	StorageSortByTitle   StorageSortBy = "title"
	StorageSortByType    StorageSortBy = "type"
)

// Valid indicates whether the value is a known member of the StorageSortBy enum.
func (e StorageSortBy) Valid() bool {
	switch e {
	case StorageSortByCreated:
		return true
	case StorageSortBySize:
		return true
	case StorageSortByTitle:
		return true
	case StorageSortByType:
		return true
	default:
		return false
	}
}

// Defines values for StorageState.
const (
	StorageStateAttaching     StorageState = "attaching"
	StorageStateBackuping     StorageState = "backuping"
	StorageStateCloning       StorageState = "cloning"
	StorageStateDetaching     StorageState = "detaching"
	StorageStateError         StorageState = "error"
	StorageStateHidden        StorageState = "hidden"
	StorageStateMaintenance   StorageState = "maintenance"
	StorageStateOnline        StorageState = "online"
	StorageStatePendingDelete StorageState = "pending_delete"
	StorageStateSyncing       StorageState = "syncing"
)

// Valid indicates whether the value is a known member of the StorageState enum.
func (e StorageState) Valid() bool {
	switch e {
	case StorageStateAttaching:
		return true
	case StorageStateBackuping:
		return true
	case StorageStateCloning:
		return true
	case StorageStateDetaching:
		return true
	case StorageStateError:
		return true
	case StorageStateHidden:
		return true
	case StorageStateMaintenance:
		return true
	case StorageStateOnline:
		return true
	case StorageStatePendingDelete:
		return true
	case StorageStateSyncing:
		return true
	default:
		return false
	}
}

// Defines values for StorageType.
const (
	StorageTypeBackup   StorageType = "backup"
	StorageTypeCdrom    StorageType = "cdrom"
	StorageTypeNormal   StorageType = "normal"
	StorageTypeTemplate StorageType = "template"
)

// Valid indicates whether the value is a known member of the StorageType enum.
func (e StorageType) Valid() bool {
	switch e {
	case StorageTypeBackup:
		return true
	case StorageTypeCdrom:
		return true
	case StorageTypeNormal:
		return true
	case StorageTypeTemplate:
		return true
	default:
		return false
	}
}

// Defines values for DeleteStorageBackups.
const (
	DeleteStorageBackupsDelete     DeleteStorageBackups = "delete"
	DeleteStorageBackupsKeep       DeleteStorageBackups = "keep"
	DeleteStorageBackupsKeepLatest DeleteStorageBackups = "keep_latest"
)

// Valid indicates whether the value is a known member of the DeleteStorageBackups enum.
func (e DeleteStorageBackups) Valid() bool {
	switch e {
	case DeleteStorageBackupsDelete:
		return true
	case DeleteStorageBackupsKeep:
		return true
	case DeleteStorageBackupsKeepLatest:
		return true
	default:
		return false
	}
}

// Defines values for DeleteStorageParamsBackups.
const (
	DeleteStorageParamsBackupsDelete     DeleteStorageParamsBackups = "delete"
	DeleteStorageParamsBackupsKeep       DeleteStorageParamsBackups = "keep"
	DeleteStorageParamsBackupsKeepLatest DeleteStorageParamsBackups = "keep_latest"
)

// Valid indicates whether the value is a known member of the DeleteStorageParamsBackups enum.
func (e DeleteStorageParamsBackups) Valid() bool {
	switch e {
	case DeleteStorageParamsBackupsDelete:
		return true
	case DeleteStorageParamsBackupsKeep:
		return true
	case DeleteStorageParamsBackupsKeepLatest:
		return true
	default:
		return false
	}
}

// AddStorageComponentRequest Schema for adding a storage component to a storage device
type AddStorageComponentRequest struct {
	Storage struct {
		ForceBackend *string `json:"force_backend,omitempty"`
	} `json:"storage"`
}

// AttachStorage Schema for attaching a storage device to a server
type AttachStorage struct {
	StorageDevice struct {
		Address *string `json:"address,omitempty"`
		Storage *string `json:"storage,omitempty"`
		Type    *string `json:"type,omitempty"`
	} `json:"storage_device"`
}

// CloneStorageRequest TODO
type CloneStorageRequest struct {
	Storage struct {
		// Components Storage component filter or selector.
		Components *StorageComponents `json:"components,omitempty"`

		// Tier Storage tier identifier.
		Tier StorageTier `json:"tier"`

		// Title Human-readable title for a resource.
		Title StorageTitle `json:"title"`

		// Zone Zone identifier
		//
		// Examples: fi-hel1, de-fra1, us-nyc1
		Zone StorageZone `json:"zone"`
	} `json:"storage"`
}

// CreateStorageBackupRequest Backup rule configuration for storage backups.
type CreateStorageBackupRequest struct {
	Interval  string `json:"interval"`
	Retention string `json:"retention"`
	Time      string `json:"time"`
}

// CreateStorageRequest Request schema for creating a storage
type CreateStorageRequest struct {
	Storage struct {
		BackupRule *struct {
			Interval  string `json:"interval"`
			Retention string `json:"retention"`
			Time      string `json:"time"`
		} `json:"backup_rule,omitempty"`
		Components   *string `json:"components,omitempty"`
		ForceBackend *string `json:"force_backend,omitempty"`
		Size         *int64  `json:"size,omitempty"`
		SizeFactor   *string `json:"size_factor,omitempty"`
		Tier         *string `json:"tier,omitempty"`
		Title        *string `json:"title,omitempty"`

		// Uuid Universally unique identifier
		Uuid *StorageUuid `json:"uuid,omitempty"`

		// Zone Zone identifier
		//
		// Examples: fi-hel1, de-fra1, us-nyc1
		Zone *StorageZone `json:"zone,omitempty"`
	} `json:"storage"`
}

// CreateStorageResponse Created storage
type CreateStorageResponse struct {
	// Storage Detailed information about a storage resource.
	Storage StorageDetails `json:"storage"`
}

// CreateStorageTemplateRequest Request schema for creating a storage template
type CreateStorageTemplateRequest struct {
	Storage struct {
		Title string `json:"title"`
	} `json:"storage"`
}

// ModifyStorageBody Request schema for modifying storage properties.
type ModifyStorageBody struct {
	Storage struct {
		// BackupRule Backup rule configuration for storage backups.
		BackupRule         *CreateStorageBackupRequest `json:"backup_rule,omitempty"`
		FilesystemResize   *string                     `json:"filesystem_resize,omitempty"`
		FlushNormalLabels  *string                     `json:"flush_normal_labels,omitempty"`
		OsType             *string                     `json:"os_type,omitempty"`
		PartitionTableType *string                     `json:"partition_table_type,omitempty"`
		Size               *int64                      `json:"size,omitempty"`
		SizeFactor         *int64                      `json:"size_factor,omitempty"`
		TemplateType       *string                     `json:"template_type,omitempty"`
		Title              *string                     `json:"title,omitempty"`
	} `json:"storage"`
}

// ModifyStorageResponse Response schema for storage modification operations.
type ModifyStorageResponse struct {
	// Storage Detailed information about a storage resource.
	Storage StorageDetails `json:"storage"`
}

// ResizeStorageResponse Response schema for resizing a storage volume.
type ResizeStorageResponse struct {
	// Storage Detailed information about a storage resource.
	Storage StorageDetails `json:"storage"`
}

// Storage Response schema containing a single storage resource.
type Storage struct {
	// Storage Detailed information about a storage resource.
	Storage StorageDetails `json:"storage"`
}

// StorageAccess Network access level
type StorageAccess string

// StorageAccessFilter Storage access level filter
type StorageAccessFilter string

// StorageAllowHidden Whether to include hidden storages in the response
//
// Examples: yes, no
type StorageAllowHidden string

// StorageComponents Storage component filter or selector.
type StorageComponents = string

// StorageCreateCdromRequest Schema for creating a new CD-ROM image
type StorageCreateCdromRequest struct {
	CreateCdrom struct {
		Access            *string `json:"access,omitempty"`
		Architecture      *string `json:"architecture,omitempty"`
		Category          *string `json:"category,omitempty"`
		DefaultDiskBus    *string `json:"default_disk_bus,omitempty"`
		DefaultNicModel   *string `json:"default_nic_model,omitempty"`
		DefaultVideoModel *string `json:"default_video_model,omitempty"`
		DescriptionEn     *string `json:"description_en,omitempty"`
		DescriptionFi     *string `json:"description_fi,omitempty"`
		Md5sum            *string `json:"md5sum,omitempty"`
		Owner             *string `json:"owner,omitempty"`
		Title             *string `json:"title,omitempty"`
		Url               *string `json:"url,omitempty"`

		// Uuid Universally unique identifier
		Uuid *StorageUuid `json:"uuid,omitempty"`

		// Zone Zone identifier
		//
		// Examples: fi-hel1, de-fra1, us-nyc1
		Zone *StorageZone `json:"zone,omitempty"`
	} `json:"create_cdrom"`
}

// StorageDetails Detailed information about a storage resource.
type StorageDetails struct {
	// Access Network access level
	Access StorageAccess `json:"access"`

	// Encrypted Indicates whether the resource is encrypted.
	//
	// Examples: yes, no
	Encrypted StorageEncrypted `json:"encrypted"`
	Labels    *[]StorageLabel  `json:"labels,omitempty"`
	License   float64          `json:"license"`

	// Metadata Only available with "metadata" in Options
	Metadata   *map[string]string        `json:"metadata,omitempty"`
	PartOfPlan *StorageDetailsPartOfPlan `json:"part_of_plan,omitempty"`
	Size       int64                     `json:"size"`

	// State Current lifecycle state of the storage resource.
	State StorageState `json:"state"`

	// Tier Storage tier identifier.
	Tier  *StorageTier `json:"tier,omitempty"`
	Title string       `json:"title"`

	// Type Storage type filter
	Type StorageType `json:"type"`

	// Uuid Universally unique identifier
	Uuid StorageUuid `json:"uuid"`

	// Zone Zone identifier
	//
	// Examples: fi-hel1, de-fra1, us-nyc1
	Zone                 *StorageZone           `json:"zone,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// StorageDetailsPartOfPlan defines model for StorageDetails.PartOfPlan.
type StorageDetailsPartOfPlan string

// StorageEncrypted Indicates whether the resource is encrypted.
//
// Examples: yes, no
type StorageEncrypted string

// StorageError A general error response indicating that the request could not be fulfilled due to a technical issue.
type StorageError struct {
	Error struct {
		// ErrorCode Examples: GENERAL_FAILURE
		ErrorCode string `json:"error_code"`

		// ErrorMessage Examples: Your request could not be fulfilled due to a technical issue.
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// StorageFavorite Filter storages by favorite status
//
// Examples: yes, no
type StorageFavorite string

// StorageLabel A key/value pair to label and categorize resources
type StorageLabel struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

// StorageLabelFilter Label filter in format key=value or !key=value for negation
//
// Examples: environment=production, !temporary=true
type StorageLabelFilter = string

// StorageLimit Maximum number of items to return. Default is 25.
//
// Examples: 25, 50, 100
type StorageLimit = int

// StorageMetadata Whether to include metadata in the response
//
// Examples: yes, no
type StorageMetadata string

// StorageOffset Number of items to skip before starting to return results. Default is 0.
//
// Examples: 0, 25, 50, 100
type StorageOffset = int

// StorageOrderBy Sort order for storage results
type StorageOrderBy string

// StorageSearch Search storages by title or UUID (partial match)
//
// Examples: my-storage
type StorageSearch = string

// StorageServers Whether to include server information in the response
//
// Examples: yes, no
type StorageServers string

// StorageSortBy Field to sort storage results by
type StorageSortBy string

// StorageState Current lifecycle state of the storage resource.
type StorageState string

// StorageTier Storage tier identifier.
type StorageTier = string

// StorageTitle Human-readable title for a resource.
type StorageTitle = string

// StorageType Storage type filter
type StorageType string

// StorageUpdateTemplateRequest Request schema for updating a storage template
type StorageUpdateTemplateRequest struct {
	UpdateTemplate struct {
		Source *string `json:"source,omitempty"`
	} `json:"update_template"`
}

// StorageUuid Universally unique identifier
type StorageUuid = openapi_types.UUID

// StorageZone Zone identifier
//
// Examples: fi-hel1, de-fra1, us-nyc1
type StorageZone = string

// Storages Response schema containing a list of storage resources.
type Storages struct {
	Storages struct {
		Storage []StorageDetails `json:"storage"`
	} `json:"storages"`
}

// AddStorageComponentUuid Universally unique identifier
type AddStorageComponentUuid = StorageUuid

// AddStorageToFavoritesUuid Universally unique identifier
type AddStorageToFavoritesUuid = StorageUuid

// AttachStorageToServerUuid Universally unique identifier
type AttachStorageToServerUuid = StorageUuid

// CancelStorageOperationUuid Universally unique identifier
type CancelStorageOperationUuid = StorageUuid

// CloneStorageUuid Universally unique identifier
type CloneStorageUuid = StorageUuid

// CreateTemplateFromStorageUuid Universally unique identifier
type CreateTemplateFromStorageUuid = StorageUuid

// DeleteStorageBackups defines model for deleteStorageBackups.
type DeleteStorageBackups string

// DeleteStorageUuid Universally unique identifier
type DeleteStorageUuid = StorageUuid

// DetachStorageFromServerUuid Universally unique identifier
type DetachStorageFromServerUuid = StorageUuid

// GetStorageInfoUuid Universally unique identifier
type GetStorageInfoUuid = StorageUuid

// GetStorageListAllowHidden Whether to include hidden storages in the response
//
// Examples: yes, no
type GetStorageListAllowHidden = StorageAllowHidden

// GetStorageListByBackupAllowHidden Whether to include hidden storages in the response
//
// Examples: yes, no
type GetStorageListByBackupAllowHidden = StorageAllowHidden

// GetStorageListByBackupFavorite Filter storages by favorite status
//
// Examples: yes, no
type GetStorageListByBackupFavorite = StorageFavorite

// GetStorageListByBackupLabel Label filter in format key=value or !key=value for negation
//
// Examples: environment=production, !temporary=true
type GetStorageListByBackupLabel = StorageLabelFilter

// GetStorageListByBackupLimit Maximum number of items to return. Default is 25.
//
// Examples: 25, 50, 100
type GetStorageListByBackupLimit = StorageLimit

// GetStorageListByBackupMetadata Whether to include metadata in the response
//
// Examples: yes, no
type GetStorageListByBackupMetadata = StorageMetadata

// GetStorageListByBackupOffset Number of items to skip before starting to return results. Default is 0.
//
// Examples: 0, 25, 50, 100
type GetStorageListByBackupOffset = StorageOffset

// GetStorageListByBackupOrderBy Sort order for storage results
type GetStorageListByBackupOrderBy = StorageOrderBy

// GetStorageListByBackupSearch Search storages by title or UUID (partial match)
//
// Examples: my-storage
type GetStorageListByBackupSearch = StorageSearch

// GetStorageListByBackupServers Whether to include server information in the response
//
// Examples: yes, no
type GetStorageListByBackupServers = StorageServers

// GetStorageListByBackupSortBy Field to sort storage results by
type GetStorageListByBackupSortBy = StorageSortBy

// GetStorageListByCdromAllowHidden Whether to include hidden storages in the response
//
// Examples: yes, no
type GetStorageListByCdromAllowHidden = StorageAllowHidden

// GetStorageListByCdromFavorite Filter storages by favorite status
//
// Examples: yes, no
type GetStorageListByCdromFavorite = StorageFavorite

// GetStorageListByCdromLabel Label filter in format key=value or !key=value for negation
//
// Examples: environment=production, !temporary=true
type GetStorageListByCdromLabel = StorageLabelFilter

// GetStorageListByCdromLimit Maximum number of items to return. Default is 25.
//
// Examples: 25, 50, 100
type GetStorageListByCdromLimit = StorageLimit

// GetStorageListByCdromMetadata Whether to include metadata in the response
//
// Examples: yes, no
type GetStorageListByCdromMetadata = StorageMetadata

// GetStorageListByCdromOffset Number of items to skip before starting to return results. Default is 0.
//
// Examples: 0, 25, 50, 100
type GetStorageListByCdromOffset = StorageOffset

// GetStorageListByCdromOrderBy Sort order for storage results
type GetStorageListByCdromOrderBy = StorageOrderBy

// GetStorageListByCdromSearch Search storages by title or UUID (partial match)
//
// Examples: my-storage
type GetStorageListByCdromSearch = StorageSearch

// GetStorageListByCdromServers Whether to include server information in the response
//
// Examples: yes, no
type GetStorageListByCdromServers = StorageServers

// GetStorageListByCdromSortBy Field to sort storage results by
type GetStorageListByCdromSortBy = StorageSortBy

// GetStorageListByNormalAllowHidden Whether to include hidden storages in the response
//
// Examples: yes, no
type GetStorageListByNormalAllowHidden = StorageAllowHidden

// GetStorageListByNormalFavorite Filter storages by favorite status
//
// Examples: yes, no
type GetStorageListByNormalFavorite = StorageFavorite

// GetStorageListByNormalLabel Label filter in format key=value or !key=value for negation
//
// Examples: environment=production, !temporary=true
type GetStorageListByNormalLabel = StorageLabelFilter

// GetStorageListByNormalLimit Maximum number of items to return. Default is 25.
//
// Examples: 25, 50, 100
type GetStorageListByNormalLimit = StorageLimit

// GetStorageListByNormalMetadata Whether to include metadata in the response
//
// Examples: yes, no
type GetStorageListByNormalMetadata = StorageMetadata

// GetStorageListByNormalOffset Number of items to skip before starting to return results. Default is 0.
//
// Examples: 0, 25, 50, 100
type GetStorageListByNormalOffset = StorageOffset

// GetStorageListByNormalOrderBy Sort order for storage results
type GetStorageListByNormalOrderBy = StorageOrderBy

// GetStorageListByNormalSearch Search storages by title or UUID (partial match)
//
// Examples: my-storage
type GetStorageListByNormalSearch = StorageSearch

// GetStorageListByNormalServers Whether to include server information in the response
//
// Examples: yes, no
type GetStorageListByNormalServers = StorageServers

// GetStorageListByNormalSortBy Field to sort storage results by
type GetStorageListByNormalSortBy = StorageSortBy

// GetStorageListByTemplateAllowHidden Whether to include hidden storages in the response
//
// Examples: yes, no
type GetStorageListByTemplateAllowHidden = StorageAllowHidden

// GetStorageListByTemplateFavorite Filter storages by favorite status
//
// Examples: yes, no
type GetStorageListByTemplateFavorite = StorageFavorite

// GetStorageListByTemplateLabel Label filter in format key=value or !key=value for negation
//
// Examples: environment=production, !temporary=true
type GetStorageListByTemplateLabel = StorageLabelFilter

// GetStorageListByTemplateLimit Maximum number of items to return. Default is 25.
//
// Examples: 25, 50, 100
type GetStorageListByTemplateLimit = StorageLimit

// GetStorageListByTemplateMetadata Whether to include metadata in the response
//
// Examples: yes, no
type GetStorageListByTemplateMetadata = StorageMetadata

// GetStorageListByTemplateOffset Number of items to skip before starting to return results. Default is 0.
//
// Examples: 0, 25, 50, 100
type GetStorageListByTemplateOffset = StorageOffset

// GetStorageListByTemplateOrderBy Sort order for storage results
type GetStorageListByTemplateOrderBy = StorageOrderBy

// GetStorageListByTemplateSearch Search storages by title or UUID (partial match)
//
// Examples: my-storage
type GetStorageListByTemplateSearch = StorageSearch

// GetStorageListByTemplateServers Whether to include server information in the response
//
// Examples: yes, no
type GetStorageListByTemplateServers = StorageServers

// GetStorageListByTemplateSortBy Field to sort storage results by
type GetStorageListByTemplateSortBy = StorageSortBy

// GetStorageListByTypeAndAccessAccess Storage access level filter
type GetStorageListByTypeAndAccessAccess = StorageAccessFilter

// GetStorageListByTypeAndAccessAllowHidden Whether to include hidden storages in the response
//
// Examples: yes, no
type GetStorageListByTypeAndAccessAllowHidden = StorageAllowHidden

// GetStorageListByTypeAndAccessFavorite Filter storages by favorite status
//
// Examples: yes, no
type GetStorageListByTypeAndAccessFavorite = StorageFavorite

// GetStorageListByTypeAndAccessLabel Label filter in format key=value or !key=value for negation
//
// Examples: environment=production, !temporary=true
type GetStorageListByTypeAndAccessLabel = StorageLabelFilter

// GetStorageListByTypeAndAccessLimit Maximum number of items to return. Default is 25.
//
// Examples: 25, 50, 100
type GetStorageListByTypeAndAccessLimit = StorageLimit

// GetStorageListByTypeAndAccessMetadata Whether to include metadata in the response
//
// Examples: yes, no
type GetStorageListByTypeAndAccessMetadata = StorageMetadata

// GetStorageListByTypeAndAccessOffset Number of items to skip before starting to return results. Default is 0.
//
// Examples: 0, 25, 50, 100
type GetStorageListByTypeAndAccessOffset = StorageOffset

// GetStorageListByTypeAndAccessOrderBy Sort order for storage results
type GetStorageListByTypeAndAccessOrderBy = StorageOrderBy

// GetStorageListByTypeAndAccessSearch Search storages by title or UUID (partial match)
//
// Examples: my-storage
type GetStorageListByTypeAndAccessSearch = StorageSearch

// GetStorageListByTypeAndAccessServers Whether to include server information in the response
//
// Examples: yes, no
type GetStorageListByTypeAndAccessServers = StorageServers

// GetStorageListByTypeAndAccessSortBy Field to sort storage results by
type GetStorageListByTypeAndAccessSortBy = StorageSortBy

// GetStorageListByTypeAndAccessType Storage type filter
type GetStorageListByTypeAndAccessType = StorageType

// GetStorageListFavorite Filter storages by favorite status
//
// Examples: yes, no
type GetStorageListFavorite = StorageFavorite

// GetStorageListLabel Label filter in format key=value or !key=value for negation
//
// Examples: environment=production, !temporary=true
type GetStorageListLabel = StorageLabelFilter

// GetStorageListLimit Maximum number of items to return. Default is 25.
//
// Examples: 25, 50, 100
type GetStorageListLimit = StorageLimit

// GetStorageListMetadata Whether to include metadata in the response
//
// Examples: yes, no
type GetStorageListMetadata = StorageMetadata

// GetStorageListOffset Number of items to skip before starting to return results. Default is 0.
//
// Examples: 0, 25, 50, 100
type GetStorageListOffset = StorageOffset

// GetStorageListOrderBy Sort order for storage results
type GetStorageListOrderBy = StorageOrderBy

// GetStorageListSearch Search storages by title or UUID (partial match)
//
// Examples: my-storage
type GetStorageListSearch = StorageSearch

// GetStorageListServers Whether to include server information in the response
//
// Examples: yes, no
type GetStorageListServers = StorageServers

// GetStorageListSortBy Field to sort storage results by
type GetStorageListSortBy = StorageSortBy

// ModifyStorageUuid Universally unique identifier
type ModifyStorageUuid = StorageUuid

// RemoveStorageFromFavoritesUuid Universally unique identifier
type RemoveStorageFromFavoritesUuid = StorageUuid

// ResizeStorageUuid Universally unique identifier
type ResizeStorageUuid = StorageUuid

// RestoreStorageFromBackupUuid Universally unique identifier
type RestoreStorageFromBackupUuid = StorageUuid

// StorageCreateOnDemandBackupUuid Universally unique identifier
type StorageCreateOnDemandBackupUuid = StorageUuid

// StorageUpdatePublicTemplateFromSourceUuid Universally unique identifier
type StorageUpdatePublicTemplateFromSourceUuid = StorageUuid

// AddStorageComponentDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type AddStorageComponentDefault = StorageError

// AddStorageToFavoritesDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type AddStorageToFavoritesDefault = StorageError

// AttachStorageToServerDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type AttachStorageToServerDefault = StorageError

// CancelStorageOperationDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CancelStorageOperationDefault = StorageError

// CloneStorage201 Created storage
type CloneStorage201 = CreateStorageResponse

// CloneStorageDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CloneStorageDefault = StorageError

// CreateCDROMStorage201 Created storage
type CreateCDROMStorage201 = CreateStorageResponse

// CreateCDROMStorageDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateCDROMStorageDefault = StorageError

// CreateStorage201 Created storage
type CreateStorage201 = CreateStorageResponse

// CreateStorageDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateStorageDefault = StorageError

// CreateTemplateFromStorage201 Created storage
type CreateTemplateFromStorage201 = CreateStorageResponse

// CreateTemplateFromStorageDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateTemplateFromStorageDefault = StorageError

// DeleteStorageDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteStorageDefault = StorageError

// DetachStorageFromServerDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type DetachStorageFromServerDefault = StorageError

// GetFavoriteStorageList200 Response schema containing a list of storage resources.
type GetFavoriteStorageList200 = Storages

// GetFavoriteStorageListDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetFavoriteStorageListDefault = StorageError

// GetStorageInfo200 Response schema containing a single storage resource.
type GetStorageInfo200 = Storage

// GetStorageInfoDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageInfoDefault = StorageError

// GetStorageList200 Response schema containing a list of storage resources.
type GetStorageList200 = Storages

// GetStorageList400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageList400 = StorageError

// GetStorageListByBackup200 Response schema containing a list of storage resources.
type GetStorageListByBackup200 = Storages

// GetStorageListByBackup400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByBackup400 = StorageError

// GetStorageListByBackupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByBackupDefault = StorageError

// GetStorageListByCdrom200 Response schema containing a list of storage resources.
type GetStorageListByCdrom200 = Storages

// GetStorageListByCdrom400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByCdrom400 = StorageError

// GetStorageListByCdromDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByCdromDefault = StorageError

// GetStorageListByNormal200 Response schema containing a list of storage resources.
type GetStorageListByNormal200 = Storages

// GetStorageListByNormal400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByNormal400 = StorageError

// GetStorageListByNormalDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByNormalDefault = StorageError

// GetStorageListByTemplate200 Response schema containing a list of storage resources.
type GetStorageListByTemplate200 = Storages

// GetStorageListByTemplate400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByTemplate400 = StorageError

// GetStorageListByTemplateDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByTemplateDefault = StorageError

// GetStorageListByTypeAndAccess200 Response schema containing a list of storage resources.
type GetStorageListByTypeAndAccess200 = Storages

// GetStorageListByTypeAndAccess400 A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByTypeAndAccess400 = StorageError

// GetStorageListByTypeAndAccessDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListByTypeAndAccessDefault = StorageError

// GetStorageListDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetStorageListDefault = StorageError

// ModifyStorage200 Response schema for storage modification operations.
type ModifyStorage200 = ModifyStorageResponse

// ModifyStorageDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyStorageDefault = StorageError

// RemoveStorageFromFavoritesDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type RemoveStorageFromFavoritesDefault = StorageError

// ResizeStorage200 Response schema for resizing a storage volume.
type ResizeStorage200 = ResizeStorageResponse

// ResizeStorageDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ResizeStorageDefault = StorageError

// RestoreStorageFromBackupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type RestoreStorageFromBackupDefault = StorageError

// StorageCreateOnDemandBackup201 Created storage
type StorageCreateOnDemandBackup201 = CreateStorageResponse

// StorageCreateOnDemandBackupDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type StorageCreateOnDemandBackupDefault = StorageError

// StorageUpdatePublicTemplateFromSourceDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type StorageUpdatePublicTemplateFromSourceDefault = StorageError

// AddStorageComponent Schema for adding a storage component to a storage device
type AddStorageComponent = AddStorageComponentRequest

// AttachStorageToServer Schema for attaching a storage device to a server
type AttachStorageToServer = AttachStorage

// CloneStorage TODO
type CloneStorage = CloneStorageRequest

// CreateCDROMStorage Schema for creating a new CD-ROM image
type CreateCDROMStorage = StorageCreateCdromRequest

// CreateStorage Request schema for creating a storage
type CreateStorage = CreateStorageRequest

// CreateTemplateFromStorage Request schema for creating a storage template
type CreateTemplateFromStorage = CreateStorageTemplateRequest

// ModifyStorage Request schema for modifying storage properties.
type ModifyStorage = ModifyStorageBody

// StorageCreateOnDemandBackup Backup rule configuration for storage backups.
type StorageCreateOnDemandBackup = CreateStorageBackupRequest

// StorageUpdatePublicTemplateFromSource Request schema for updating a storage template
type StorageUpdatePublicTemplateFromSource = StorageUpdateTemplateRequest

// GetStorageListParams defines parameters for GetStorageList.
type GetStorageListParams struct {
	// Label Filter by labels. Can be specified multiple times.
	Label *GetStorageListLabel `form:"label,omitempty" json:"label,omitempty"`

	// Search Search storages by title or UUID (partial match)
	Search *GetStorageListSearch `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sort results by the specified field
	SortBy *GetStorageListSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// OrderBy Sort order (ascending or descending). Only valid when sort_by is also specified.
	OrderBy *GetStorageListOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// Limit Maximum number of storages to return per page
	Limit *GetStorageListLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of storages to skip before starting to return results
	Offset *GetStorageListOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// AllowHidden Include hidden storages in the response
	AllowHidden *GetStorageListAllowHidden `form:"allow_hidden,omitempty" json:"allow_hidden,omitempty"`

	// Favorite Filter storages by favorite status
	Favorite *GetStorageListFavorite `form:"favorite,omitempty" json:"favorite,omitempty"`

	// Metadata Whether to include metadata in the response
	Metadata *GetStorageListMetadata `form:"metadata,omitempty" json:"metadata,omitempty"`

	// Servers Whether to include server information in the response
	Servers *GetStorageListServers `form:"servers,omitempty" json:"servers,omitempty"`
}

// GetStorageListByBackupParams defines parameters for GetStorageListByBackup.
type GetStorageListByBackupParams struct {
	// Label Filter by labels. Can be specified multiple times.
	Label *GetStorageListByBackupLabel `form:"label,omitempty" json:"label,omitempty"`

	// Search Search storages by title or UUID (partial match)
	Search *GetStorageListByBackupSearch `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sort results by the specified field
	SortBy *GetStorageListByBackupSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// OrderBy Sort order (ascending or descending). Only valid when sort_by is also specified.
	OrderBy *GetStorageListByBackupOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// Limit Maximum number of storages to return per page
	Limit *GetStorageListByBackupLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of storages to skip before starting to return results
	Offset *GetStorageListByBackupOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// AllowHidden Include hidden storages in the response
	AllowHidden *GetStorageListByBackupAllowHidden `form:"allow_hidden,omitempty" json:"allow_hidden,omitempty"`

	// Favorite Filter storages by favorite status
	Favorite *GetStorageListByBackupFavorite `form:"favorite,omitempty" json:"favorite,omitempty"`

	// Metadata Whether to include metadata in the response
	Metadata *GetStorageListByBackupMetadata `form:"metadata,omitempty" json:"metadata,omitempty"`

	// Servers Whether to include server information in the response
	Servers *GetStorageListByBackupServers `form:"servers,omitempty" json:"servers,omitempty"`
}

// GetStorageListByCdromParams defines parameters for GetStorageListByCdrom.
type GetStorageListByCdromParams struct {
	// Label Filter by labels. Can be specified multiple times.
	Label *GetStorageListByCdromLabel `form:"label,omitempty" json:"label,omitempty"`

	// Search Search storages by title or UUID (partial match)
	Search *GetStorageListByCdromSearch `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sort results by the specified field
	SortBy *GetStorageListByCdromSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// OrderBy Sort order (ascending or descending). Only valid when sort_by is also specified.
	OrderBy *GetStorageListByCdromOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// Limit Maximum number of storages to return per page
	Limit *GetStorageListByCdromLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of storages to skip before starting to return results
	Offset *GetStorageListByCdromOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// AllowHidden Include hidden storages in the response
	AllowHidden *GetStorageListByCdromAllowHidden `form:"allow_hidden,omitempty" json:"allow_hidden,omitempty"`

	// Favorite Filter storages by favorite status
	Favorite *GetStorageListByCdromFavorite `form:"favorite,omitempty" json:"favorite,omitempty"`

	// Metadata Whether to include metadata in the response
	Metadata *GetStorageListByCdromMetadata `form:"metadata,omitempty" json:"metadata,omitempty"`

	// Servers Whether to include server information in the response
	Servers *GetStorageListByCdromServers `form:"servers,omitempty" json:"servers,omitempty"`
}

// GetStorageListByNormalParams defines parameters for GetStorageListByNormal.
type GetStorageListByNormalParams struct {
	// Label Filter by labels. Can be specified multiple times.
	Label *GetStorageListByNormalLabel `form:"label,omitempty" json:"label,omitempty"`

	// Search Search storages by title or UUID (partial match)
	Search *GetStorageListByNormalSearch `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sort results by the specified field
	SortBy *GetStorageListByNormalSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// OrderBy Sort order (ascending or descending). Only valid when sort_by is also specified.
	OrderBy *GetStorageListByNormalOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// Limit Maximum number of storages to return per page
	Limit *GetStorageListByNormalLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of storages to skip before starting to return results
	Offset *GetStorageListByNormalOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// AllowHidden Include hidden storages in the response
	AllowHidden *GetStorageListByNormalAllowHidden `form:"allow_hidden,omitempty" json:"allow_hidden,omitempty"`

	// Favorite Filter storages by favorite status
	Favorite *GetStorageListByNormalFavorite `form:"favorite,omitempty" json:"favorite,omitempty"`

	// Metadata Whether to include metadata in the response
	Metadata *GetStorageListByNormalMetadata `form:"metadata,omitempty" json:"metadata,omitempty"`

	// Servers Whether to include server information in the response
	Servers *GetStorageListByNormalServers `form:"servers,omitempty" json:"servers,omitempty"`
}

// GetStorageListByTemplateParams defines parameters for GetStorageListByTemplate.
type GetStorageListByTemplateParams struct {
	// Label Filter by labels. Can be specified multiple times.
	Label *GetStorageListByTemplateLabel `form:"label,omitempty" json:"label,omitempty"`

	// Search Search storages by title or UUID (partial match)
	Search *GetStorageListByTemplateSearch `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sort results by the specified field
	SortBy *GetStorageListByTemplateSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// OrderBy Sort order (ascending or descending). Only valid when sort_by is also specified.
	OrderBy *GetStorageListByTemplateOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// Limit Maximum number of storages to return per page
	Limit *GetStorageListByTemplateLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of storages to skip before starting to return results
	Offset *GetStorageListByTemplateOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// AllowHidden Include hidden storages in the response
	AllowHidden *GetStorageListByTemplateAllowHidden `form:"allow_hidden,omitempty" json:"allow_hidden,omitempty"`

	// Favorite Filter storages by favorite status
	Favorite *GetStorageListByTemplateFavorite `form:"favorite,omitempty" json:"favorite,omitempty"`

	// Metadata Whether to include metadata in the response
	Metadata *GetStorageListByTemplateMetadata `form:"metadata,omitempty" json:"metadata,omitempty"`

	// Servers Whether to include server information in the response
	Servers *GetStorageListByTemplateServers `form:"servers,omitempty" json:"servers,omitempty"`
}

// GetStorageListByTypeAndAccessParams defines parameters for GetStorageListByTypeAndAccess.
type GetStorageListByTypeAndAccessParams struct {
	// Label Filter by labels. Can be specified multiple times.
	Label *GetStorageListByTypeAndAccessLabel `form:"label,omitempty" json:"label,omitempty"`

	// Search Search storages by title or UUID (partial match)
	Search *GetStorageListByTypeAndAccessSearch `form:"search,omitempty" json:"search,omitempty"`

	// SortBy Sort results by the specified field
	SortBy *GetStorageListByTypeAndAccessSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`

	// OrderBy Sort order (ascending or descending). Only valid when sort_by is also specified.
	OrderBy *GetStorageListByTypeAndAccessOrderBy `form:"order_by,omitempty" json:"order_by,omitempty"`

	// Limit Maximum number of storages to return per page
	Limit *GetStorageListByTypeAndAccessLimit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of storages to skip before starting to return results
	Offset *GetStorageListByTypeAndAccessOffset `form:"offset,omitempty" json:"offset,omitempty"`

	// AllowHidden Include hidden storages in the response
	AllowHidden *GetStorageListByTypeAndAccessAllowHidden `form:"allow_hidden,omitempty" json:"allow_hidden,omitempty"`

	// Favorite Filter storages by favorite status
	Favorite *GetStorageListByTypeAndAccessFavorite `form:"favorite,omitempty" json:"favorite,omitempty"`

	// Metadata Whether to include metadata in the response
	Metadata *GetStorageListByTypeAndAccessMetadata `form:"metadata,omitempty" json:"metadata,omitempty"`

	// Servers Whether to include server information in the response
	Servers *GetStorageListByTypeAndAccessServers `form:"servers,omitempty" json:"servers,omitempty"`
}

// DeleteStorageParams defines parameters for DeleteStorage.
type DeleteStorageParams struct {
	// Backups Policy for handling backups when deleting a storage. Allowed values: keep, delete, keep_latest
	Backups *DeleteStorageParamsBackups `form:"backups,omitempty" json:"backups,omitempty"`
}

// DeleteStorageParamsBackups defines parameters for DeleteStorage.
type DeleteStorageParamsBackups string

// CreateStorageJSONRequestBody defines body for CreateStorage for application/json ContentType.
type CreateStorageJSONRequestBody = CreateStorageRequest

// CreateCDROMStorageJSONRequestBody defines body for CreateCDROMStorage for application/json ContentType.
type CreateCDROMStorageJSONRequestBody = StorageCreateCdromRequest

// ModifyStorageJSONRequestBody defines body for ModifyStorage for application/json ContentType.
type ModifyStorageJSONRequestBody = ModifyStorageBody

// AddStorageComponentJSONRequestBody defines body for AddStorageComponent for application/json ContentType.
type AddStorageComponentJSONRequestBody = AddStorageComponentRequest

// AttachStorageToServerJSONRequestBody defines body for AttachStorageToServer for application/json ContentType.
type AttachStorageToServerJSONRequestBody = AttachStorage

// CreateOnDemandBackupJSONRequestBody defines body for CreateOnDemandBackup for application/json ContentType.
type CreateOnDemandBackupJSONRequestBody = CreateStorageBackupRequest

// CloneStorageJSONRequestBody defines body for CloneStorage for application/json ContentType.
type CloneStorageJSONRequestBody = CloneStorageRequest

// CreateTemplateFromStorageJSONRequestBody defines body for CreateTemplateFromStorage for application/json ContentType.
type CreateTemplateFromStorageJSONRequestBody = CreateStorageTemplateRequest

// UpdatePublicTemplateFromSourceJSONRequestBody defines body for UpdatePublicTemplateFromSource for application/json ContentType.
type UpdatePublicTemplateFromSourceJSONRequestBody = StorageUpdateTemplateRequest

// Getter for additional properties for StorageDetails. Returns the specified
// element and whether it was found
func (a StorageDetails) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for StorageDetails
func (a *StorageDetails) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for StorageDetails to handle AdditionalProperties
func (a *StorageDetails) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access"]; found {
		err = json.Unmarshal(raw, &a.Access)
		if err != nil {
			return fmt.Errorf("error reading 'access': %w", err)
		}
		delete(object, "access")
	}

	if raw, found := object["encrypted"]; found {
		err = json.Unmarshal(raw, &a.Encrypted)
		if err != nil {
			return fmt.Errorf("error reading 'encrypted': %w", err)
		}
		delete(object, "encrypted")
	}

	if raw, found := object["labels"]; found {
		err = json.Unmarshal(raw, &a.Labels)
		if err != nil {
			return fmt.Errorf("error reading 'labels': %w", err)
		}
		delete(object, "labels")
	}

	if raw, found := object["license"]; found {
		err = json.Unmarshal(raw, &a.License)
		if err != nil {
			return fmt.Errorf("error reading 'license': %w", err)
		}
		delete(object, "license")
	}

	if raw, found := object["metadata"]; found {
		err = json.Unmarshal(raw, &a.Metadata)
		if err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["part_of_plan"]; found {
		err = json.Unmarshal(raw, &a.PartOfPlan)
		if err != nil {
			return fmt.Errorf("error reading 'part_of_plan': %w", err)
		}
		delete(object, "part_of_plan")
	}

	if raw, found := object["size"]; found {
		err = json.Unmarshal(raw, &a.Size)
		if err != nil {
			return fmt.Errorf("error reading 'size': %w", err)
		}
		delete(object, "size")
	}

	if raw, found := object["state"]; found {
		err = json.Unmarshal(raw, &a.State)
		if err != nil {
			return fmt.Errorf("error reading 'state': %w", err)
		}
		delete(object, "state")
	}

	if raw, found := object["tier"]; found {
		err = json.Unmarshal(raw, &a.Tier)
		if err != nil {
			return fmt.Errorf("error reading 'tier': %w", err)
		}
		delete(object, "tier")
	}

	if raw, found := object["title"]; found {
		err = json.Unmarshal(raw, &a.Title)
		if err != nil {
			return fmt.Errorf("error reading 'title': %w", err)
		}
		delete(object, "title")
	}

	if raw, found := object["type"]; found {
		err = json.Unmarshal(raw, &a.Type)
		if err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["uuid"]; found {
		err = json.Unmarshal(raw, &a.Uuid)
		if err != nil {
			return fmt.Errorf("error reading 'uuid': %w", err)
		}
		delete(object, "uuid")
	}

	if raw, found := object["zone"]; found {
		err = json.Unmarshal(raw, &a.Zone)
		if err != nil {
			return fmt.Errorf("error reading 'zone': %w", err)
		}
		delete(object, "zone")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for StorageDetails to handle AdditionalProperties
func (a StorageDetails) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["access"], err = json.Marshal(a.Access)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'access': %w", err)
	}

	object["encrypted"], err = json.Marshal(a.Encrypted)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'encrypted': %w", err)
	}

	if a.Labels != nil {
		object["labels"], err = json.Marshal(a.Labels)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'labels': %w", err)
		}
	}

	object["license"], err = json.Marshal(a.License)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'license': %w", err)
	}

	if a.Metadata != nil {
		object["metadata"], err = json.Marshal(a.Metadata)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
		}
	}

	if a.PartOfPlan != nil {
		object["part_of_plan"], err = json.Marshal(a.PartOfPlan)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'part_of_plan': %w", err)
		}
	}

	object["size"], err = json.Marshal(a.Size)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'size': %w", err)
	}

	object["state"], err = json.Marshal(a.State)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'state': %w", err)
	}

	if a.Tier != nil {
		object["tier"], err = json.Marshal(a.Tier)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'tier': %w", err)
		}
	}

	object["title"], err = json.Marshal(a.Title)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'title': %w", err)
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	object["uuid"], err = json.Marshal(a.Uuid)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'uuid': %w", err)
	}

	if a.Zone != nil {
		object["zone"], err = json.Marshal(a.Zone)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'zone': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}
