// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// DatabaseDependencyResponse a dependency definition
type DatabaseDependencyResponse struct {
	// Required List of required properties when this dependency is present
	Required *[]string `json:"required,omitempty"`
}

// DatabasePropertySchemaResponse Schema definition for a single property
type DatabasePropertySchemaResponse struct {
	// Id Schema identifier
	Id *string `json:"$id,omitempty"`

	// Schema JSON Schema URI
	Schema *string `json:"$schema,omitempty"`

	// AdditionalProperties Whether additional properties are allowed
	AdditionalProperties *bool `json:"additionalProperties,omitempty"`

	// CreateOnly Whether the property can only be set during creation
	CreateOnly *bool `json:"createOnly,omitempty"`

	// Default Any valid JSON value is allowed here
	Default *map[string]interface{} `json:"default,omitempty"`

	// Dependencies Property dependency collection
	Dependencies *map[string]DatabaseDependencyResponse `json:"dependencies,omitempty"`

	// Description Description of the property
	Description *string `json:"description,omitempty"`

	// Enum Enumeration of allowed values
	Enum *[]interface{} `json:"enum,omitempty"`

	// Example Any valid JSON value is allowed here
	Example *map[string]interface{} `json:"example,omitempty"`

	// Items Schema definition for a single property
	Items *DatabasePropertySchemaResponse `json:"items,omitempty"`

	// MaxItems Maximum number of items for arrays
	MaxItems *int32 `json:"maxItems,omitempty"`

	// MaxLength Maximum length for the property schema
	MaxLength *int32 `json:"maxLength,omitempty"`

	// Maximum Maximum values for numeric properties
	Maximum *[]map[string]interface{} `json:"maximum,omitempty"`

	// MinLength Minimum length for the property schema
	MinLength *int32 `json:"minLength,omitempty"`

	// Minimum Minimum values for numeric properties
	Minimum *[]map[string]interface{} `json:"minimum,omitempty"`

	// Pattern Allowed patterns for the property
	Pattern *string `json:"pattern,omitempty"`

	// Properties Properties for object type
	Properties *map[string]DatabasePropertySchemaResponse `json:"properties,omitempty"`

	// Required List of required properties
	Required *[]string `json:"required,omitempty"`

	// Title Human-readable title for the property
	Title *string `json:"title,omitempty"`

	// Type Data type of the property
	Type *string `json:"type,omitempty"`

	// UserError User-friendly error message
	UserError *string `json:"user_error,omitempty"`
}

// KubernetesName Name
type KubernetesName = string

// KubernetesNodeName Node name
type KubernetesNodeName = string

// KubernetesUuid UUID
type KubernetesUuid = openapi_types.UUID

// Tag defines model for tag.
type Tag struct {
	Tag struct {
		Description *TagDescription `json:"description,omitempty"`
		Name        TagName         `json:"name"`

		// Servers List of servers associated with the tag.
		Servers TagServers `json:"servers"`
	} `json:"tag"`
}

// TagDescription defines model for tagDescription.
type TagDescription = string

// TagError A general error response indicating that the request could not be fulfilled due to a technical issue.
type TagError struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// TagError400 400 Bad Request errors for tag operations.
type TagError400 struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// TagError403 400 Forbidden errors for tag operations.
type TagError403 struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// TagError404 404 Not Found errors for tag operations.
type TagError404 struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// TagError409 409 Conflict errors for tag operations.
type TagError409 struct {
	Error struct {
		ErrorCode    string `json:"error_code"`
		ErrorMessage string `json:"error_message"`
	} `json:"error"`
}

// TagName defines model for tagName.
type TagName = string

// TagServers List of servers associated with the tag.
type TagServers struct {
	Server *[]openapi_types.UUID `json:"server,omitempty"`
}

// Tags defines model for tags.
type Tags struct {
	Tags struct {
		Tag []struct {
			Description *TagDescription `json:"description,omitempty"`
			Name        TagName         `json:"name"`

			// Servers List of servers associated with the tag.
			Servers TagServers `json:"servers"`
		} `json:"tag"`
	} `json:"tags"`
}

// DeleteTagName defines model for deleteTagName.
type DeleteTagName = TagName

// GetTagName defines model for getTagName.
type GetTagName = TagName

// KubernetesNameParameter Name
type KubernetesNameParameter = KubernetesName

// KubernetesNodeNameParameter Node name
type KubernetesNodeNameParameter = KubernetesNodeName

// KubernetesUuidParameter UUID
type KubernetesUuidParameter = KubernetesUuid

// ModifyTagName defines model for modifyTagName.
type ModifyTagName = TagName

// CreateTag200 defines model for createTag200.
type CreateTag200 = Tag

// CreateTag400 400 Bad Request errors for tag operations.
type CreateTag400 = TagError400

// CreateTag403 400 Forbidden errors for tag operations.
type CreateTag403 = TagError403

// CreateTag409 409 Conflict errors for tag operations.
type CreateTag409 = TagError409

// CreateTagDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type CreateTagDefault = TagError

// DeleteTag400 400 Bad Request errors for tag operations.
type DeleteTag400 = TagError400

// DeleteTag403 400 Forbidden errors for tag operations.
type DeleteTag403 = TagError403

// DeleteTag404 404 Not Found errors for tag operations.
type DeleteTag404 = TagError404

// DeleteTagDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type DeleteTagDefault = TagError

// GetTag200 defines model for getTag200.
type GetTag200 = Tag

// GetTag400 400 Bad Request errors for tag operations.
type GetTag400 = TagError400

// GetTag403 400 Forbidden errors for tag operations.
type GetTag403 = TagError403

// GetTag404 404 Not Found errors for tag operations.
type GetTag404 = TagError404

// GetTagDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type GetTagDefault = TagError

// ListTags200 defines model for listTags200.
type ListTags200 = Tags

// ListTagsDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ListTagsDefault = TagError

// ModifyTag200 defines model for modifyTag200.
type ModifyTag200 = Tag

// ModifyTag400 400 Bad Request errors for tag operations.
type ModifyTag400 = TagError400

// ModifyTag403 400 Forbidden errors for tag operations.
type ModifyTag403 = TagError403

// ModifyTag404 404 Not Found errors for tag operations.
type ModifyTag404 = TagError404

// ModifyTagDefault A general error response indicating that the request could not be fulfilled due to a technical issue.
type ModifyTagDefault = TagError

// CreateTag defines model for createTag.
type CreateTag = Tag

// ModifyTag defines model for modifyTag.
type ModifyTag = Tag

// CreateTagJSONRequestBody defines body for CreateTag for application/json ContentType.
type CreateTagJSONRequestBody = Tag

// ModifyTagJSONRequestBody defines body for ModifyTag for application/json ContentType.
type ModifyTagJSONRequestBody = Tag
