// Package upcloud provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package upcloud

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
)

// The interface specification for the client above.
type TimezoneClientInterface interface {
	// ListTimezones request
	ListTimezones(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListTimezones(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListTimezonesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListTimezonesRequest generates requests for ListTimezones
func NewListTimezonesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/1.3/timezone")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type TimezoneClientWithResponsesInterface interface {
	// ListTimezonesWithResponse request
	ListTimezonesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListTimezonesResp, error)
}

type ListTimezonesResp struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListTimezones200
	JSONDefault  *ListTimezonesDefault
}

// Status returns HTTPResponse.Status
func (r ListTimezonesResp) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListTimezonesResp) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListTimezonesWithResponse request returning *ListTimezonesResp
func (c *ClientWithResponses) ListTimezonesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListTimezonesResp, error) {
	rsp, err := c.ListTimezones(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListTimezonesResp(rsp)
}

// ParseListTimezonesResp parses an HTTP response from a ListTimezonesWithResponse call
func ParseListTimezonesResp(rsp *http.Response) (*ListTimezonesResp, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListTimezonesResp{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListTimezones200
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ListTimezonesDefault
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
